moped-editor/_redirects
moped-editor/package.json
moped-editor/src/app/App.jsx

The router changes worked for local development, but it does not play well with Netlify / CloudFront. Continued work on the same branch, and will create a new PR to address those issues.

MPE: Fix the routing

---

.github/workflows/atd_cognito_hooks_build.yml
moped-auth/cognito-pre-token-hook/handler.py

Closes https://github.com/cityofaustin/atd-data-tech/issues/4139

Keep Cogito Triggers Warm: 4139 

---

moped-api/app.py
moped-api/claims.py
moped-api/users/helpers.py
moped-api/users/users.py

Update production with user management API.

Update production with user management API

---

moped-database/metadata/tables.yaml

Closes https://github.com/cityofaustin/atd-data-tech/issues/3873
To check it works
```
$ ./hasura-cluster start
$./hasura-cluster console
```
[Documentation Page](https://app.gitbook.com/@atd-dts/s/moped-technical-docs/~/drafts/-MK5HDmotwDu2bQxuWHH/dev-guides/hasura/hasura-roles)

Moped | Implement Alpha permissions in Cognito and Hasura #3873

---

moped-database/hasura-cluster

Adds functionality to the hasura cluster to check if docker is already running, if not it handles the failure gracefully instead of showing a bunch of error logs.

Moped Database | Hasura Cluster Docker Status Check

---

moped-editor/.env-cmdrc
moped-editor/src/views/staff/StaffListView/StaffList.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4220

Update to use local hasura cluster instance

---

moped-auth/cognito-pre-token-hook/handler.py

Closes https://github.com/cityofaustin/atd-data-tech/issues/4454
This updates the token generator to load the Cognito UUID from DunamoDB and makes it part of the token for Hasura.

Moped | Single Sign On | Pre-token generator needs to know Cognito ID #4454

---

moped-editor/.env-cmdrc
moped-editor/src/App.js
moped-editor/src/auth/user.js

In this PR we've added some user auth helper functions that enable us to get tokens and roles based on different environment settings.

Get hasura endpoints working for staging & prod envs

---

moped-editor/package.json
moped-editor/public/index.html
moped-editor/src/layouts/DashboardLayout/NavBar/NavBar.js
moped-editor/src/layouts/DashboardLayout/TopBar.js
moped-editor/src/layouts/MainLayout/MainLayout.js
moped-editor/src/routes.js
moped-editor/src/views/auth/RegisterView.js
moped-editor/src/views/product/ProductListView/Toolbar.js
moped-editor/src/views/staff/Toolbar.js
moped-etl/LICENSE

This PR fixes (🤞 ) the bug I introduced where hitting the staging URL (https://moped.austinmobility.io/moped/) shows as a blank white page.

update sub folder routing /moped

---

moped-editor/src/components/Logo.js
moped-editor/src/index.js
moped-editor/src/layouts/DashboardLayout/TopBar.js
moped-editor/src/views/account/AccountView/Profile.js
moped-editor/src/views/errors/NotFoundView.js
moped-editor/src/views/product/ProductListView/data.js
moped-editor/src/views/reports/DashboardView/LatestProducts.js

No more broken images.
Followed these recommendations:
https://medium.com/@svinkle/how-to-deploy-a-react-app-to-a-subdirectory-f694d46427c1

Fix static assets in staging

---

moped-database/hasura-cluster

Prevents migrations from being applied to production or staging.

Fixes to hasura-cluster command

---

moped-editor/package.json

Closes https://github.com/cityofaustin/atd-data-tech/issues/4631
To test, simply run `npm run start` and check if the HTTPS is there (even if it says "not secure")

Moped Editor | Fix HTTPS on Start-Local #4631

---

moped-editor/package-lock.json
moped-editor/package.json
moped-editor/src/views/staff/StaffListView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4616

Kickstand | gqlAbtract.js updates and import into Moped Editor via Kickstand #4616

---

moped-api/claims.py

Closes https://github.com/cityofaustin/atd-data-tech/issues/4421

Adds support for SSO tokens for API Gateway #4421

---

moped-editor/src/auth/useAuthentication.js

This branch removes the need of the hosted ui
https://github.com/cityofaustin/atd-data-tech/issues/4654

Moped Editor | Skip Hosted UI #4654

---

moped-database/metadata/tables.yaml

To test, pull this branch and run hasura-cluster start and hasura-cluster console
for every table you should be able to see the permissions applied

Adds aggregation permissions to all roles

---

moped-editor/src/routes.js
moped-editor/src/views/projects/ProjectsListView.js
moped-editor/src/views/projects/ProjectsTable.js
moped-editor/src/views/projects/Toolbar.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4672

Project Listing | Implement basic project listing with Material UI table #4672

---

moped-editor/src/auth/user.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4680

Moped Editor | Direct path access | Routing issue #4680

---

moped-editor/src/views/projects/MapProjectGeometry.js
moped-editor/src/views/projects/NewProjectView.js
moped-editor/src/views/projects/ProjectTeamTable.js

Closes part of https://github.com/cityofaustin/atd-data-tech/issues/4544

Editor | Project definition follow up

---

.github/workflows/aws-moped-api-helper.sh
.gitignore

Closes https://github.com/cityofaustin/atd-data-tech/issues/4706

Moped API | Fix DevOps pipeline #4706

---

moped-database/metadata/tables.yaml

Closes https://github.com/cityofaustin/atd-data-tech/issues/4702

Moped Database | Fix problem with workgroups #4702

---

moped-editor/src/views/reports/DashboardView/Budget.js
moped-editor/src/views/reports/DashboardView/LatestOrders.js
moped-editor/src/views/reports/DashboardView/LatestProducts.js
moped-editor/src/views/reports/DashboardView/Sales.js
moped-editor/src/views/reports/DashboardView/TasksProgress.js
moped-editor/src/views/reports/DashboardView/TotalCustomers.js
moped-editor/src/views/reports/DashboardView/TotalProfit.js
moped-editor/src/views/reports/DashboardView/TrafficByDevice.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4670

Updates Dashboard titles and icons

---

moped-editor/src/routes.js
moped-editor/src/views/projects/NewProjectView.js
moped-editor/src/views/projects/ProjectSummary.js
moped-editor/src/views/projects/ProjectSummaryDetails.js
moped-editor/src/views/projects/ProjectsTable.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4525

Project summary updates

---

moped-editor/src/views/projects/NewProjectView.js
moped-editor/src/views/projects/ProjectTeamTable.js

Reverts cityofaustin/atd-moped#145
Reverting the merge of my branch into `4130_lz_nestedMutation` so that these changes (for https://github.com/cityofaustin/atd-data-tech/issues/4544) can be compared against `main` instead.

Revert "Editor | Project definition follow up"

---

moped-editor/src/views/projects/NewProjectView.js

This fixes a couple of console warnings that broke the `main` deploy.

Fix some console warnings

---

moped-editor/src/auth/useAuthentication.js
moped-editor/src/auth/user.js
moped-editor/src/views/auth/LoginView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4741
This PR adds a spinner that appears when either the email login or SSO login is used to access Moped. The [Backdrop MUI](https://material-ui.com/components/backdrop/) spinner component is used for now just make it super clear when the spinner is present. We can update to any other loading component.

Moped User Login | Give user feedback after a user submits their login

---

moped-editor/src/auth/user.js
moped-editor/src/views/account/AccountView/ProfileDetails.js
moped-editor/src/views/staff/helpers.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4651
This PR adds extends the `useUser` hook to expose whether a user is logged in with SSO or not. I also removed a duplicate function to get the user's JWT and updated the `useUserApi` hook deduped function.

User Management | Handle update password feature for SSO users

---

moped-database/metadata/tables.yaml

Closes https://github.com/cityofaustin/atd-data-tech/issues/4830
This PR updates the role permissions metadata for the `moped_project` table to allow appropriate access to the `project_extent_geojson` and `project_extent_ids` for each role.

Project Extent | Update permissions for user roles for new project extent fields

---

.github/workflows/atd_moped_db_docs.yml
moped-database/schemaspy/Dockerfile
moped-database/schemaspy/database.cfg
moped-database/schemaspy/document.sh
moped-database/schemaspy/generate-pk-map.py

Fixes DNS issues?
Fully working pipeline:
https://github.com/cityofaustin/atd-moped/runs/1767257162?check_suite_focus=true
Output Documentation (live staging and prod branches):
https://db-docs.austinmobility.io/atd-moped-staging/index.html
Primary Keys (for SQS jobs):
https://db-docs.austinmobility.io/maps/atd-moped-pk-map-staging.json
Closes https://github.com/cityofaustin/atd-data-tech/issues/5085

Automates Database Documentation

---

moped-database/migrations/1611865900241_moped_proj_personnel/down.sql
moped-database/migrations/1611865900241_moped_proj_personnel/up.sql

https://github.com/cityofaustin/atd-data-tech/issues/4974
With this migration we can see the database establish the relationship between the tables via Foreign Key:

Moped | Add relationship between moped_project_roles and moped_proj_personnel #4974

---

.github/workflows/atd_cognito_hooks_build.yml
.github/workflows/atd_moped_api.yml
.github/workflows/aws-moped-api-helper.sh
.github/workflows/aws-moped-sqs-helper.sh
moped-api/app.py
moped-api/claims.py
moped-api/tests/test_user_helpers.py
moped-api/users/helpers.py
moped-api/users/queries.py
moped-api/users/users.py
moped-auth/cognito-pre-token-hook/handler.py

Closes https://github.com/cityofaustin/atd-data-tech/issues/5129
This should extend the API functionality to include user_id and workgroup_id to the user token and dynamodb profile

Moped Editor | Add user_id (integer) to token #5129

---

moped-database/metadata/tables.yaml

Modifies nothing on the metadata except the event data from a previous commit: 250d1354a67a904f28276ea0da25ef72e1f690ad

Restores Events Metadata

---

moped-database/metadata/tables.yaml

Fixes this issue in the activity log tab:

Fixes permissions for activity log

---

moped-editor/src/auth/user.js
moped-editor/src/layouts/DashboardLayout/TopBar.js
moped-editor/src/views/account/AccountView/Profile.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4798
PR URL:
https://deploy-preview-202--atd-moped-main.netlify.app/

User Management | Implement default avatars #4798

---

moped-editor/src/layouts/DashboardLayout/TopBar.js
moped-editor/src/utils/emailToInitials.js
moped-editor/src/views/account/AccountView/Profile.js

This is what it should look like now:
https://deploy-preview-215--atd-moped-main.netlify.app/

Make use of user initials in the account page

---

moped-api/users/helpers.py
moped-api/users/queries.py
moped-database/metadata/tables.yaml
moped-database/migrations/1614280986665_alter_table_public_moped_users_add_column_roles/down.sql
moped-database/migrations/1614280986665_alter_table_public_moped_users_add_column_roles/up.sql

DB update for https://github.com/cityofaustin/atd-data-tech/issues/4994
Adds `roles` field as jsonb to the User table and updates permissions. All changes generated by Hasura.

User Management | Add roles field to user table

---

moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5314
Deploy Preview: https://deploy-preview-234--atd-moped-main.netlify.app/moped/projects

Remove date_added & capital_funded from Projects List

---

moped-api/users/helpers.py
moped-api/users/users.py

Fixes a the database_id and workgroup_id bug in the API

Moped Database | Problem with Cognito Entries in DynamoDB #5412

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectActivityLog.js
moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5456
Live Demo:
https://deploy-preview-238--atd-moped-main.netlify.app/moped/projects/180?tab=activity_log
It looks like this:

[Bug] Activity feed does not display all project changes as intended #5456

---

moped-database/metadata/tables.yaml
moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js

This is a patch to allow for the activity log to track file uploads and for the activity log to handle the updates in the UI

Activity log tracking for file uploads and activity log mapping

---

moped-editor/src/views/projects/projectView/ProjectTeamTable.js

Adds link to PR comment for more context
Decided to submit as a PR rather than push to main!

#5452 add project enter key bug

---

moped-editor/src/components/FileUpload/FileUploadDialogSingle.js
moped-editor/src/utils/humanReadableFileSize.js
moped-editor/src/views/projects/projectView/ProjectFiles.js
moped-editor/src/views/projects/projectView/ProjectView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5496
Live Demo:
https://5496-sg-fileupload-changes--atd-moped-main.netlify.app/moped/session/signin

Esthetic Adjustments

---

moped-data-events/activity_log/app.py

Closes https://github.com/cityofaustin/atd-data-tech/issues/5547
It's already invoking the lambda function successfully:

Make Activity Log Lambda Warmer #5547

---

moped-database/migrations/1616187574890_alter_table_public_moped_activity_log_alter_column_created_at/down.sql
moped-database/migrations/1616187574890_alter_table_public_moped_activity_log_alter_column_created_at/up.sql

Closes https://github.com/cityofaustin/atd-data-tech/issues/5543

Configure activity feed timestamps to display to users in CDT #5543

---

moped-editor/package-lock.json
moped-editor/package.json
moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectNameEditable.js
moped-editor/src/views/projects/projectView/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectView.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/4867
Live Demo:
https://deploy-preview-248--atd-moped-main.netlify.app/moped/session/signin
Deletion:
Edit Title:

Implement ability to soft-delete projects #4867

---

moped-editor/src/routes.js

Fixes https://github.com/cityofaustin/atd-data-tech/issues/5467

Updates landing page from Dashboard to Projects page

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/newProjectView/NewProjectView.js
moped-editor/src/views/projects/projectView/ProjectTeamRoleMultiselect.js
moped-editor/src/views/projects/projectView/ProjectTeamTable.js

It looks like the multi-select is stable now, let me know your thoughts.
The live demo should be functional at the new project page and the team tab:
https://deploy-preview-263--atd-moped-main.netlify.app/moped
If you are running locally, be sure to restart the hasura server so that the latest unique constraint is applied.
Closes https://github.com/cityofaustin/atd-data-tech/issues/5696

Multi-Select Project Personnel

---

moped-editor/src/utils/mapHelpers.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5794
Live Demo:
https://deploy-preview-277--atd-moped-main.netlify.app/moped/projects/156

Test patch for mabox styling WSOD error

---

moped-database/migrations/1618341519548_update_status/down.sql
moped-database/migrations/1618341519548_update_status/up.sql

Should be a breeze, the state is identical across all three stages.
Closes https://github.com/cityofaustin/atd-data-tech/issues/5251

[Database] Update project statuses #5251

---

moped-tools/main_rollback.py
moped-tools/rollback/moped_project.py

Closes https://github.com/cityofaustin/atd-data-tech/issues/5748

Moped Database | Write a script to wipe out data from staging, orderly #5748

---

moped-database/metadata/tables.yaml
moped-database/migrations/1618341519548_update_status/down.sql
moped-database/migrations/1618341519548_update_status/up.sql
moped-database/migrations/1618344795697_create_table_public_moped_subphases/down.sql
moped-database/migrations/1618344795697_create_table_public_moped_subphases/up.sql

This should be ready for review
Closes https://github.com/cityofaustin/atd-data-tech/issues/5744

Phases | Add subphases tables #5744

---

moped-editor/src/components/FileUpload/FileUploadDialogSimple.js
moped-editor/src/components/FileUpload/FileUploadDialogSingle.js
moped-editor/src/utils/mapHelpers.js
moped-editor/src/views/projects/projectView/ProjectFiles.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5810
Live Demo:
https://deploy-preview-276--atd-moped-main.netlify.app/moped/projects/188?tab=files
Fixes:
- File upload bug where the dialog would break after the first successful upload
- Fixes sorting for dates
- Fixes sorting for file size

Fixes bug with File Upload

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectTeamTable.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5880
Live Demo:
https://deploy-preview-289--atd-moped-main.netlify.app/moped/projects/176?tab=team
(Nodding to my professor last semester, I never thought I'd ever use tuple operations and tuple sets. )

Bug | Can't add or edit Team members #5880

---

moped-editor/src/views/projects/projectView/ProjectTimeline.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6016
** Front-End Changes Only, Live Demo:
https://deploy-preview-307--atd-moped-main.netlify.app/moped/session/signin

Bug | Duplicate records created when adding phases via keyboard #6016

---

moped-database/metadata/tables.yaml

Cannot explain the regression, but this should take care of the permissions.
** This can be tested in the moped-test environment and local environment,

Fix problems with project permissions (Patch)

---

moped-editor/src/views/projects/projectView/ProjectActivityLog.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6147
Sorry for the extra diff noise, it looks like prettier went to town on this one.
Live Preview:
https://deploy-preview-314--atd-moped-main.netlify.app/moped/projects/176?tab=activity_log

Bug - WSOD on activity log page #6147

---

moped-editor/src/views/projects/newProjectView/NewProjectView.js

This should fix the project personnel issue.
**Front-end change only, testable in Netlify, Moped-test, or locally:
https://sg-fix-personnel--atd-moped-main.netlify.app/moped/session/signin

Re-fix for project personnel

---

moped-editor/src/utils/mapHelpers.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6231
** UI change only, test in Netlify, moped-test or locally.
Live Demo:
https://deploy-preview-326--atd-moped-main.netlify.app/moped/projects/269

[Bug] Map is no longer zooming to full extent in the project Summary tab #6231

---

moped-api/claims.py
moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/views/staff/StaffForm.js
moped-editor/src/views/staff/StaffListViewQueryConf.js
moped-editor/src/views/staff/helpers.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/5799
** This is mostly a UI change only, you can test in Netlify, moped-test and locally.
There are API changes that are meant to make sure the user name stays as lowercase in AWS.
Also, there was an upgrade for the DataGrid component where a column's className can now be customized.
Live Demo:
https://deploy-preview-324--atd-moped-main.netlify.app/moped/staff

Investigate and address User API failures #5799

---

moped-editor/src/layouts/DashboardLayout/DashboardLayout.js
moped-editor/src/layouts/DashboardLayout/NavBar/NavBar.js
moped-editor/src/layouts/DashboardLayout/TopBar.js

Closes [#6190](https://github.com/cityofaustin/atd-data-tech/issues/6190).

Collapse sidebar menu at all viewport sizes

---

moped-editor/src/views/projects/projectView/ProjectView.js

- Fixes https://github.com/cityofaustin/atd-data-tech/issues/5227
- Fully testable in the Netlify deploy preview environment

Adds "All projects" breadcrumb to project view and removes button

---

moped-editor/src/views/projects/newProjectView/DefineProjectForm.js

https://6199-tweak-define-project--atd-moped-main.netlify.app/moped/projects/new
@amenity, Does the layout or padding next to change at all after removing current phase?

Tweak add new project workflow

---

moped-editor/src/auth/rolesBasedRules.js
moped-editor/src/routes.js
moped-editor/src/views/account/AccountView/Profile.js
moped-editor/src/views/dev/DeviasStyleView/ColorsView.js
moped-editor/src/views/dev/DeviasStyleView/DeviasStyleView.js
moped-editor/src/views/dev/DeviasStyleView/TypographyView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6293
I misread the issue and thought it included colors, instead of colors being a future issue. 
Example page at https://6293-style-examples--atd-moped-main.netlify.app/moped/dev/devias

Add Style examples page 

---

moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/routes.js
moped-editor/src/views/projects/projectView/ProjectView.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js

closes https://github.com/cityofaustin/atd-data-tech/issues/6292
https://6292-projects-breadcrumb--atd-moped-main.netlify.app/moped

All projects breadcrumb returns to search results

---

moped-database/migrations/1624913258837_update_table_moped_subcomponents_add_subcomponents/down.sql
moped-database/migrations/1624913258837_update_table_moped_subcomponents_add_subcomponents/up.sql

Closes https://github.com/cityofaustin/atd-data-tech/issues/6526
** Database change only.
After the migration, this is what subcomponents looks like:

Update Moped subcomponents with latest taxonomy #6526

---

moped-editor/.eslintrc.json
moped-editor/package-lock.json
moped-editor/package.json
moped-editor/src/views/projects/newProjectView/DefineProjectForm.js

- Closes https://github.com/cityofaustin/atd-data-tech/issues/5424
- Add color prop to primary
- Change aria label prop from secondary to primary

Change capital funding switch component color from red to blue

---

moped-editor/src/views/projects/projectView/ProjectView.js

- Closes https://github.com/cityofaustin/atd-data-tech/issues/5568
- Replace anchor tag with Link component

Change anchor tag in Project delete modal to Link component

---

moped-editor/src/routes.js
moped-editor/src/views/dev/DeviasStyleView/ColorsView.js
moped-editor/src/views/dev/DeviasStyleView/DeviasStyleView.js
moped-editor/src/views/dev/DeviasStyleView/TypographyView.js

- Closes https://github.com/cityofaustin/atd-data-tech/issues/6737
- Changed page title to Moped Styles
- Change route to `dev/styles`

Update Moped styles page

---

moped-editor/src/layouts/DashboardLayout/DashboardLayout.js
moped-editor/src/theme/index.js
moped-editor/src/views/dev/DeviasStyleView/ColorsView.js
moped-editor/src/views/errors/NotFoundView.js
moped-editor/src/views/projects/projectView/ProjectSummaryMapFallback.js

- Closes https://github.com/cityofaustin/atd-data-tech/issues/6779
- Removes background color dark prop from styles in Not found view, Dashboard, and Fallback summary map

Fix dark background bug

---

moped-editor/src/views/staff/StaffForm.js

- Closes https://github.com/cityofaustin/atd-data-tech/issues/6724
- Added email and tolowercase to email key of yup object shape
**How to Test**
- Visit moped site from netlify preview
- Make sure you add/remove user privileges
- Go to staff page and click on the add staff button
- Fill out form and save

Validate and process email addresses for user registration

---

moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/views/staff/StaffListViewQueryConf.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6674
** UI Change only, see live demo:
https://deploy-preview-380--atd-moped-main.netlify.app/moped/staff
Changes to the staff list:
This is the way it looks like now:

Implement design refinements to "Staff" page #6674

---

moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/components/GridTable/GridTableSearch.js

Attempts to address the WSOD in the Staff list:

[Bug] Staff WSOD

---

moped-editor/src/views/projects/projectView/ProjectTeamTable.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6943
Thank you Sergio for helping walk me through it. 
deployed at https://moped-test.austinmobility.io/moped/projects/new

Prevent null from being sent in team query

---

moped-editor/src/components/GridTable/GridTable.js

Fixes [#7001](https://github.com/cityofaustin/atd-data-tech/issues/7001)

Remove project list and staff list container scrolling

---

moped-editor/src/views/projects/newProjectView/NewProjectView.js

Fixes [#7074](https://github.com/cityofaustin/atd-data-tech/issues/7074).

Show project name in new project workflow header

---

moped-editor/src/views/projects/projectView/ProjectFiles.js
moped-editor/src/views/projects/projectView/ProjectTeamTable.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js

Fixes https://github.com/cityofaustin/atd-data-tech/issues/7072
Test [here](https://deploy-preview-410--atd-moped-main.netlify.app/).

Replaces x icon in tables with trash can icon to delete records

---

moped-editor/src/components/DataTable/DataTable.js
moped-editor/src/components/GridTable/GridTableSearch.js
moped-editor/src/layouts/DashboardLayout/NavBar/SupportMenu.js
moped-editor/src/layouts/DashboardLayout/TopBar.js
moped-editor/src/views/projects/projectView/TabPanel.js

Fixes [#7035](https://github.com/cityofaustin/atd-data-tech/issues/7035)

Fix various React/DOM warnings - #7035

---

moped-toolbox/component_geo_processing/components.sql
moped-toolbox/component_geo_processing/create_components_geojson.py

I created a lil script that converts components into geojson feature collections that are ArcGIS friendly. This is not production ready but was useful for getting the map data for [#6286](https://github.com/cityofaustin/atd-data-tech/issues/6286).

Create script to convert moped components to ArcGIS-friendly geojson

---

.github/workflows/aws-heroku-helper.sh
moped-database/migrations/1631716080737_update_phases_milestones/down.sql
moped-database/migrations/1631716080737_update_phases_milestones/up.sql
moped-editor/src/queries/project.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7134
Updates the phases, subphases and milestones according these spreadsheets:
https://docs.google.com/spreadsheets/d/13EbvdJNoZRCXQOJZJdrUqTUb2-o2puMXhiZN_94_go0/edit#gid=217441231
https://docs.google.com/spreadsheets/d/13EbvdJNoZRCXQOJZJdrUqTUb2-o2puMXhiZN_94_go0/edit#gid=33802623
https://moped-test.austinmobility.io/moped/projects/174?tab=timeline

Update Phases and Milestones terms in the database #7134

---

moped-database/metadata/tables.yaml
moped-database/migrations/1632338636658_alter_table_public_moped_proj_notes_add_column_project_note_type/down.sql
moped-database/migrations/1632338636658_alter_table_public_moped_proj_notes_add_column_project_note_type/up.sql
moped-editor/src/queries/comments.js
moped-editor/src/views/projects/projectView/CommentInputQuill.js
moped-editor/src/views/projects/projectView/ProjectComments.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7124
** Please Test in Moped-Test

Implement Comment types #7124

---

moped-database/metadata/tables.yaml
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/6995
** UI & database changes, test in moped-test.
https://moped-test.austinmobility.io/moped/projects/161?tab=comments
https://user-images.githubusercontent.com/5282430/135158757-761fc95a-bec5-4af1-8df1-fe96f69aeba2.mp4

[Feature] Project "Status update"#6995

---

moped-editor/src/views/projects/projectView/ProjectTeamRoleMultiselect.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7658
UI Changes only

[Bug][Snackoo] Fix staff multi-select #7658

---

moped-database/metadata/tables.yaml
moped-database/migrations/1636086195529_alter_table_public_moped_project_add_column_project_website/down.sql
moped-database/migrations/1636086195529_alter_table_public_moped_project_add_column_project_website/up.sql
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectWebsite.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7069
** Database and UI changes = moped-test please

Implement "Project website" field #7069

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectDescription.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryTable.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7653
Run in moped-test please, it's dependent on other branches.

Design refinements: Project description #7653

---

moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryCurrentPhase.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryTable.js

Design refinements: Current Phase #7654

---

moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectDescription.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryTable.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7657

Design refinements: Status Update #7657

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryCurrentStatus.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7657

Design refinements: Current Status #7657

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectECapris.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectWebsite.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7655

Design refinements: Capital Funding #7655

---

moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7698
Fixes alignment:

Implement additional design refinements to project "Summary" tab #7698

---

moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryCurrentPhase.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryCurrentStatus.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectPartners.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectSponsor.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectWebsite.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7702
https://deploy-preview-463--atd-moped-main.netlify.app/moped/session/signin

Apply sentence case to all field labels on project "Summary" tab #7702

---

moped-editor/public/static/images/moped-flat.svg
moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchInput.js
moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchResults.js
moped-editor/src/views/errors/NotFoundView.js

https://github.com/cityofaustin/atd-data-tech/issues/6604
Updates 404 page with new image, language, search bar and styling.
Fully testable [here](https://deploy-preview-447--atd-moped-main.netlify.app/).
https://user-images.githubusercontent.com/35410637/140419450-2915bbae-4dfc-4d4d-969f-34123f0a7b73.mov

Updates 404 page with new image, language, search bar and styling

---

moped-database/migrations/1637823185562_alter_project_list_view/down.sql
moped-database/migrations/1637823185562_alter_project_list_view/up.sql
moped-editor/src/queries/signals.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js

https://moped-test.austinmobility.io/moped/
WIP
---

Hide cancelled projects #7640

---

moped-database/metadata/tables.yaml
moped-database/migrations/1637828066290_set_fk_public_moped_project_status_id/down.sql
moped-database/migrations/1637828066290_set_fk_public_moped_project_status_id/up.sql
moped-editor/src/queries/project.js
moped-editor/src/views/projects/newProjectView/NewProjectView.js
moped-editor/src/views/projects/projectView/ProjectStatusBadge.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js
moped-editor/src/views/projects/projectView/ProjectView.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js

https://moped-test.austinmobility.io/moped
WIP
---

Add UI triggers for project status and apply design updates to project menu #7639

---

.github/workflows/atd_moped_build_stage.yml

Closes https://github.com/cityofaustin/atd-data-tech/issues/7819
None
We will need to start tracking node/npm versions moving forward, newer versions are introducing features that make GitHub actions fail (until they upgrade or we use something like docker or nvm within GH actions)
---

[Bug] Build process for editor is failing #7819

---

moped-editor/src/queries/workgroups.js
moped-editor/src/views/staff/StaffForm.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/7670
https://deploy-preview-484--atd-moped-main.netlify.app/
- go to staff tab
- select "add staff"
- select workgroup dropdown
"project delivery" was already present in the database
---

Alphabetizes list of workgroup options for Moped users

---

moped-editor/src/views/projects/projectView/ProjectFundingTable.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/7449
https://deploy-preview-474--atd-moped-main.netlify.app/moped/session/signin
- Select a project
- On timeline tab, add or edit a phase, select an existing subphase, save, then edit again and select "-" for subphase and save
- On funding tab, add or edit a source, select an existing program, save, then edit again and select "-" for program and save
---

Provide a way to clear single-select dropdowns

---

.github/workflows/atd_moped_build_stage.yml

Upgrade Node / NPM in GH Actions

---

moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMapFallback.js

This PR intends to close [#7808](https://github.com/cityofaustin/atd-data-tech/issues/7808).
This commits in this PR have been cherry-picked from #470, where you may find the original discussion around these changes.
**URL to test:** https://deploy-preview-473--atd-moped-main.netlify.app/
---

Refactor use of ProjectSummaryMap & Fallback to eliminate console errors

---

moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectStatusBadge.js
moped-editor/src/views/projects/projectView/ProjectView.js
moped-editor/src/views/projects/projectsListView/ProjectsListView.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js

https://github.com/cityofaustin/atd-data-tech/issues/7827
https://7827-project-status-badge--atd-moped-main.netlify.app/moped/projects
Confirm that the badges on the projects page match the badge on the project summary page.
---

Render project status badge on Projects page

---

moped-editor/src/queries/signals.js
moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js

https://github.com/cityofaustin/atd-data-tech/issues/7957
https://7957-signal-refinements--atd-moped-main.netlify.app/moped/dashboard
Change table to 30 rows
Reduce cell padding to 10px
Sort by last updated at
Set whitespace property for table headers to nowrap
Hide deleted projects from table
Change column names to reduce wrapping:
- "Targeted construction start" --> "Construction start"
- "Project completion date" --> "Project completion"
- "Last modified" --> "Modified"
---

Minor refinements to signal table

---

moped-database/migrations/1623358779761_run_sql_migration/up.sql

Adds the migration that exists in production that is not in main. 
I have tested locally and it runs. Will test on Test. Please pull and run locally if you can. 
---

Reconcile migration mismatch between production and main

---

moped-editor/src/views/projects/projectView/ProjectView.js
moped-editor/src/views/staff/EditStaffView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7719
As per the issue's content:
>We need to investigate the routing issues causing WSODs in a couple of places:
>- Any non-existent URL beginning with /moped/staff/edit/
>- Any non-existent URL beginning with /moped/projects/
Projects: You should see a 404 message here:
https://deploy-preview-508--atd-moped-main.netlify.app/moped/projects/123456789
Staff: You should see a 404 message here:
https://deploy-preview-508--atd-moped-main.netlify.app/moped/staff/edit/12345
---

[BUG] 404 page does not render in subdirectory URLs #7719

---

moped-editor/src/views/projects/projectView/ProjectComponents.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7403
This can be tested on Netlify or moped-test.
https://deploy-preview-516--atd-moped-main.netlify.app/moped/projects
Add, edit, remove features from a project.
https://user-images.githubusercontent.com/5282430/148231495-5db23f7b-92ab-44d0-a3d7-bd7dc4e77f4a.mp4
https://user-images.githubusercontent.com/5282430/148231535-98b83f2c-4aa4-4098-a87d-40787aa139e4.mp4
---

Always render current components in "Summary" map #7403

---

moped-editor/src/components/GridTable/GridTable.js
moped-editor/src/views/staff/StaffListView.js
moped-editor/src/views/staff/StaffListViewCustomComponents.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/8081
https://deploy-preview-519--atd-moped-main.netlify.app/moped/staff
https://user-images.githubusercontent.com/5282430/148393697-a3b5d924-388f-47bd-bb3f-21c59553848a.mp4
---

[Enhancement] Allow admin users to access inactive and/or deleted accounts #8081

---

moped-editor/src/views/projects/projectView/ProjectTimeline.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/8006
https://deploy-preview-518--atd-moped-main.netlify.app/moped/projects/374?tab=timeline
https://user-images.githubusercontent.com/5282430/148409638-ca9f2677-3235-4e65-a15f-072e9e50ce99.mp4
---

Convert milestone select input to autocomplete #8006

---

moped-database/migrations/1641337581998_run_sql_migration/down.sql
moped-database/migrations/1641337581998_run_sql_migration/up.sql
moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js

https://github.com/cityofaustin/atd-data-tech/issues/8025
database changes, so test on https://moped-test.austinmobility.io/moped/
On staging/production right now, if you have team members associated with a project as well as more than one 
project partner, you will find that the personnel roles are repeated. 
To test, add more than one team member to a project as well as more than one project partner. Confirm nothing is repeated. 
---

Fix repeat personnel roles bug

---

moped-editor/src/views/projects/projectView/ProjectFundingTable.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectECapris.js
moped-editor/src/views/projects/projectView/ProjectView.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/8079
https://deploy-preview-523--atd-moped-main.netlify.app/moped/projects/345?tab=funding
https://user-images.githubusercontent.com/5282430/149398478-a73d0a51-4dfa-4766-b087-cdb71afeddbf.mp4
https://user-images.githubusercontent.com/5282430/149398512-81ac9caf-351e-4dd5-a011-c82cb1a41f28.mp4
---

Add eCAPRIS field to "Funding" tab and adjust required fields #8079

---

moped-editor/src/views/staff/StaffForm.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/8158
https://deploy-preview-524--atd-moped-main.netlify.app/moped/staff
https://user-images.githubusercontent.com/5282430/149538338-08da5d73-0fe3-41ee-bd75-8982a2e34592.mp4
https://user-images.githubusercontent.com/5282430/149538347-d7822d88-0abb-43ef-ade0-ad6f794c7731.mp4
https://user-images.githubusercontent.com/5282430/149538354-6ee8f511-9141-4e00-975f-4d6bfe77438c.mp4
---

Refine delete/inactivate user account interface #8158

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryContractor.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectDO.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/8175
https://deploy-preview-525--atd-moped-main.netlify.app/moped/projects/377/
https://user-images.githubusercontent.com/5282430/149501102-b5ffc54b-0043-4b29-b9db-7bf937d98d3a.mp4
---

Add fields for "Contractor/contract" and "Project DO #" to the "Summary" tab #8175

---

moped-editor/src/views/projects/projectView/ProjectTeamTable.js

This PR gets rid of that nasty setTimeout pattern once and for all.
Close https://github.com/cityofaustin/atd-data-tech/issues/8178
https://deploy-preview-526--atd-moped-main.netlify.app/moped/projects/345?tab=team
https://user-images.githubusercontent.com/5282430/149504378-b8c12784-18d6-4c77-8690-9edaa5cc80c8.mp4
---

Clean up project team table #8178

---

moped-editor/src/queries/funding.js
moped-editor/src/views/projects/projectView/ProjectFundingTable.js
moped-editor/src/views/projects/signalProjectTable/TaskOrderAutocomplete.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/7930
https://deploy-preview-527--atd-moped-main.netlify.app/moped/dashboard
https://deploy-preview-527--atd-moped-main.netlify.app/moped/projects/377/
https://user-images.githubusercontent.com/5282430/149559974-8a15a46d-501a-4288-a902-fcde699f652f.mp4
https://user-images.githubusercontent.com/5282430/149559981-e3796e2f-ac97-46cb-90da-40bcf414940b.mp4
https://user-images.githubusercontent.com/5282430/149559989-7593869c-6386-4008-a520-68726527ee0b.mp4
---

Add task order multi-select to "Funding" tab #7930

---

moped-editor/src/queries/funding.js
moped-editor/src/queries/signals.js
moped-etl/app/process/logging.py

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8002. 
https://deploy-preview-529--atd-moped-main.netlify.app/moped/projects
* Create a project from a signal asset and assign it a funding source. 
* On the signal dashboard, observe that the new funding source shows for this project.
* Delete this funding source.
* On the signal dashboard, observe that the deleted funding source is no longer shown.
---

8002 Address deleted funding sources on signal dashboard page

---

moped-editor/src/queries/signals.js

https://github.com/cityofaustin/atd-moped/pull/534
To keep main in sync with the release candidate/ production branch.
---

Patch to update filters on signal query

---

moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js

PR to match patch that was merged to release candidate: https://github.com/cityofaustin/atd-moped/pull/538
---

Use different variable for project_sponsor on signal table

---

moped-editor/package.json
moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchInput.js
moped-editor/src/libs/GQLAbstract.js
moped-editor/src/views/projects/projectsListView/ProjectsListView.js
moped-editor/src/views/staff/StaffListView.js

Remove kickstand as external dependency 
---

0.13.2 bugfix take 2

---

moped-database/metadata/tables.yaml

Fixes [#8441](https://github.com/cityofaustin/atd-data-tech/issues/8441)
This is purely a Hasura config change to simplify Knack migration mutations.
**URL to test:** TBD: need to deploy to test env
Make sure project partners still works as expected
1. Go to project summary tab
2. Add a project partner
3. Remove a project parter
---

Add array relation from moped_proj to moped_proj_partners

---

moped-database/metadata/tables.yaml

https://github.com/cityofaustin/atd-data-tech/issues/8435
current_status had been dropped from the permissions table. It is back now.
---
- [x ~Added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#gid=776973707)~

Fix Searching by "Current status" error

---

moped-toolbox/knack_migration/0_download_knack_projects.py
moped-toolbox/knack_migration/1_prepare_projects.py
moped-toolbox/knack_migration/2_insert_projects.py
moped-toolbox/knack_migration/3_update_knack_with_moped_proj.py
moped-toolbox/knack_migration/4_download_files.py
moped-toolbox/knack_migration/5_build_amd_report.py
moped-toolbox/knack_migration/logger.py
moped-toolbox/knack_migration/queries.py
moped-toolbox/knack_migration/requirements.txt
moped-toolbox/knack_migration/secrets.py
moped-toolbox/knack_migration/settings.py
moped-toolbox/knack_migration/utils.py

Resolves [#8067](https://github.com/cityofaustin/atd-data-tech/issues/8067).

Create Knack migration scripts

---

moped-editor/package.json
moped-editor/src/views/projects/signalProjectTable/RenderSignalLink.js

This is the companion production PR to this PR to main https://github.com/cityofaustin/atd-moped/pull/573
https://github.com/cityofaustin/atd-data-tech/issues/8455
https://8455-signal-link--atd-moped-main.netlify.app/moped/dashboard
---

1.0.2 - Patch data tracker signal links

---

moped-editor/package.json
moped-editor/src/queries/signals.js

Companion PR to https://github.com/cityofaustin/atd-moped/pull/582
Fixes bug and updates the version in package.json
---

1.0.3: bugfix, deleted projects appearing on dashboard

---

moped-editor/src/queries/signals.js

https://github.com/cityofaustin/atd-data-tech/issues/8474
https://8474-deleted-projects--atd-moped-main.netlify.app/moped/dashboard
1. Add a project with a signal. Check that it's on the signal dashboard. Then remove the signal, it should no longer be on the dashboard. 
2. Delete a project that was previously visible on the dashboard. Should not be showing up on dashboard. 
---

Fix deleted projects showing up on dashboard

---

moped-editor/src/views/projects/projectView/ProjectTimeline.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/7660
https://deploy-preview-587--atd-moped-main.netlify.app/
add a new milestone without editing toggle (complete field will display "no" instead of blank)
---

sets milestone complete attribute default state to false

---

.github/workflows/aws-heroku-helper.sh
.github/workflows/aws-moped-migrations-helper.sh

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8622. 
Testing is sort of free on this one. Deploying this to the `test` instance and subsequent deployments to `staging` and `production`, if successful, should be considered an acceptable test. 
---

Skip version check in `hasura` CLI in Github actions

---

moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/8137
https://deploy-preview-588--atd-moped-main.netlify.app/
go to dashboard and view projects table, select pagination dropdown
---

Implements design refinements to signal projects table

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/6352
https://deploy-preview-589--atd-moped-main.netlify.app/moped/projects
go to timeline tab, add a project phase with a description. edit an exiting project phase description.
---

implements small refinements to timeline tab

---

moped-editor/src/views/projects/projectView/ProjectFundingTable.js

Incorporates v1.1.1 hotfix into main. See https://github.com/cityofaustin/atd-moped/pull/607
https://deploy-preview-615--atd-moped-main.netlify.app/
---

Update main with v1.1.1 patch

---

moped-database/migrations/1648075868116_insert_moped_types/down.sql
moped-database/migrations/1648075868116_insert_moped_types/up.sql
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectTypes.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/8632
https://moped-test.austinmobility.io/moped/
in test env, go to an existing project and edit project type
---

add new project types

---

moped-editor/src/views/projects/projectView/ProjectComments.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/8720
https://deploy-preview-621--atd-moped-main.netlify.app/moped/projects
go to a project, select comments tab
---

removes project notes button and entry from projectNoteTypes array

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/8759
https://deploy-preview-616--atd-moped-main.netlify.app/
Go to a project and create a new status update
---

Adds attribution and date to status updates

---

moped-editor/src/views/projects/projectView/ProjectTimeline.js

https://github.com/cityofaustin/atd-data-tech/issues/8262
https://8262-blank-phase--atd-moped-main.netlify.app/moped/projects
Try to add a phase to the timelines table without entering any information. It should prevent you from being able to save.
I also fixed some warnings/errors in the console. 
---

Set phase name as required

---

moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js

https://github.com/cityofaustin/atd-data-tech/issues/8869
Netlify [deploy with filters on](https://8869-last-modified--atd-moped-main.netlify.app/moped/projects?filter=eyI5NDVjMTMzMS1kNjFlLTQ4YmMtYjliOC03YTNmY2ZhMDZhMWIiOnsiaWQiOiI5NDVjMTMzMS1kNjFlLTQ4YmMtYjliOC03YTNmY2ZhMDZhMWIiLCJmaWVsZCI6InVwZGF0ZWRfYXQiLCJvcGVyYXRvciI6ImRhdGVfZ3JlYXRlcl90aGFuX2VxdWFsX3RvIiwiYXZhaWxhYmxlT3BlcmF0b3JzIjpbeyJvcGVyYXRvciI6Il9lcSIsImxhYmVsIjoiaXMiLCJkZXNjcmlwdGlvbiI6IlRoZSBkYXRlIGlzIGVxdWFsIHRvLiIsImVudmVsb3BlIjpudWxsLCJ0eXBlIjoiZGF0ZSIsImlkIjoiZGF0ZV9lcXVhbHMifSx7Im9wZXJhdG9yIjoiX2d0IiwibGFiZWwiOiJncmVhdGVyIHRoYW4iLCJkZXNjcmlwdGlvbiI6IlRoZSBkYXRlIGlzIGdyZWF0ZXIgdGhhbi4iLCJlbnZlbG9wZSI6bnVsbCwidHlwZSI6ImRhdGUiLCJpZCI6ImRhdGVfZ3JlYXRlcl90aGFuIn0seyJvcGVyYXRvciI6Il9ndGUiLCJsYWJlbCI6ImdyZWF0ZX …

Include "last modified" in advanced filters

---

moped-editor/src/views/projects/projectView/ProjectFundingTable.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/8721
https://deploy-preview-630--atd-moped-main.netlify.app/
1) create a new funding source setting a status value
2) create a new funding source without setting a status value
---

sets funding_status_id to user selection or tentative if no selection

---

moped-database/migrations/1650035696474_pk-and-sequences/down.sql
moped-database/migrations/1650035696474_pk-and-sequences/up.sql

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8451.
1) Read the SQL changes for sanity
1) Spin up the database
1) Try to insert records (form shown in comments in `up.sql` and observe correct ID assignment
1) Spin up a local copy of the database with `main` checked out
1) Checkout this branch, `8451-database-primary-keys-and-sequences`
1) Apply the `up.sql` line by line to observe behavior
1) Try to insert records (form shown in comments in `up.sql` and observe correct ID assignment
---

Update 5 tables with adjusted primary keys, sequences

---

moped-database/migrations/1652877867946_project-list-view-dedup-signal-assets/down.sql
moped-database/migrations/1652877867946_project-list-view-dedup-signal-assets/up.sql
moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js

https://github.com/cityofaustin/atd-data-tech/issues/9167.
_RC version_
PR to main: 
https://github.com/cityofaustin/atd-moped/pull/651
---

RC patch to fix #9167

---

moped-database/metadata/tables.yaml
moped-database/migrations/1653067649000_alter_table_moped_proj_milestones/down.sql
moped-database/migrations/1653067649000_alter_table_moped_proj_milestones/up.sql
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js

https://github.com/cityofaustin/atd-data-tech/issues/9208
Test locally or on moped-test
1. add new milestones: https://moped-test.austinmobility.io/moped/projects/161?tab=timeline
2. edit existing milestones
3. delete milestones
You should not notice any functionality difference from the user's perspective. 
I also tested by copying the production data from the read replica (thank you to @frankhereford for helping me execute that) and running the migration steps manually. 
---

Create foreign key relationship between milestones tables

---

moped-editor/src/views/dashboard/DashboardView.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/9205
https://deploy-preview-657--atd-moped-main.netlify.app/
see views section on dashboard page
---

Adds views section to dashboard

---

moped-editor/package.json
moped-editor/src/views/dashboard/DashboardView.js

****Please note this uses [this branch](https://github.com/cityofaustin/atd-moped/tree/9205_add_views_section_to_dashboard) as a base to avoid redundancy. Please review [this PR](https://github.com/cityofaustin/atd-moped/pull/657) first.****
https://deploy-preview-663--atd-moped-main.netlify.app/
view greeting on dashboard!
---

Adds welcome header component to dashboard

---

moped-editor/src/queries/signals.js
moped-editor/src/views/projects/newProjectView/NewProjectView.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/9403
https://moped-test.austinmobility.io/moped/projects
add new signals project and open signals project view
---

Fixes wsod on signal projects table

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js

https://github.com/cityofaustin/atd-data-tech/issues/9405
https://cb-fix-construction-date--atd-moped-main.netlify.app/moped/projects
Add a construction phase with a start date to a project, see that it shows up on the projects list. 
---

Patch Fix - include phase name in project phase insert

---

moped-editor/package.json
moped-editor/src/views/dashboard/DashboardView.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/9393
https://deploy-preview-676--atd-moped-main.netlify.app/
go to dashboard and confirm salutation and date are correct
---

Removes moment js dependency

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectActivityLog.js
moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js

https://github.com/cityofaustin/atd-data-tech/issues/9415
Test on moped test to get access to the activity log functionality
Add a new phase to a project. Check Activity Log to see that a) it renders and b) lists the correct phase name.
(if it is activity log information from seed data, you will not see a phase name since those records lack phase_ids)
---

Bug fix - WSOD on Activity Log for moped phases

---

moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectView/ProjectActivityLog.js
moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
moped-editor/src/views/projects/projectView/ProjectTimeline.js

putting the patches from the release candidate into main
https://github.com/cityofaustin/atd-moped/pull/673
https://github.com/cityofaustin/atd-moped/pull/677
https://github.com/cityofaustin/atd-moped/pull/670
---

RC patches - missing phase name and wsod on activity table

---

moped-editor/package-lock.json
moped-editor/src/queries/dashboard.js

https://chia-patch-dashboard--atd-moped-main.netlify.app/moped/dashboard
Check the dashboard on staging -- it is empty of projects
Check the dashboard in the netlify deploy, it has projects. (if still empty, follow some projects to confirm)
Same database, but different queries. 
---

Check for is_deleted in dashboard query

---

moped-editor/src/views/dashboard/DashboardView.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/9394
https://deploy-preview-678--atd-moped-main.netlify.app/
dashboard greeting styling
---

Dashboard design enhancements for consistency

---

moped-editor/src/queries/dashboard.js
moped-editor/src/views/dashboard/DashboardView.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/9661
branched from https://github.com/cityofaustin/atd-moped/tree/9277_dashboard_milestone_progress_column
https://deploy-preview-707--atd-moped-main.netlify.app/
follow or add yourself to a project team
put the project on hold
the "on hold" badge should display under project status on dashboard
---

Shows on hold status badge on dashboard

---

.github/workflows/aws-moped-sqs-helper.sh

https://github.com/cityofaustin/atd-data-tech/issues/9723
We cannot test this until its merged :/
---

Fixes staging activity log deployment

---

moped-etl/prefect/moped_test_create_flow.py

This is @mddilley and I consolidating branches to ease the task of keeping up with main.

Consolidate feature branches around moped-test-deployment development

---

moped-etl/prefect/moped_test_create_flow.py
moped-etl/prefect/tasks/ecs.py

This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/9630. 
This PR has a sibling PR, [Prefect #19](https://github.com/cityofaustin/atd-prefect/pull/19).

ECS Deployment Flows

---

moped-etl/prefect/moped_test_create_flow.py
moped-etl/prefect/tasks/database.py

Sibling to https://github.com/cityofaustin/atd-prefect/pull/24

Populate moped test database with either staging or prod data

---

moped-toolbox/backfill_activity_log/backfill_activity_log.py

https://github.com/cityofaustin/atd-data-tech/issues/9726
This is for posterity. We did not use this script in production due to issues discussed in https://github.com/cityofaustin/atd-data-tech/issues/9773.

Add script to backfill activity log

---

moped-etl/prefect/tasks/api.py

Quick patch to the GraphQL endpoint passed the API deployment

Patch up GraphQL endpoint passed to API deployment

---

moped-database/migrations/1661896731916_insert_moped_components/down.sql
moped-database/migrations/1661896731916_insert_moped_components/up.sql
moped-database/migrations/1661897396206_set_fk_public_moped_proj_components_component_id/down.sql
moped-database/migrations/1661897396206_set_fk_public_moped_proj_components_component_id/up.sql

fixes https://github.com/cityofaustin/atd-data-tech/issues/9312
fixes https://github.com/cityofaustin/atd-data-tech/issues/10106
https://9312_add_rrfb_component--atd-moped-main.netlify.app/
go to moped project -> map -> add new component and add the following components:
signage -> rrfb
intersection -> roundabout
---

Inserts new moped rrfb and roundabout components

---

moped-database/migrations/1663016156653_pdd_new_milestones/down.sql
moped-database/migrations/1663016156653_pdd_new_milestones/up.sql
moped-database/migrations/1663016172738_pdd_update_existing_milestones/down.sql
moped-database/migrations/1663016172738_pdd_update_existing_milestones/up.sql

https://github.com/cityofaustin/atd-data-tech/issues/10070
Local or [Moped test deploy](https://10070-jc-pdd-milestones--atd-moped-main.netlify.app/moped)
Visit `moped/dev/lookups#moped-milestones` and confirm the following changes:
- Add "Construction Bid Published" with phase "Bid/Award/Execution"
- Add "Construction Bid Due" with phase "Bid/Award/Execution"
- Add "Design RFQ Published" with no phase
- Add "Design RFQ Due" with no phase
- Add "Design Contract Execution" with no phase
- Add "Inter-agency Agreement Council Award" with phase "Design"
- Rename "	Preliminary schematic complete" to "Schematic Complete" and change phase to "Prelim Design"
- Rename "Award" to "Design Award" and phase should be blank
- Change "Design Notice-to-Proceed" phase …

Adds and updates milestones for PDD

---

moped-editor/src/components/GridTable/GridTableFiltersCommonOperators.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/9720
https://deploy-preview-784--atd-moped-main.netlify.app/
Go to projects filter, set "status" to "is" "Potential," this should return results (same results as lowercase "potential")
---

Replace case sensitive operator

---

.github/workflows/atd_moped_database.yml

Oops, [we deleted our database CI](https://github.com/cityofaustin/atd-moped/pull/781/files#diff-7b8f8f0b9f093c1dd2b47f26b26ea1508ce1d97f8485ff5a8fc9e1d088e380eb).
I don't believe it will be possible to test this until we merge this PR.

Restore the Moped database migration action

---

.github/workflows/atd_moped_database.yml

Let's hold off until we know the staging database migrations are squared away.

Adds DB migration action from main into v1.8 RC

---

moped-editor/src/utils/timelineTemplates.js
moped-editor/src/views/projects/projectView/MilestoneTemplateModal.js
moped-editor/src/views/projects/projectView/ProjectMilestones.js

https://github.com/cityofaustin/atd-data-tech/issues/10236
Same testing as this: https://github.com/cityofaustin/atd-moped/pull/796, but now you can select PDD as a viable option
https://deploy-preview-797--atd-moped-main.netlify.app/moped/projects
---

Create Project Delivery timeline template 

---

moped-database/metadata/tables.yaml
moped-database/migrations/1664402014381_add_project_tags_to_view/down.sql
moped-database/migrations/1664402014381_add_project_tags_to_view/up.sql
moped-editor/src/components/GridTable/GridTableFilters.js
moped-editor/src/queries/project.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js

https://github.com/cityofaustin/atd-data-tech/issues/10288
This PR adds advanced search for project tags and patches a bug where autocomplete had stopped enabling with an option dropdown when a lookup table was set in the [ProjectsListViewFiltersConf](https://github.com/cityofaustin/atd-moped/blob/5b991e54b41d829b6d66291bc8c9e293eba05ed8/moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js).
I'm confident that the bug patch won't lead to regressions, but please let me know if that is not the case. Also could use feedback on if this patch restores things to the way they were. 🙏 
Also, I'll add the tests that I mentioned in a separate PR since it requires adding a package and some boilerplate that will clutter this diff up.
**URL to test:** …

Add advanced search for project tags

---

moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/10290
https://deploy-preview-821--atd-moped-main.netlify.app/
go to the project list view and check the "project tags" field. add or delete tags from a project to see it update!
---

displays project tags in projects list view

---

moped-editor/package-lock.json
moped-editor/src/components/CustomPopper.js
moped-editor/src/components/LookupSelectComponent.js
moped-editor/src/views/projects/projectView/FundingDeptUnitAutocomplete.js
moped-editor/src/views/projects/projectView/ProjectFundingTable.js
moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js
pull_request_template.md

https://github.com/cityofaustin/atd-data-tech/issues/10418
I also fixed a bug I had written where the tags were not filtering out correctly. 
https://deploy-preview-825--atd-moped-main.netlify.app/moped/projects/1887?tab=funding
On funding tab
Add new funding source
In Source, try "Street Impact Fee" or other text in autocomplete. 
In Program "Signal" is a good thing to search as well
Test editing after submit. 
---

Change Funding Sources selects to autocompletes

---

moped-editor/src/views/projects/projectView/ProjectFundingTable.js

https://github.com/cityofaustin/atd-data-tech/issues/10418
https://deploy-preview-826--atd-moped-main.netlify.app/moped/projects/1815?tab=funding
similiar to https://github.com/cityofaustin/atd-moped/pull/825
testing autocomplete in the funding table, but this time with the fund dropdown
---

Change fund dropdown to autocomplete

---

moped-editor/src/views/projects/projectView/DeleteConfirmationModal.js
moped-editor/src/views/projects/projectView/ProjectComments.js
moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js

This is a dupe of https://github.com/cityofaustin/atd-moped/pull/815 which brings this feature into v1.10.

10292 delete comment confirmation modal

---

moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectDescription.js

https://github.com/cityofaustin/atd-data-tech/issues/10419
WIP
---

Refines the project summary tab UX

---

moped-database/migrations/1666724534571_add new moped_components/down.sql
moped-database/migrations/1666724534571_add new moped_components/up.sql

fixes https://github.com/cityofaustin/atd-data-tech/issues/10539
https://10539_intersection_improvement_component_type--atd-moped-main.netlify.app/moped/
add a component -> select type 'intersection' -> there should be two new subtypes 'improvement' and 'improvement (linear)'
---

Creates "intersection improvement" component types

---

moped-database/migrations/1666819956123_correct_construction_milestones/down.sql
moped-database/migrations/1666819956123_correct_construction_milestones/up.sql
moped-editor/src/queries/tableLookups.js

https://github.com/cityofaustin/atd-data-tech/issues/9843
---

Update the related phase for "cabinet set" milestone

---

moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
moped-editor/src/views/projects/projectView/ProjectComponents/index.js
moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
moped-editor/src/views/projects/projectView/ProjectComponents/mapStyleSettings.js
moped-editor/src/views/projects/projectView/ProjectComponents/mapUtils.js

https://github.com/cityofaustin/atd-data-tech/issues/10407
Changes:
- Updates from conditionally rendering Mapbox sources and layers with state conditionals to conditionally toggling [layer visibility ](https://docs.mapbox.com/mapbox-gl-js/style-spec/layers/#layout-background-visibility)
- https://docs.mapbox.com/mapbox-gl-js/example/toggle-layers/
- Adds `isInteractive` boolean to the layers config so we can generate a list of [interactive layer IDs](https://visgl.github.io/react-map-gl/docs/api-reference/map#interactivelayerids) from it
https://md-10407-interactive-layers--atd-moped-main.netlify.app/ or local
1. Go to a new or existing project's **Map** tab
2. Click **New Component** and select the type called **Access Control - Driveway Closure**
3. …

Manage dynamic interactive layer IDs and layers (#5)

---

moped-etl/prefect/tasks/ecs.py

Bump graphql engine version to 2.16.0

---

moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js

https://github.com/cityofaustin/atd-data-tech/issues/11218
---

Causes new subproject rows to be inserted as the first row of the table

---

moped-database/metadata/tables.yaml
moped-database/migrations/1673463464960_alter_table_public_moped_proj_notes_drop_column_added_by/down.sql
moped-database/migrations/1673463464960_alter_table_public_moped_proj_notes_drop_column_added_by/up.sql
moped-database/seeds/1602292389297_initial_seed_staging.sql
moped-editor/src/queries/comments.js
moped-editor/src/queries/dashboard.js
moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js

- https://github.com/cityofaustin/atd-data-tech/issues/11182
1. Start the Hasura cluster and editor
3. Create, edit, and delete comments through the three places this is possible:
- Project comments tab
- Project summary status update
- Status update modal from the Dashboard page
---

Drops moped_proj_notes.added_by column

---

moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js

https://github.com/cityofaustin/atd-data-tech/issues/11001
@johnclary - ~there are columns that we export that we don't show in the project list view. Think we should tidy those up too? Let me know if you have something specific in mind, and I'll update if needed.~ 🙏  
_Edit: Updated all columns in the export_
Local or https://deploy-preview-963--atd-moped-main.netlify.app/
1. Download the project list view CSV and take a look at the column names
2. Check to see that they match the names of the columns of the table in the app
3. These two columns that are not shown in the table are also updated
> project_description -> Project Description
current_phase_key -> Current Phase Key
---

Make column names in CSV download match column names in project list view

---

moped-database/docker-compose.yml

- https://github.com/cityofaustin/atd-data-tech/issues/11886
- [v2.22.0 release notes](https://github.com/hasura/graphql-engine/releases/tag/v2.22.0)
**URL to test:** Local or [Staging](https://moped.austinmobility.io/moped)
1. Start the Hasura cluster and editor. Kick the tires a bit.
Full testing will be covered via the next Moped release (v1.21).
---

Bump Hasura to v2.22.0

---

moped-editor/src/components/FileUpload/FileUploadDialogSingle.js

https://github.com/cityofaustin/atd-data-tech/issues/11900
This is the quick fix to get it into the next release
I would like to still refactor the components FileUploadDialogSingle.js and FileUploadDialogSimple.js because they are very similar to each other
---

11900 Fix to save files with ampersands

---

moped-database/docker-compose.yml
moped-database/seeds/1602292389297_initial_seed_staging.sql

- https://github.com/cityofaustin/atd-data-tech/issues/12033
1. Spin up the cluster and editor
2. On the "Funding" table, add a new contract record.
---

Fix project contract seeds and bump to Hasura v2.23

---

moped-database/docker-compose.yml
moped-editor/package.json
moped-editor/src/components/FileUpload/FileUpload.js
moped-editor/src/components/FileUpload/FileUploadDialogSimple.js
moped-editor/src/components/FileUpload/FileUploadDialogSingle.js

1.21.1 - patch file upload bug

---

moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeFeatureCollections.js

- https://github.com/cityofaustin/atd-data-tech/issues/12059
**URL to test:** [Netlify preview](https://deploy-preview-1025--atd-moped-main.netlify.app/)
1. Create a bike lane component by selecting street segments.
2. Edit that component by adding additional segments and drawing lines. Confirm that you can save your edits. ✅ 
3. Repeat with a crosswalk (or other point-type component) and drawing points as well.
---

Fixes component feature editing bug

---

moped-auth/cloudfront-cognito-at-edge/package-lock.json

I bumped the `package.json` version in https://github.com/cityofaustin/atd-moped/pull/1036, but I didn't commit the package-lock.json.
This will resolve:
- https://github.com/cityofaustin/atd-moped/security/dependabot/96
- https://github.com/cityofaustin/atd-moped/security/dependabot/88
- https://github.com/cityofaustin/atd-moped/security/dependabot/86
It requires a yolo merge to staging.

Upgrade to cognito-at-edge js v1.4

---

moped-editor/src/views/projects/projectView/ProjectMilestones.js
moped-editor/src/views/projects/projectView/ProjectPhases.js
moped-editor/src/views/projects/projectView/ProjectTeamTable.js

these are the changes from the patch to prod https://github.com/cityofaustin/atd-moped/pull/1037/files
---

Bug Fix -- 1.22.1 patch to prod, added to main

---

moped-editor/src/queries/tableLookups.js
moped-editor/src/views/dev/LookupsView/settings.js

https://github.com/cityofaustin/atd-data-tech/issues/12296
test locally
https://localhost:3000/moped/dev/lookups
see the component tags! 
---

Add component tags to data dictionary

---

moped-database/migrations/1683927220054_run_sql_migration/down.sql
moped-database/migrations/1683927220054_run_sql_migration/up.sql
moped-database/migrations/1684262757917_update-component-tags/down.sql
moped-database/migrations/1684262757917_update-component-tags/up.sql
moped-editor/src/queries/components.js
moped-editor/src/queries/tableLookups.js
moped-editor/src/views/dev/LookupsView/settings.js
moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeComponentData.js

https://github.com/cityofaustin/atd-data-tech/issues/12223
https://deploy-preview-1049--atd-moped-main.netlify.app/moped/projects
edited: Yall i just realized that you have to test this locally, because there are updates to the db
Edit a component's attributes:
Add tags to the component. 
Save the component, come back and add more tags/ delete existing tags. 
---

Add tags multi-select to component form

---

moped-database/migrations/1687456919099_amd-2023-proj-tag/down.sql
moped-database/migrations/1687456919099_amd-2023-proj-tag/up.sql

- https://github.com/cityofaustin/atd-data-tech/issues/12655
1. Start the cluster + editor
2. Go to a project's summary page and add the project tag called `Arterial Management 2023`.
3. Delete the project tag
---

Creates new project tag for Arterial Management

---

moped-editor/package.json
moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js

- https://github.com/cityofaustin/atd-data-tech/issues/12810
- Reviewed here: https://github.com/cityofaustin/atd-moped/pull/1074
Netlify
---

Promote v1.27.1 to production

---

moped-database/migrations/1692241827284_smart_mobility_smo_entity/down.sql
moped-database/migrations/1692241827284_smart_mobility_smo_entity/up.sql
moped-editor/src/queries/project.js

- https://github.com/cityofaustin/atd-data-tech/issues/13267
Visit a project's summary page and observe that `COA ATD Smart Mobility Office` can be selected as a project lead, sponsor, partner. 
---

Adds Smart Mobility as an entity

---

moped-toolbox/component_geo_processing/create_components_geojson.py
moped-toolbox/component_geo_processing/secrets.py
moped-toolbox/component_geo_processing/secrets_template.py
moped-toolbox/component_geo_processing/settings.py

- https://github.com/cityofaustin/atd-data-tech/issues/13424
This script continues to be a helper for giving Andrew data he needs for the Mobility Annual Plan. I would definitely want to refactor this before using it in an ETL. Ultimately I think we'll want to make a DB view that does most of the munging.
1. Start the cluster + editor
2. navigate to this this script: `/atd-moped/moped-toolbox/component_geo_processing`
3. Save `secrets_template.py` as `secrets.py`
4. Using a Python environment with `requests`  you can run the script:
```shell
python create_components_geojson.py -e local
```
5. Inspect the contents of the `/_output` directory. you can copy/paste the geojson into http://geojson.io/ if you like.
---

Update geoprocessing script for latest component schema

---

moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js

- https://github.com/cityofaustin/atd-data-tech/issues/13623
**URL to test:** Local (bc its a branch from a branch)
1. Add a new file by filling in the link field instead of uploading a file
2. In the file table, edit the file link.
3. Confirm that the edit is captured in the activity log
---

Handles file links in activity log

---

moped-database/metadata/tables.yaml
moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
moped-editor/src/utils/activityLogHelpers.js
moped-editor/src/views/projects/projectView/ProjectActivityLog.js

- https://github.com/cityofaustin/atd-data-tech/issues/13820
1. Delete a component from a project.
2. Add a component to a project.
3. Use the new feature to move the component to another project
4. Check the activity log for the project your component moved from, and verify the delete, add and "moved to" activities are correct.
5.  Check the activity log of the project your component moved to and verify the component "moved from" event looks correct.
---

Adds activity log event for moving component to another project

---

moped-editor/package.json

Brings missing package.json commit into `main`. I will bump main again after merging.
See https://github.com/cityofaustin/atd-moped/pull/1132

Companion PR for v1.32.1

---

moped-editor/package-lock.json
moped-editor/package.json
moped-editor/src/components/GridTable/GridTableSearch.js
moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js

Papa, can you hear me?
https://github.com/cityofaustin/atd-moped/pull/1140
https://deploy-preview-1141--atd-moped-main.netlify.app/moped/projects
Steps to test:
Click download button next to search input. Check that the csv export makes sense, a good way to quickly eyeball this is by scrolling horizontally to the end and seeing that there aren't extra columns with empty headers. In prod right now, commas that are in the status update column are being interpreted as delimiters and inserting extra columns.
Question
the file that is downloaded is named project_list_view2023-09-27blahblahtodaystime.csv Do you think we should prepend the word moped to the file name?
---

Use package to process csvs

---

moped-database/metadata/tables.yaml
moped-database/migrations/1696268106764_alter_table_public_moped_phases_add_column_phase_name_simple/down.sql
moped-database/migrations/1696268106764_alter_table_public_moped_phases_add_column_phase_name_simple/up.sql
moped-database/migrations/1696270091202_update_current_phase_view/down.sql
moped-database/migrations/1696270091202_update_current_phase_view/up.sql
moped-database/migrations/1696553602101_add_phase_simple_project_list_view/down.sql
moped-database/migrations/1696553602101_add_phase_simple_project_list_view/up.sql
moped-database/views/current_phase_view.sql
moped-database/views/project_list_view.sql

https://github.com/cityofaustin/atd-data-tech/issues/14017
gotta test local
Spin up the branch and use your database client to check the moped_phases table, see the new column
*note* 
The down migration is out of step with my other branch (the project list view definition), I will need to update this branch if and when that one is approved and merged. 
---

[Enhancement] Add phase_name_simple column to the moped_phases table and current_phase_view

---

moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js

- https://github.com/cityofaustin/atd-data-tech/issues/14240
**URL to test:** [Netlify preview](https://deploy-preview-1157--atd-moped-main.netlify.app/)
1. Go to the Funding tab and create a work activity by filling in all fields
2. It should work normally
---

Update work activity column order

---

moped-editor/src/components/FileUpload/FileUploadDialogSimple.js
moped-editor/src/components/FileUpload/FileUploadDialogSingle.js
moped-editor/src/views/dashboard/DashboardStatusModal.js
moped-editor/src/views/dashboard/DashboardTimelineModal.js
moped-editor/src/views/dashboard/DashboardView.js
moped-editor/src/views/projects/projectView/MilestoneTemplateModal.js
moped-editor/src/views/projects/projectView/PhaseTemplateModal.js
moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
moped-editor/src/views/projects/projectView/ProjectComponents/DeleteComponentModal.js
moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
moped-editor/src/views/projects/projectView/ProjectComponents/MoveProjectComponentModal.js
moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
moped-editor/src/views/projects/projectView/ProjectView.js
moped-editor/src/views/projects/projectView/SubprojectFundingModal.js
moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useCsvExport.js
moped-editor/src/views/staff/components/StaffFormConfirmModal.js
moped-editor/src/views/staff/components/StaffFormErrorModal.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/14221
https://deploy-preview-1163--atd-moped-main.netlify.app/moped/ 
1. Not a whole lot to test? To see an example of the change compare the status update modal title here https://moped.austinmobility.io/moped/dashboard vs now with my changes, and test the same for the milestones modal etc.
---

Unify dialog title styles

---

moped-etl/arcgis/README.md

Get me that Moped contribution!
---

ETL Typo and Clarifying AGOL in README

---

moped-database/migrations/1699553498334_increase_agol_point_radius/down.sql
moped-database/migrations/1699553498334_increase_agol_point_radius/up.sql
moped-etl/arcgis/utils.py

- https://github.com/cityofaustin/atd-data-tech/issues/14612
You can follow the [readme](https://github.com/cityofaustin/atd-moped/tree/main/moped-etl/arcgis) to run this ETL. it is best to use your local env after downloading a snapshot of production.
The ETL should work, while occasionally logging failures + retries.
---

Mitigate AGOL ETL 404 errors

---

moped-database/migrations/1699899884388_atsd_component_tags/down.sql
moped-database/migrations/1699899884388_atsd_component_tags/up.sql

- https://github.com/cityofaustin/atd-data-tech/issues/14567
1. Start Moped and confirm these tags are available via the component form
2. Checkout the down migration `hasura migrate apply ---down 1`
---

Adds additional component tags for ATSD

---

moped-database/migrations/1703023666940_insert_into_public_moped_subphases/down.sql
moped-database/migrations/1703023666940_insert_into_public_moped_subphases/up.sql

Closes https://github.com/cityofaustin/atd-data-tech/issues/14942
Local
1. Start ur local moped DB, apply the migrations
2. Test adding the new subphases to a project
---

Subphase additions for Smart Mobility Office

---

moped-editor/src/auth/useAuthentication.js

- https://github.com/cityofaustin/atd-data-tech/issues/14951
I am curious to see what this auth payload looks like with SSO, which is only possible on staging or prod (or by figuring out how to get  SSO working locally). 
---

Add a debugger to auth for fun and profit

---

moped-database/metadata/tables.yaml
moped-database/migrations/1706217806294_update_work_activity_audit_field_trigger/down.sql
moped-database/migrations/1706217806294_update_work_activity_audit_field_trigger/up.sql

- https://github.com/cityofaustin/atd-data-tech/issues/15422
1. Create, edit, and delete work activities (on the **Funding** tab) and components (on the **Map** tab)
2. As you do this, make sure the audit fields are updating correctly on the record itself and the related `moped_project` record.
---

Replace REST connector events with DB triggers for work activities and components

---

moped-editor/src/views/projects/projectView/SubprojectFundingModal.js

- https://github.com/cityofaustin/atd-data-tech/issues/15530
**URL to test:**  [Netlify](https://deploy-preview-1264--atd-moped-main.netlify.app/)
1. On the summary tab, set the project's eCapris Subproject ID to `7333.001`
2. On the funding tab, use **Add Funding Source** menu and select **From eCapris** to open the fund picker dialog. Select a funding source and click **Add Funding Source** to save your changes.
Compare this behavior on staging to see the bug.
---

Fixes eCapris funding modal

---

moped-editor/package.json
moped-editor/src/queries/dashboard.js

companion PR to https://github.com/cityofaustin/atd-moped/pull/1294

patch dashboard, 2.6.1

---

moped-database/migrations/1712796816384_add_new_entities/down.sql
moped-database/migrations/1712796816384_add_new_entities/up.sql

https://github.com/cityofaustin/atd-data-tech/issues/16673
run locally
You can see the two new entities in the Project Lead or Project Sponsor selections on the summary page. 
---

Add two new entities

---

moped-editor/package.json
moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js

bug found in testing
https://deploy-preview-1329--atd-moped-main.netlify.app/moped/session/signin
Add a subproject to a project. Verify that it saves correctly. 
---

Update the subprojects payload to get the project id

---

moped-editor/src/layouts/DashboardLayout/NavBar/DropdownMenu.js

Closes https://github.com/cityofaustin/atd-data-tech/issues/16984
https://deploy-preview-1331--atd-moped-main.netlify.app/moped/projects
1. Check out the new User guides link, make sure it takes you to the Getting started page in our gitbook.
---

Update "User Guide" link in dropdown navigation menu

---

moped-database/hasura-cluster

_none_
Local testing:
* can you `./hasura-cluster setenv local`?
* can you `./hasura-cluster replicate`?
* any other usage of `hasura-cluster` should still work
---

Fix positional handling in orchestration script

---

moped-editor/package.json

bump version number

---

moped-editor/package-lock.json
moped-editor/package.json
moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js

https://github.com/cityofaustin/atd-data-tech/issues/16931
The error message that was appearing was due to something in an apollo warning: https://github.com/apollographql/apollo-client/issues/11544
https://deploy-preview-1349--atd-moped-main.netlify.app/moped/projects/1862?tab=map
Move one of the components to another project. 
Navigate to that project
use the back button to return to original project. 
No Crash!
---

Upgrade apollo client to fix app error

---

moped-editor/src/views/projects/projectView/ProjectFundingTable.js

closes https://github.com/cityofaustin/atd-data-tech/issues/17596
https://deploy-preview-1356--atd-moped-main.netlify.app/moped/projects
Go to the funding tab of a project and select Add a new funding source
In the row, choose a Source and then enter 100 in the Amount field but then delete the amount so it is blank. 
see that it saves correctly.
---

[Bug] Adding and then removing a funding amount causes work to be lost

---

moped-database/README.md

Update docs about `hasura-cluster replicate -j`

---

moped-editor/package-lock.json
moped-editor/src/components/GridTable/Filters.js
moped-editor/src/components/GridTable/FiltersChips.js
moped-editor/src/components/GridTable/Search.js
moped-editor/src/components/GridTable/SearchBar.js

https://github.com/cityofaustin/atd-data-tech/issues/17849
I made another branch to handle https://github.com/cityofaustin/atd-data-tech/issues/18232, and thought it would be easier to include in this branch.
https://deploy-preview-1384--atd-moped-main.netlify.app/moped/projects
Add at least one advanced search filter. Apply filters. Test removing the filters, confirm that the records refetch and the url updates accordingly
Add two filters, but this time match ANY filters. Test removing one of the filters. See the results update. 
---

Delete an advanced search filter by clicking on chip

---

moped-editor/package-lock.json
moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js

Hey @mddilley, thank you for your patience on this—the PR is ready for issue #[18324](https://github.com/cityofaustin/atd-data-tech/issues/18324#event-13635944813) I tested it on my local setup, so I think everything is fine, but this being my first time writing any React code, there might be something wrong (hopefully not though). 
Closes https://github.com/cityofaustin/atd-data-tech/issues/18324
https://deploy-preview-1390--atd-moped-main.netlify.app/
1. Delete a work activity row and see the updated delete confirmation modal matches the one in the funding table
---

Added DeleteConfirmationModal to the work activity table

---

moped-database/migrations/1723496266686_add_bike_share_station_comp/down.sql
moped-database/migrations/1723496266686_add_bike_share_station_comp/up.sql

https://github.com/cityofaustin/atd-data-tech/issues/18589
This PR adds a new component type.
Local
1. Start up the local stack
2. Add the new **Bike Share Station** component to a project and notice that the point icon shows next to it in the **Component Type** dropdown
3. Make sure that the work types available in the component form are: **New, Replacement, and Modification**
4. Make sure the **Subcomponents** dropdown is not shown in the component form since this component type has none
5. Make sure that you can select and draw points on the map when creating and editing
6. Test the down migration
---
~- [ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4axNZXLE/edit#) if …

Add Bike Share Station component

---

moped-etl/arcgis/README.md

https://github.com/cityofaustin/atd-data-tech/issues/18672
Take a look at the updated README [here](https://github.com/cityofaustin/atd-moped/tree/update-readme/moped-etl/arcgis), the diff [here](https://github.com/cityofaustin/atd-moped/pull/1413/files), and see if you like the changes. Everyone needs an editor, so please don't hesitate to ask for anything you think could be improved. 
Thanks!
---

Update README for AGOL component publishing script

---

moped-editor/package.json
moped-etl/arcgis/components_to_agol.py
moped-etl/arcgis/requirements.txt
moped-etl/arcgis/utils.py

Patching the same changes in https://github.com/cityofaustin/atd-moped/pull/1428 in production.

Patch Moped AGOL ETL to handle invalid HTML (into `production`) 

---

moped-editor/package.json
moped-editor/src/views/projects/projectView/NoteInput.js
moped-editor/src/views/projects/projectView/ProjectNotes.js

Moving changes Patch 2.21.1 (see https://github.com/cityofaustin/atd-moped/pull/1459) into `main` branch
n/a
n/a
---

Patch 2.21.1 into main

---

moped-database/migrations/1730931541882_add_active_work_activity_status/down.sql
moped-database/migrations/1730931541882_add_active_work_activity_status/up.sql

Closes https://github.com/cityofaustin/atd-data-tech/issues/19508
Local
1. Start up the local start and test the up and down migrations
2. Go to the **Work activities** table in a project's **Funding** tab and add a work activity
3. Update the status to **Active** and save
---

Add Active work activity status

---

moped-editor/src/components/GridTable/Search.js

Remove click listener

---

moped-database/docker-compose.yml

This PR hopes to close https://github.com/cityofaustin/atd-data-tech/issues/19916. 
```
./hasura-cluster replicate
```
If this works, I think we're back in business. Thanks!
---

Bump local PG and PostGIS versions to 16 & 3.5 respectively 

---

moped-database/migrations/1734112355149_add_ss4a_proj_tags/down.sql
moped-database/migrations/1734112355149_add_ss4a_proj_tags/up.sql
moped-editor/package.json

Moving the patched changes from https://github.com/cityofaustin/atd-moped/pull/1508 into `main`
Local
1. Same as https://github.com/cityofaustin/atd-moped/pull/1508
---

Add new project tags to help track SS4A grant funding (Patch into main)

---

moped-editor/src/views/projects/projectView/ProjectTeam/ProjectTeamTable.js

https://github.com/cityofaustin/atd-data-tech/issues/19513
https://deploy-preview-1524--atd-moped-main.netlify.app/moped/projects/1939?tab=team
---

Update info link in Team table to point to Roles part of Data dictionary

---

moped-editor/package-lock.json
moped-editor/src/views/projects/projectsListView/helpers.js

fixes https://github.com/cityofaustin/atd-data-tech/issues/20494
https://deploy-preview-1542--atd-moped-main.netlify.app/
- go to the project list view and select all columns for display
- look through the columns that have lists and confirm that each entry in the list has a comma at the end, aside from the last entry, and confirm that each new entry starts on its own line
---

20494 add commas to concatenated lists project list view

---

.github/workflows/atd_moped_database.yml
.github/workflows/atd_moped_db_docs.yml

jobs were automatically cancelled: https://github.com/cityofaustin/atd-moped/actions
https://github.com/actions/runner-images/issues/11101
---

Update ubuntu for db docs and db migrations

---

moped-database/docker-compose.yml
moped-database/env_template

Fix a typo in an image name

---

moped-editor/package-lock.json
moped-editor/package.json

local
- run npm install
- note that `package-lock.json` no longer includes `@material-table/core`
---

remove material-table

---

moped-editor/src/components/GridTable/FiltersChips.js

This PR hopes to close https://github.com/cityofaustin/atd-data-tech/issues/22722
https://deploy-preview-1611--atd-moped-main.netlify.app/
* Go to the project listing and start piling on advanced searches. You'll need 5 or 6ish.
* Did they wrap around to a second line? If no, add some more until you have a few overflowed onto a second line.
* Resize the window and slowly remove them one by one and keep resizing.
* Do you like how this flows?
* Do you see any other regressions?
---

Fix chip line-wrap and alignment
