- moped-database/metadata/tables.yaml
- moped-database/migrations/1602803091511_rename_table_public_moped_coa_staff/down.sql
- moped-database/migrations/1602803091511_rename_table_public_moped_coa_staff/up.sql
- moped-database/migrations/1602822189445_alter_table_public_moped_users_alter_column_staff_id/down.sql
- moped-database/migrations/1602822189445_alter_table_public_moped_users_alter_column_staff_id/up.sql
- moped-database/migrations/1602822304841_alter_table_public_moped_users_rename_keys/down.sql
- moped-database/migrations/1602822304841_alter_table_public_moped_users_rename_keys/up.sql
- moped-database/migrations/1602823000310_alter_table_public_moped_users_add_column_is_coa_staff/down.sql
- moped-database/migrations/1602823000310_alter_table_public_moped_users_add_column_is_coa_staff/up.sql
- moped-database/migrations/1602823097162_alter_table_public_moped_users_alter_column_cognito_user_id/down.sql
- moped-database/migrations/1602823097162_alter_table_public_moped_users_alter_column_cognito_user_id/up.sql
- moped-database/migrations/1602823426327_alter_table_public_moped_users_add_column_status_id/down.sql
- moped-database/migrations/1602823426327_alter_table_public_moped_users_add_column_status_id/up.sql
- moped-database/seeds/1602292389297_initial_seed.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/4182
```
$ ./hasura-cluster start
$ hasura console 
```
> Moped Database: Rename staff table #4182

- moped-api/claims.py
- moped-api/users/helpers.py
- moped-api/users/users.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/4422
Keeps the functionality of the API the same, but it switches the claims to use email identifiers as opposed to Cognito UUIDs, that way we can have two or more cognito accounts (Cognito and AzureAD) both pointing to the same record in DynamoDB where we get our claims.
> Moped | Single Sign On | Refactor Claims Structure in DynamoDB #4422

- moped-api/claims.py
- moped-api/users/users.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/4455
This PR adds the cognito_uuid column in the users table in DynamoDB, it lives right along with the claims and the user email. We need the cognito_uuid to be provided when searching with an email, as opposed to browsing through the entire Cognito list of users.
The Lambda that generates tokens for AzureAD needs that Cognito UUID, and it passes it to Hasura. Normal cognito accounts are not affected at all.
> Moped | Single Sign On | Make API Populate Cognito UUID in DynamoDB #4455

- moped-api/tests/test_users.py
This PR updates the User API test coverage to work with the latest improvements and also adds a test for the new password update route. I also fixed the order of nested `@patch` decorators in the test methods to pass in arguments in the right order. https://docs.python.org/3/library/unittest.mock.html#quick-guide
> API | Add update password route test and update existing tests

- moped-api/users/users.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/4583
This PR adds CORS setup to the users blueprint in the Flask app. CORS was already set up app-wide by Sergio 🙏 but it seems that blueprints require their own initialization.
> Moped API | Handle CORS in the MOPED User Management API

- moped-api/users/users.py
This PR removes some extra config for the users blueprint so we can update the Moped API.
> Remove CORS config in Users blueprint

- moped-editor/src/views/account/AccountView/ProfileDetails.js
- moped-editor/src/views/staff/EditStaffView.js
- moped-editor/src/views/staff/StaffForm.js
- moped-editor/src/views/staff/StaffListView.js
- moped-editor/src/views/staff/helpers.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4494
This PR updates the user add/edit forms to display errors return from the user API. I also fixed a bug that prevented these forms from submitting successfully in the current staging/production apps. Open to any feedback on whether we should make the API errors human-readable on the front-end or not. I definitely like the way the API returns the regex in the errors the way it does currently.
> Editor | Use error responses from User Management API for Add User form feedback

- moped-api/users/helpers.py
- moped-api/users/users.py
- moped-api/users/validation.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/4722
In the Flask API, the data validation schema being used for create and edit user routes is the same. The password field is not always present in the edit user payload coming from the UI. When it is not present, the request fails and returns an error response with validation failure details.
- Need to handle validation in the case when a user data is updated but not their password
- Revise validation for status_id (value is either 0 or 1)
> Handle API data validation for Edit User route #4722

- moped-api/users/validation.py
This PR updates the regex for `workgroup` validation in the API to allow spaces so we can use the full workgroup names in the database.
> Allow spaces in workgroup name

- moped-editor/src/views/projects/DefineProjectForm.js
- moped-editor/src/views/projects/ProjectSummary.js
- moped-editor/src/views/projects/ProjectSummaryDetails.js
- moped-editor/src/views/projects/ProjectsListView.js
- moped-editor/src/views/projects/ProjectsTable.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4745
This pull request updates the labeling for "Capital Funding" fields. It does not change the database schema or table attributes. If that change is necessary in the DB, I can work on those migrations as a follow-up task.
In the process of adding the Capital Funding field to the Project Summary page, I encountered a bug where a record that had Capital Funding set as `false` was being displayed as "No data". I changed the ternary logic in a way that was quick for me in the moment but allows for some expanded type checking based on field in the future.
> Capitally Funded  ➡️ Capital Funding

- moped-database/migrations/1609960117759_alter_table_public_moped_users_alter_column_first_name/down.sql
- moped-database/migrations/1609960117759_alter_table_public_moped_users_alter_column_first_name/up.sql
- moped-database/migrations/1609960123867_alter_table_public_moped_users_alter_column_last_name/down.sql
- moped-database/migrations/1609960123867_alter_table_public_moped_users_alter_column_last_name/up.sql
I noticed the First Name and Last Name fields in the database are of type Name, which was unknown to me, not to mention it lacks important string comparison operators we need. As it turns out "the name type exists only for the storage of identifiers in the internal system catalogs and **_is not intended for use by the general user_**".
https://www.postgresql.org/docs/current/datatype-character.html
This branch was created only for the migration, changes were cherry-picked from commit id: `3498946e118c995c8f82ff0ce19fe4e2ca5b9447`
> Changes First Name and Last Name field type from Name to Text

- moped-editor/src/theme/index.js
- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4821
Closes https://github.com/cityofaustin/atd-data-tech/issues/4715
This PR updates the New Project map geocoder with a bounding box to keep search results within the Austin area. It also restores the polygon outlines in the map to allow users to see selectable polygons.
Updated technical docs for geocoder: https://app.gitbook.com/@atd-dts/s/moped-technical-docs/infrastructure/user-interface/maps
> Project Extent | Restrict geocoder and restore unselected polygon outlines

- moped-editor/src/layouts/DashboardLayout/NavBar/NavBar.js
- moped-editor/src/layouts/DashboardLayout/TopBar.js
- moped-editor/src/routes.js
- moped-editor/src/views/auth/Logout.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4758
This PR updates the logout button icon and adds a logout link to the sidebar for logging out in mobile viewports.
> User Management | Replace "Login" in side drawer with "Log out"

- moped-editor/package-lock.json
- moped-editor/src/layouts/DashboardLayout/NavBar/NavBar.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/4810
Removes "Settings" and "Register" options from user nav bar.
> removed unnecessary account management nav items

- moped-editor/package-lock.json
- moped-editor/package.json
- moped-editor/src/components/GridTable/GridTableExport.js
I had written something like this before, so I decided to do this manually for the time being and removed the "react-csv" library.
Tested to work in Firefox and Chrome:
https://deploy-preview-191--atd-moped-main.netlify.app/moped/projects
Initially I attempted to use another component within the react-csv library called CSVDownload, it' used as follows`<CSVDownload data={csvData} target="_blank" />;` This however presented a problem because it uses experimental javascript, which requires additional babel libraries and additional configuration settings I did not have the time to play with.
Alternatively, we could have hidden the CSVLink component, but that also required hiding the component with styles and advanced DOM logic and event emulation. This is still a possibility if this …
> Changes to CSV Export

- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
- moped-editor/src/views/projects/projectView/ProjectSummaryDetailsMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4892
This PR updates the vector tile layer used to define the project extent with the [CTN layer](https://tiles.arcgis.com/tiles/0L95CJ0VTaxqcmED/arcgis/rest/services/CTN_Project_Extent_Vector_Tiles/VectorTileServer). I also updated the way styles are defined with a map config object to make switching out or adding layers more straightforward in the future. I also consolidated some common logic between the `NewProjectMap` and `ProjectSummaryDetailsMap` components into a custom hook called `useHoverLayer`.
Found out about the [`get` syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) which I used to expose `this` in the map layer configs so that I could introspect the object outside of the …
> Project Extent | Implement extent definition using CTN segments

- moped-database/metadata/tables.yaml
Creates access permissions for the activity log for all users:
> Moped Database | Permissions for Activity Log

- moped-editor/package-lock.json
- moped-editor/package.json
- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
- moped-editor/src/views/projects/projectView/ProjectSummaryMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4819
This PR adds a custom hook that handles fit the project summary map to a bbox created from its existing feature collection. 
@amenity I think that this feature would be great for the edit map too, but, with the current code, it will zoom to the current features each time a new line is selected. I could refactor to add the option to only zoom on initial load but could use some feedback before investing time on that route.
> Project Extent | Zoom to project extent in Project Summary view

- moped-data-events/activity_log/MopedEvent.py
- moped-database/metadata/tables.yaml
- moped-database/migrations/1612468574956_alter_table_public_moped_activity_log_add_column_operation_type/down.sql
- moped-database/migrations/1612468574956_alter_table_public_moped_activity_log_add_column_operation_type/up.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/5205
Closes https://github.com/cityofaustin/atd-data-tech/issues/5206
This PR basically creates a new column in the activity_log table, allows us to quickly retrieve the operation type: INSERT, UPDATE, DELETE. It will be a nullable varchar(8) and it will be indexed (since we are not expecting more than those 3 entries)
Also, it will be null by default, this field will be populated by the Lambda in SQS as it processes new events from Hasura
> Moped Database | Add column to easily retrieve the operation type #5205

- .prettierignore
- moped-database/.prettierignore
This PR adds a `.prettierignore` file to the DB subfolder to prevent auto-formatting that creates conflicts with changes that Hasura generates.
I tested in `/moped-database/metadata/tables.yaml` with my VSCode setup and was able to verify that format-on-save did not create any changes after this update, but this could use some testing on other machines.
> Add .prettierignore to database subfolder

- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
Preview:
https://deploy-preview-214--atd-moped-main.netlify.app/
The problem:
The fix:
To test, run locally with `$ npm run start:staging`
> Fixes the activity log label for project extend and geojson

- moped-database/metadata/tables.yaml
- moped-database/migrations/1613065498057_alter_table_public_moped_proj_personnel_drop_column_join_date/down.sql
- moped-database/migrations/1613065498057_alter_table_public_moped_proj_personnel_drop_column_join_date/up.sql
- moped-database/migrations/1613065535586_alter_table_public_moped_proj_personnel_drop_column_allocation/down.sql
- moped-database/migrations/1613065535586_alter_table_public_moped_proj_personnel_drop_column_allocation/up.sql
- moped-database/migrations/1613065579652_alter_table_public_moped_proj_personnel_drop_column_role_order/down.sql
- moped-database/migrations/1613065579652_alter_table_public_moped_proj_personnel_drop_column_role_order/up.sql
- moped-database/migrations/1613065672692_alter_table_public_moped_proj_personnel_drop_column_project_personnel_user_id/down.sql
- moped-database/migrations/1613065672692_alter_table_public_moped_proj_personnel_drop_column_project_personnel_user_id/up.sql
- moped-database/migrations/1613066369582_alter_table_public_moped_proj_personnel_drop_column_status/down.sql
- moped-database/migrations/1613066369582_alter_table_public_moped_proj_personnel_drop_column_status/up.sql
- moped-database/migrations/1613066457765_alter_table_public_moped_proj_personnel_add_column_status_id/down.sql
- moped-database/migrations/1613066457765_alter_table_public_moped_proj_personnel_add_column_status_id/up.sql
- moped-database/seeds/1602292389297_initial_seed.sql
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
Closes part of https://github.com/cityofaustin/atd-data-tech/issues/4913
This PR adds the ability to soft delete personnel from a project in the Project Summary Team tab. The table in this tab is filtered to `status_id` of 1. Personnel are "removed" from a project by switching that field to 0. There are also some DB changes summarized below. Replacing the existing table in the New Project workflow is the next PR.
This is also includes a few UI improvements from https://github.com/cityofaustin/atd-data-tech/issues/4834 (X icon instead of trash can icon to remove personnel, notes edit field is now standard MUI style instead of outlined, and increased notes character count to 125).
**Removed**
- `join_date` (captured in `date_added`)
- `allocation` (no longer in scope)
- `role_order` (stored …
> Project Staffing | Delete project team

- moped-editor/src/auth/user.js
- moped-editor/src/components/ApolloErrorHandler.js
These are two small changes:
- Removes unused functions
- Allows more time (5 seconds) for AWS Amplify to refresh token
> JWT Token: Clean-up

- moped-api/users/helpers.py
- moped-api/users/queries.py
Updates to ETL for https://github.com/cityofaustin/atd-data-tech/issues/4994
This PR updates the `generate_user_profile` method to include user roles. This method prepares the data dictionary for DB insert/update via GraphQL mutation.
Note: Some of the changes are just from Black autoformatting.
> User Management | Update ETL to set user roles in create and update routes

- moped-api/app.py
- moped-api/files/files.py
- moped-api/files/helpers.py
- moped-api/tests/test_files_helpers.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/5298
Basically, this branch extends the moped API to allow for uploads and downloads from S3. This allows us to use a react component to upload files directly from the UI into S3.
- Route `/files/download/<file-path>`:  This route will attempt to find the file in the pre-configured bucket name, and if it is found it will return a signed url that makes the file temporarily public (up to 60 seconds).
- Route `/files/request-signature?file=<file-path>`: This route will attempt to request permission to upload a file to s3. If the request is successful, the user is allowed to upload a file to that specific file path only.
This implements the file upload API, unfortunately this cannot be tested without Postman and AWS Creds, but here …
> Moped API | File Uploads to S3

- moped-editor/src/views/projects/projectView/ProjectNameEditable.js
- moped-editor/src/views/projects/projectView/ProjectView.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5378
Live Demo:
https://deploy-preview-233--atd-moped-main.netlify.app/moped/session/signin
What to expect:
- Mouse hover shows edit icon
- User can accept or cancel the operation
- The user can use the mouse to save, or hit the Enter button in the keyboard.
> Make "Project name" editable on Project summary page #5378

- moped-editor/src/queries/project.js
- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
- moped-editor/src/views/projects/newProjectView/ProjectSaveButton.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5376
This PR makes the following updates: 
1. Require at least one line selected (used this MUI pattern https://material-ui.com/components/steppers/#non-linear-error-step)
2. Sentence case in "Map project"
3. Remove "Polygon ID" hover
4. Set map extent to match to project extent when edit panel opens
> Project Extent | Implement refinements to "Map project" step in new project workflow and "Project summary" page

- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/5452
- Adds form validation so a user can't submit a new team member without a username or role
- Disables default MaterialTable enter key behavior so hitting enter on a single field doesn't submit the whole form (this had to be done because MaterialTable's form validation is overridden when a user hits enter)
There's still a minor UX bump in that without being able to submit a form with the enter key, the user has to click the "save" button. Still better than a nasty error! Solution would be to reenable default enter key behavior when user_id and role_id are populated. Haven't had a chance to figure that out yet but wanted to get this submitted in time for the release! Happy to take a crack at it if there's more time.
> add form validation and disable default enter key behavior

- moped-editor/src/queries/project.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogDialog.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5285
This PR updates the `PROJECT_ACTIVITY_LOG_DETAILS` query and adds a helper to the`ProjectActivityLogDialog` component to use lookup tables to translate values in the project activity log details view.
Example with some team member and team role changes: https://deploy-preview-242--atd-moped-main.netlify.app/moped/projects/183?tab=activity_log
> Project Activity Feed | Improve fields displayed in activity log details from personnel table

- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5544
Live Demo:
https://5544-sg-fileuploads-activitylog--atd-moped-main.netlify.app/moped/projects/164?tab=activity_log
Look! The file uploads are showing nicely:
> [Bug] File uploads do not show in the activity log #5544

- moped-database/migrations/1617216384819_alter_table_public_moped_proj_personnel_add_unique_project_id_user_id_role_id/down.sql
- moped-database/migrations/1617216384819_alter_table_public_moped_proj_personnel_add_unique_project_id_user_id_role_id/up.sql
This migration creates a unique index that makes sure there will not be duplicate personnel entries in the database table
> Multiple-Select Migration

- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
- moped-editor/src/views/projects/projectView/ProjectTimeline.js
PR that would move the actions column to the right when adding to the Project Team and Timeline tables
Associated with https://github.com/cityofaustin/atd-data-tech/issues/5375
Example:
> Move actions column index to the right on MaterialTable instances

- moped-editor/src/components/GridTable/GridTable.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5830
It appears that switching the ecapris_subproject_id type from string to number is breaking the code. This PR refactors the code so that whenever there is an unavoidable situation whenever we pass a string to a numeric field in a search it assumes a safe default value.
> Moped Editor | Make The Project Search Feature Great Again #5830

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5602
What this branch does is a necessary refactor for the actual migration happening in a different PR. Once the personnel is migrated, they are imported as inactive; however, this presents the projects team page with a problem because the graphql query excludes any inactive users causing the code to a WSOD. Also, I noticed this query gathers the entire list of active users, even if there is no personnel associated to a project, which is not performant or necessary.
** Tried renaming the branch name to have the same github issue number but GitHub it keeps nagging **
> Data Migration | Transform IMPD data to fit moped_proj_personnel table in Moped #5602

- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/5862
This PR updates the `createProjectViewLayerConfig` helper to consider the `visibleLayerIds` array of layer ID names exposed by `useLayerSelect`. If a layer name is in the array, the `visibility` property of the layer's style spec is set to `visible`. Oppositely, the `visibility` property is set to `none` if the layer name is not present in the array. The checkbox UI adds and removes the layer ID names from the `visibleLayerIds` when a user toggles the checkboxes.
This can be tested on https://deploy-preview-291--atd-moped-main.netlify.app/moped/projects/159 by clicking on the Edit button on the map and then toggling the "Drawn" checkbox.
> Project Extent | Fix drawn layer select checkbox

- moped-database/migrations/1619024083593_ecapris_replace_constraint_with_index/down.sql
- moped-database/migrations/1619024083593_ecapris_replace_constraint_with_index/up.sql
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/5881
Replaces the ecapris_subproject_id unique constraint with an unconstrained index and allows ecapris_subproject_id to have no value.
To test, use [this deploy preview environment](https://deploy-preview-288--atd-moped-main.netlify.app/moped) rather than the one associated with this PR. The one I linked here includes a fix for an unrelated bug for a better testing experience. Not that you can't test whether you can put in the same ID twice (unique constraint) in the deploy preview environment. You would have to locally run the [code that establishes that environment](https://github.com/cityofaustin/atd-moped/pull/288).
> Replaces the ecapris_subproject_id unique constraint with an unconstrained index

- moped-editor/src/views/projects/projectView/ProjectSummaryMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6228
Forces the component to throw an error if there are no features to render.
** Test with moped-test or local environment, which include projects without features.
> [Bug] Map error handler not rendering on projects without locations #6228

- moped-editor/src/views/projects/projectView/ProjectView.js
- Fixes https://github.com/cityofaustin/atd-data-tech/issues/5355
- Fully testable in the Netlify deploy preview environment
> Sets project name as HTML page title rather than "Project Summary Page"

- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
Add project status to advanced filters option. I also changed the labels to sentence case. 
Note, project statuses have spaces removed when displayed in the chip. For example, "on hold" is seen as "onhold". If you are searching for "onhold" you will not get any resuts. 
https://6272-add-status-to-filters--atd-moped-main.netlify.app/moped?filter=eyJiNDhlYTUwNi02YTc0LTQ1YjAtOTYwZC05MDI1NDNmNTA3ZDkiOnsiaWQiOiJiNDhlYTUwNi02YTc0LTQ1YjAtOTYwZC05MDI1NDNmNTA3ZDkiLCJmaWVsZCI6ImN1cnJlbnRfc3RhdHVzIiwib3BlcmF0b3IiOiJzdHJpbmdfY29udGFpbnNfY2FzZV9pbnNlbnNpdGl2ZSIsImF2YWlsYWJsZU9wZXJhdG9ycyI6W3sib3BlcmF0b3IiOiJfaWxpa2UiLCJsYWJlbCI6ImNvbnRhaW5zIiwiZGVzY3JpcHRpb24iOiJTdHJpbmcgaXMgY29udGFpbmVkIGluIGZpZWxkIChjYXNlLWluc2Vuc2l0aXZlKSIsImVudmVsb3BlIjoiJXtWQUxVRX0lIiwidHlwZSI6InN0cmluZyIsImlkIjoic3RyaW5nX2NvbnRha …
> Add project status to advanced filters

- moped-editor/src/views/account/AccountView/AccountView.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6620
Live demo:
https://deploy-preview-349--atd-moped-main.netlify.app/moped/account
** UI change only, Can be tested in Netlify, Moped-test, or locally
In the code we simply remove ProfileDetails component from AccountView
> Remove password reset UI from account page #6220

- moped-editor/src/views/projects/projectView/ProjectView.js
Fixes bug introduced by breadcrumbs update
In theory object returned by useLocation() should always include state, but using the optional chaining there too, because one never knows.
> Prevent filter null failure when making new project

- moped-editor/package.json
- moped-editor/src/components/ExternalLink.js
- moped-editor/src/layouts/DashboardLayout/DashboardLayout.js
- moped-editor/src/layouts/DashboardLayout/Footer.js
closes https://github.com/cityofaustin/atd-data-tech/issues/6520
https://deploy-preview-358--atd-moped-main.netlify.app/moped
the netlify sidebar icon slightly covers the footer. What do yall think of the color of the text and the size? Margin/padding?
> Include moped version number in footer

- moped-database/metadata/tables.yaml
- moped-database/migrations/1624984081574_alter_table_public_moped_proj_notes_add_column_added_by_user_id/down.sql
- moped-database/migrations/1624984081574_alter_table_public_moped_proj_notes_add_column_added_by_user_id/up.sql
- moped-editor/src/queries/comments.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
Database updates, so need to test on moped test or locally. 
Testing locally takes a bit of effort. I signed in and made some comments, signing in locally we are all JD. I changed the user_id in `src/auth/user.js` Line 104 to a different userid (ex, Mike Dilley is 8, Nathan Wilkes is 2). Sign out and sign back in and see the comments.  In this screenshot the user is Nathan. 
I thought we had a similar issue in moped-test since when I logged in it says I am Patrick, but I see John has been able to leave comments as himself. 
edit -- now that I check for moped-admin status as well as who authored the comments, you have to sign in as the test-viewer (creds in 1password) to see if the icons are hidden. The user's highest role is based on whose password signed in, so changing the user_id in …
> Prevent edit/delete comment icons from appearing if not comment creator

- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
- moped-editor/src/views/projects/projectView/ProjectComponentEdit.js
- moped-editor/src/views/projects/projectView/ProjectComponents.js
- moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6574
** Front-end changes only, you can use Netlify, moped-test or locally.
Live Preview:
https://deploy-preview-359--atd-moped-main.netlify.app/moped/session/signin
This PR updates the components editor so that whenever a new component is added, it initializes the map to start in the same area as the rest of the project.
> [Project Components] Zoom to extent of all components when creating new component #6574

- moped-editor/src/components/DataTable/DataTable.js
- moped-editor/src/views/projects/projectView/ProjectNameEditable.js
- moped-editor/src/views/projects/projectView/ProjectSummaryTable.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6582
To test: https://deploy-preview-361--atd-moped-main.netlify.app/moped/projects/276/
Try changing title or description to a blank/ empty string. 
I am also adding the field configuration to the gitbook https://app.gitbook.com/@atd-dts/s/moped/dev-guides/api/configuration-files
> Prevent saving Project Title and Project Description as blank strings

- moped-editor/src/views/projects/projectView/ProjectComponentEdit.js
- moped-editor/src/views/projects/projectView/ProjectComponentSubcomponents.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6616
Description:
Refactors subtype & subcomponent logic and removes duplicates
** Front-end change only, test with Netlify
Live Demo:
https://deploy-preview-364--atd-moped-main.netlify.app/moped/session/signin
> [Bug] Previous 'Subtype' stays in text box after selecting new 'Type' #6616

- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/utils/stringToTitleCase.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6253
To test:
https://deploy-preview-365--atd-moped-main.netlify.app/moped/projects/276?tab=summary
hover over street names to bring up tooltip
> Update map hover tooltip styles

- moped-editor/src/routes.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/6774
and should also handle https://github.com/cityofaustin/atd-data-tech/issues/6550 since a user can no longer go to `/moped/?filter=eyJhY2JiZmM0Ni0xNjhlLTRlNDItYWIwZC0yYzFhNz[…]lbnQgcGhhc2UiLCJ2YWx1ZSI6InBvdCIsInR5cGUiOiJzdHJpbmcifX0=` and instead will always be at `/moped/proejcts/?filter=foobarfooetc`
https://6774-redirect-moped--atd-moped-main.netlify.app/
To test: click moped icon, projects tab should be highlighted as active.
> Redirect /moped to /moped/projects

- moped-database/metadata/tables.yaml
- moped-database/migrations/1627672459000_create_table_public_moped_department/down.sql
- moped-database/migrations/1627672459000_create_table_public_moped_department/up.sql
- moped-database/migrations/1627672511597_alter_table_public_moped_workgroup_add_column_department_id/down.sql
- moped-database/migrations/1627672511597_alter_table_public_moped_workgroup_add_column_department_id/up.sql
- moped-database/migrations/1627672550424_set_fk_public_moped_workgroup_department_id/down.sql
- moped-database/migrations/1627672550424_set_fk_public_moped_workgroup_department_id/up.sql
- moped-database/migrations/1627672560000_update_table_moped_workgroup_additional_workgroups/down.sql
- moped-database/migrations/1627672560000_update_table_moped_workgroup_additional_workgroups/up.sql
- moped-database/migrations/1627673512978_update_table_moped_workgroup_add_department_existing_workgroups/down.sql
- moped-database/migrations/1627673512978_update_table_moped_workgroup_add_department_existing_workgroups/up.sql
- moped-database/seeds/1602292389297_initial_seed_staging.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/6768
** MIGRATIONS ONLY:  These can only be tested in **moped-test** or local.
Changes:
Additional workgroups to moped_workgroup table
For Public Works:
- Urban Trails
- Safe Routes to School
- Corridor Program Office
- Sidewalks
- Engineering Services Division
New table, moped_department:
- Austin Transporation
- Corridor Program Office
- Public Works
- Moped Workgroup has a new column department_id, and it has associated relationships
A user can be filtered or grouped by department:
> Add additional workgroups to Moped #6768

- moped-editor/src/views/staff/StaffForm.js
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6475
- Add navigate to callback after user is deleted in staff view
- User is redirected to '/moped/staff/' 
**How to test**
- Visit website using the netlify build preview.
- Make sure your moped account has the ability to delete users.
- Visit staff page and select a user you want to delete.
- Afterwards click the delete user button and then confirm.
> Reroute user to moped staff page after a staff member is deleted

- moped-editor/src/components/CDN/Avatar.js
- moped-editor/src/layouts/DashboardLayout/TopBar.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/4809
* Front-end change only:
Live Demo: https://363-sg-avatars--atd-moped-main.netlify.app/moped/projects/273?tab=activity_log
Refactors the CDNAvatar component and it is applied to the activity log.
> Renders user avatar images in activity feed #4809

- moped-editor/src/components/GridTable/GridTable.js
- moped-editor/src/components/GridTable/GridTableListHeader.js
- moped-editor/src/layouts/MainLayout/MainLayout.js
- moped-editor/src/theme/index.js
- moped-editor/src/views/projects/projectView/ProjectView.js
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6859
- Updated primary main and primary light colors in theme
- Set background color of Table row with `.MuiTableCell-stickyHeader`
- Set background color and text color to AppBar on project pages
- Set indicator color and text color of active tab on project pages
How to view changes
- Visit netlify preview and log in moped
- Go to projects section and look at the table
- Select a project and look at the tabs
- Select a tab and see the change there
- Go to staff section and look at the table
> Miscellaneous color adjustments

- moped-editor/src/components/GridTable/GridTable.js
- moped-editor/src/components/GridTable/GridTableSearch.js
- Closes https://github.com/cityofaustin/atd-data-tech/issues/6748
- Pass table items data as prop from GridTable to GridTableSearch components
- Use table items data prop to disable button if there are no table items
**How to test**
- Visit netlify preview and Log in to moped
- Visit projects page and search for something that doesn't return a list of projects
- See if download button is disabled
> White screen when trying to download table with zero search results

- .github/workflows/aws-heroku-helper.sh
This patch should prevent PostGIS from being installed in moped-test. This is only a problem in Heroku, because PostGIS comes with +5,000 rows, which puts us close to the 10k limit on the free tier and makes us get a bunch of annoying emails.
Tested to work, now the total amount of rows is 1500 (down from 7000+):
> Patch Heroku Deployment Script

- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
- moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
- moped-editor/src/views/projects/projectView/ProjectSummaryMap.js
Updates MaxZoom across all instances of `<ReactMapGL/>`
https://deploy-preview-397--atd-moped-main.netlify.app/
> [Bug] Prevent map from zooming in too close #6821

- moped-editor/package-lock.json
- moped-editor/package.json
- moped-editor/src/components/GridTable/GridTableSearch.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
- moped-editor/src/views/projects/projectView/ProjectTimeline.js
- moped-editor/src/views/reports/DashboardView/LatestOrders.js
- moped-editor/src/views/reports/DashboardView/LatestProducts.js
- Closes https://github.com/cityofaustin/atd-data-tech/issues/5447
- Replaced moment functions with date-fns functions
- Moment was replaced in LatestProducts, LatestOrders, ProjectTimeline, NewProjectView, GridTableSearch components
How to view changes
- Go to dashboard and scroll down to data syncs. Look at last updated.
- Go to dashboard and scroll down to latest staff updates. Look at the date column.
- Go to projects and click on the new project button. Look at start date.
- Go to projects and click on the download button (make sure there are search results). Look at file name.
- Go to projects and select an existing project. Go to timeline and look at start date, end date, date completed, completion estimate columns.
> Replace moment with date-fns throughout moped

- moped-editor/src/views/projects/projectView/ProjectNameEditable.js
Closes cityofaustin/atd-data-tech#7010
In a PEMDAS-type code error, I was incorrectly checking if a title update was empty. 
I wanted to check that `projectName.trim()===""` was not true. But `!projectName.trim()===""` was evaluating as `!projectName.trim()` equals `""`
Test here: https://7010-change-project-name--atd-moped-main.netlify.app/ by changing a project's name and saving.
> Fix bug preventing changing project name

- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/6961
Just needed to explicitly include which columns to export in the csv. I moved the team member filter function into it's own function since it now had to be used twice. 
Test here: https://6961-csv-export--atd-moped-main.netlify.app/moped/projects
> Export all columns when downloading project list view csv

- moped-editor/src/queries/project.js
- moped-editor/src/utils/mapHelpers.js
- moped-editor/src/utils/signalComponentHelpers.js
- moped-editor/src/views/projects/newProjectView/NewProjectMap.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
- moped-editor/src/views/projects/newProjectView/SignalAutocomplete.js
- moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
- moped-editor/src/views/projects/projectView/SignalComponentAutocomplete.js
Fixes [#7136](https://github.com/cityofaustin/atd-data-tech/issues/7136).
- Source signal component definitions from Moped DB
-  Unifies input props for SignalAutoComplete and SignalComponentAutocomplete components
- Addresses a few linter warnings
> Resolves follow-up tasks to signal-based component editing

- .github/workflows/atd_moped_build_stage.yml
- .github/workflows/aws-moped-api-helper.sh
- moped-api/requirements/development.txt
- moped-api/requirements/moped_test.txt
- moped-api/requirements/production.txt
- moped-api/requirements/staging.txt
Closes https://github.com/cityofaustin/atd-moped/issues/424
Downgrades setuptools to v 57.5.0 as per breaking changes in newest version:
https://setuptools.pypa.io/en/latest/history.html#v58-0-0
> [Bug] Fix moped-test API deployment #424

- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryLabel.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectWebsite.js
- moped-editor/src/views/projects/projectView/ProjectView.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/7491
- Removes text under map
- Moves map controls to bottom right
- Pencil icon is now outline
- Updates menu options (and dialog)
- Updates text color to #828282 (secondary text)
- website is 1/2 the width (xs=6)
https://deploy-preview-461--atd-moped-main.netlify.app/moped/session/signin
> Implement design and layout refinements to "Summary" tab #7491

- moped-editor/src/views/projects/projectView/ProjectComponentEdit.js
- moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/7665
https://deploy-preview-465--atd-moped-main.netlify.app/moped/session/signin
Be sure you are in Windows 10, Chrome 98
Go to Map, look at list of components, it should not show scrollbars:
---
> [Bug] unneccessary scroll bars show up in map components panel on Windows/Chrome #7665

- moped-editor/src/queries/signals.js
- moped-editor/src/utils/signalComponentHelpers.js
- moped-editor/src/views/projects/newProjectView/SignalAutocomplete.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/SignalComponentAutocomplete.js
- moped-editor/src/views/projects/signalProjectTable/RenderSignalLink.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
Addresses: https://github.com/cityofaustin/atd-data-tech/issues/7556
I’m getting the knack id for the signal from the socrata payload. Existing signal projects in our database don't include their knack ids, so those signal ids are not linked to their knack page.
Also when testing this PR I realized that I wasn't filtering on active features, so deleted signals were still showing up.
**URL to test:** https://7556-signal-id-link--atd-moped-main.netlify.app/moped/dashboard
Add one (or more) signals to a project. Check the dashboard view, signal ids column (2nd from left) should contain list of signals by their id. Clicking on one will open a new tab with that knack signal page. 
---
> Add links to Knack Signal Projects

- moped-editor/src/views/projects/projectView/ProjectView.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/7667
Only a frontend change so testing in preview app ok.
**URL to test:** https://deploy-preview-468--atd-moped-main.netlify.app/
- Go to any project summary page and see the new order of the tabs
Ex:
---
> Reorder project summary tabs

- moped-editor/src/queries/signals.js
- moped-editor/src/views/projects/signalProjectTable/RenderSignalLink.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
Addresses: https://github.com/cityofaustin/atd-data-tech/issues/7582
**URL to test:** https://7582-add-columns--atd-moped-main.netlify.app/moped/dashboard
Add Inspector(s) and Designer(s) to moped signal projects. You should see their names in the appropriate columns. Clicking on the cells will open that project's team tab. 
Add a completion date to a project by adding a Complete phase. Clicking on that cell or the projected construction start should open that project's timeline tab.
---
> Add additional columns to signal project management table view

- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/7830
**URL to test:** https://7830-signal-tweaks--atd-moped-main.netlify.app/moped/dashboard
**Steps to test:** The project name column has been widened from 60ish px wide to 150px wide. Renamed the column for status update. 
---
- [x Product manager approved
> Minor style tweaks to signal projects dashboard

- moped-editor/package-lock.json
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
Precludes: https://github.com/cityofaustin/atd-moped/pull/475
Closes https://github.com/cityofaustin/atd-data-tech/issues/7635
https://deploy-preview-471--atd-moped-main.netlify.app/moped/projects/new
Create a new project (either a signal project or otherwise), you should see the "potential" phase as the default.
---
> Add current phase and current status to new project mutation#7635

- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/7859
https://7859-screen-tabs--atd-moped-main.netlify.app/moped/projects/360/
Load screen, make window smaller than width of tabs. See the appearance of scroll buttons. 
On mobile views, check that you can drag to scroll the tabs. 
---
> Enable scrollable tabs on Project View on smaller screens

- moped-database/metadata/tables.yaml
- moped-database/migrations/1638905763818_run_sql_migration/down.sql
- moped-database/migrations/1638905763818_run_sql_migration/up.sql
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectPartners.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
https://github.com/cityofaustin/atd-data-tech/issues/7360
I added project partner and project sponsor the Projects page, as well as the advanced search, the more straightforward search and the csv export configuration. 
There are DB changes, so run locally or use moped-test.
From a product summary page, add project partners and/or a project sponsor to a project. They should be visible on the projects page and come up in the search results. 
---
> Add "Project partners" and "Project sponsor" to "Projects" page

- moped-editor/src/views/projects/projectView/CommentInputQuill.js
- moped-editor/src/views/projects/signalProjectTable/RenderSignalLink.js
https://github.com/cityofaustin/atd-data-tech/issues/7933
https://7933-external-link-signal--atd-moped-main.netlify.app/moped/dashboard
Check the linked signals on the signal dashboard. They links should all have icons after each link. 
---
> Add external link icon to signal links

- moped-editor/src/queries/signals.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryLabel.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/7870
https://7870-edit-in-place--atd-moped-main.netlify.app/moped/dashboard
https://7870-edit-in-place--atd-moped-main.netlify.app/moped/projects/323/
Check in the summary view that you don't see any pencils. That clicking a field will open the edit capability. 
On the signals dashboard you shouldn't be able to edit a row. Empty editable fields will have a hyphen as a placeholder. 
---
> Standardize edit-in-place and hyperlink UIs

- moped-database/metadata/tables.yaml
- moped-database/migrations/1637823185562_alter_project_list_view/up.sql
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
none
This fixes the release candidate not building. Recent commits to main have edited the Project List SQL View, but once it was merged with production, errors appeared. 
> (so it could be that this commit got patches into production, that never got merged into main https://github.com/cityofaustin/atd-moped/commit/a8f9f922b54c6c8d79ff33fb05670c0a80785ce9? (edited) )
Our newer Views drop a column, so I dropped the View before creating or replacing: https://dba.stackexchange.com/questions/77564/postgresql-drop-column-from-view
This PR also removes the other references to that dropped column. 
---
> Drop project list view before creating new one

- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
https://github.com/cityofaustin/atd-data-tech/issues/7320
https://7320-status-tooltip--atd-moped-main.netlify.app/moped/projects/182/
---
> Add tooltip to project status button

- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
This PR intends to address the paticular H2 seen in https://github.com/cityofaustin/atd-data-tech/issues/7865 but not to close the issue.
https://deploy-preview-488--atd-moped-main.netlify.app/moped/
View a project's activity feed and observe the header.
---
> 7865: Return activity feed page header to a san-serif font

- moped-editor/src/theme/index.js
- moped-editor/src/theme/typography.js
- moped-editor/src/views/projects/projectView/ProjectFiles.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/7865
Material table has this line (https://github.com/mbrn/material-table/blob/master/src/components/m-table-cell.js#L132) where the cell style has fontFamily inherit. Why does this revert to serif, I cannot seem to figure out. One fix is to explicitly set the typography on cellStyle for cells that aren't editable. 
I also set a fallback font style on the theme. That didn't solve the issue on material table rendering, but I am leaving it there as a failsafe. 
https://7865-font-issues--atd-moped-main.netlify.app/moped/projects/182?tab=files
On a project files view, click the pencil to edit a row. Cells that arent being edited should not revert back to a serifed font. 
---
> Fix font rendering issues on material table

- moped-editor/src/utils/materialTableHelpers.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/7998
Thanks to Amenity for linking to this issue: https://github.com/mbrn/material-table/issues/709#issuecomment-566097441
https://7998-sticky-header--atd-moped-main.netlify.app/moped/dashboard
Resize window and see that signal table also resizes. Headers should stay put.
---
> Set headers on signal dashboard as sticky

- moped-editor/src/views/projects/projectView/KnackSync.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryKnackDataTrackerSync.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryLabel.js
This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/7777. 
https://flh-7777-sync-ui-element--atd-moped-main.netlify.app/moped/projects
NB: The staging database has a number of projects which indicate they are synchronized to knack, but the development knack database has had the corresponding records removed in the course of development. I would be happy to get connected to the staging database and remove these stale knack IDs - please let me know if this would be helpful.
NB: Also, please note that the URL that is used when sending the user to knack after they click on the "View in Data Tracker" link is based on the production Knack URL even when being used in testing. I attempted to put in some logic to direct the user to the development Data Tracker instance, …
> 7777: New UI element for sync to Data Tracker

- moped-editor/src/queries/signals.js
the query used to be: 
``` 
where: {
_or: [
{
moped_proj_components: {
moped_components: { component_name: { _ilike: "signal" } }
}
status_id: { _is_null: true }
}
{
moped_proj_components: {
moped_components: { component_name: { _ilike: "signal" } }
}
status_id: { _neq: 4 }
}
],
status_id: {_neq: 6}
}
```
which was preventing projects with a null status from showing up. Which seem to be existing projects / seed projects that then get a signal added to it. (I guess you can't both be is_null is true and _neq: 6?)
now it will be signal projects with either null status, or not 3 or not 6. 
---
> Update filters on signal dashboard query

- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/8244
Deploy to test, to test!
Missing edit hyphen for some projects -- save a blank project DO#, by entering only empty spaces and saving. it should still render as a - instead of the blank spaces
To test the disappearing project sponsor. First, try resizing the screen. confirm the column texts dont disappear. Try updating other fields and the project sponsor shouldn't go away. 
I think this should also fix the project DO# not wanting to save. I can't see in the video of the bug, but I suspect the project sponsor had disappeared so when the project DO was trying to save, it was sending "undefined" as the project sponsor, thus preventing the update from completing. That is my conjecture though, since …
> Patch project sponsor disappearing bug

- moped-editor/package.json
Fix deploy error for Moped v0.13.0 by pinning the version of `npm` that runs to 6+.
---
> Fix 0.13.0 Deployment

- moped-database/migrations/1642785096000_update_moped_components_table/down.sql
- moped-database/migrations/1642785096000_update_moped_components_table/up.sql
- moped-editor/src/queries/project.js
https://github.com/cityofaustin/atd-data-tech/issues/8058
Database changes, so must be local or on moped test. 
To see the changes on the moped entity table: Go to a projects summary page and select the partner dropdown. COA ATD Vision Zero is now an option. (Note, when I tested locally, that option moved to the bottom of the list. I'm not sure if the order in the dropdown matters, but if it does we could order by enitity_id)
To see the moped components change, go the map tab, add a new component and look for a Crosswalk with only 2 s. 
---
> Perform miscellaneous database updates

- moped-database/hasura-cluster
This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8264. 
This is a tricky one to test. Two routes come to mind:
- This nonsensical approach is the result of us not really having direct access to the actual linux VMs on which this build step happens, I believe. 
---
> Fix moped DB documentation build step by special casing the architecture detection on GNU/Linux

- moped-editor/package.json
None. This adjusts the spelling of `license` in `moped-editor/package.json` to the common American spelling to align with the [NPM docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json). 
**URL to test:** N/A
* Review the code changes in this PR.
---
> American-style spelling of license in the editor's package.json file

- .github/workflows/atd_moped_build_stage.yml
- .github/workflows/aws-heroku-helper.sh
none
The way to test is to deploy this branch to the test instance and see if the db builds successfully on heroku.
Recently hasura's graphql-engine-heroku dockerfile was updated (https://github.com/hasura/graphql-engine-heroku/commit/da63f74c5494226e6342b4bc03ec236286370dc3) and the new command uses a [different flag](https://hasura.io/docs/latest/graphql/core/deployment/graphql-engine-flags/reference.html#graphql-engine-command-flags-environment-variables) that is only available on versions of hasura greater than 2.0.0.
Since we were editing the dockerfile to use 1.3.3, this was failing on Heroku. I changed the aws-heroku-helper script to check out the commit to master that uses 1.3.3. 
https://atd-moped-editor-development.herokuapp.com/console/login …
> update workflow to use graphql-engine-heroku where version is 1.3.3

- moped-database/hasura-cluster
_none_
Testing really is just to look at the code; this is a one-liner.
But for completeness: Testing needs to be done locally, and can be done by spinning up the database that does not have `moped-database/config/hasura.${ENVIRONMENT}.yaml` in place. One should observing that the command is correctly named in the directions that come out of the `hasura-cluster` management tool.
Previous behavior:
---
> Correct DB management tool name in echoed directions for use

- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryKnackDataTrackerSync.js
Refactor knack sync for new db schema and simplify chaining:
- rework the method to extract + count signal features
- remove the branching on the knack PUT/POST request chain
> Refactor knack sync for new db schema and simplify chaining

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryWorkOrders.js
Discovered a minor issue during release that the knack work order ID needs to be updated with Moped project ID.
---
> Fix work order link to Data Tracker (production patch)

- moped-database/metadata/tables.yaml
- moped-database/migrations/1644608438018_drop_moped_proj_features_components/down.sql
- moped-database/migrations/1644608438018_drop_moped_proj_features_components/up.sql
This takes care of some DB cleanup related to components. We deprecated the use of the `moped_proj_features_components` table as part of https://github.com/cityofaustin/atd-moped/pull/553, but the table and relationships still exist in the DB.
This PR completely removes moped_proj_features_components from the DB.
https://github.com/cityofaustin/atd-data-tech/issues/8462
**URL to test:** https://moped-test.austinmobility.io/moped
Create and test projects with various components. Verify data is saved and rendered as expected.
---
> Remove metadata and drop unsued moped_proj_features_components table

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/8440
**URL to test:** https://deploy-preview-584--atd-moped-main.netlify.app/moped/projects
- check positioning of Zoom controls and Basemap switcher. They should be in the bottom right for both the Project Summary and Project Map pages.
---
> Fix map controls UI bug

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/ProjectComponentsMapView.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
https://github.com/cityofaustin/atd-moped/pull/584
Closes https://github.com/cityofaustin/atd-data-tech/issues/8440
**URL to test:** https://deploy-preview-585--atd-moped-main.netlify.app/moped/projects
- check positioning of Zoom controls and Basemap switcher. They should be in the bottom right for both the Project Summary and Project Map pages.
---
> Fix map controls UI bug (1.0.4 patch to main)

- moped-editor/src/layouts/DashboardLayout/DashboardLayout.js
- moped-editor/src/layouts/DashboardLayout/TopBar.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/8234
URL to test:
https://deploy-preview-559--atd-moped-main.netlify.app/ 
not sure how to test this because the banner will only display in the staging environment. @mateoclarke or @chiaberry , do you have any thoughts? will add @amenity for review once we sort that out.
---
> Displays an alert banner in the staging environment

- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/8098
https://8098-column-filter--atd-moped-main.netlify.app/moped/dashboard 
Test the filters that appear at the top of the signals table. Specifically test that 
- project types
- task orders
- project sponsors
are able to be filtered. Also we have the option to change the filter icon, if that is desired. 
---
> Add filtering capability to signal dashboard table

- moped-editor/src/components/GridTable/GridTableFilters.js
- moped-editor/src/components/GridTable/GridTableSearch.js
- moped-editor/src/components/GridTable/GridTableSearchBar.js
The netlify branch has the icon's background color changed if the advanced search is active. Here is the alternative:
[https://8556-active-search--atd-moped-main.netlify.app/moped/projects?](https://8556-active-search--atd-moped-main.netlify.app/moped/projects?filter=eyIzNDA3M2JiMi1mMzk0LTQ3YmUtYWRmNi0xMzZiZWE0MjkwNjkiOnsiaWQiOiIzNDA3M2JiMi1mMzk0LTQ3YmUtYWRmNi0xMzZiZWE0MjkwNjkiLCJmaWVsZCI6InByb2plY3RfdGVhbV9tZW1iZXJzIiwib3BlcmF0b3IiOiJzdHJpbmdfY29udGFpbnNfY2FzZV9pbnNlbnNpdGl2ZSIsImF2YWlsYWJsZU9wZXJhdG9ycyI6W3sib3BlcmF0b3IiOiJfaWxpa2UiLCJsYWJlbCI6ImNvbnRhaW5zIiwiZGVzY3JpcHRpb24iOiJTdHJpbmcgaXMgY29udGFpbmVkIGluIGZpZWxkIChjYXNlLWluc2Vuc2l0aXZlKSIsImVudmVsb3BlIjoiJXtWQUxVRX0lIiwidHlwZSI6InN0cmluZyIsImlkIjoic3RyaW5nX2NvbnRhaW5zX2Nhc2VfaW5zZW5zaXRpdmUifSx7Im9wZXJhdG9yIjoiX2lsaW …
> Indicate that an advanced search is active on the "Projects" page

- moped-data-events/activity_log/MopedEvent.py
This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/8640.
My branch name has the issue number typo'd in it. I can delete that branch and cherry pick these two commits into a new one if needed.
https://moped-test.austinmobility.io/moped
1) Deploy this branch to test
1) Connect to the heroku DB directly with an SQL client so you can look at exact values in `moped_project.updated_at`
1) Update a project itself (the description or name, perhaps) and see that the last updated value for that record updates to `now()`
1) Update a record that is tied to the project but not stored in the project table, such as adding a note or a phase
1) Observe that the new "child" record is created and documented in the activity log, *and* that the project's …
> Update λ function to use `recordProjectId` when mutating `moped_project` table

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/ProjectFundingTable.js
As we transition to using S3 as the source for task order data, we will no longer have the unique Knack `id` column in the [Socrata task orders dataset](https://data.austintexas.gov/Transportation-and-Mobility/-TEST-Mobility-Project-Task-Orders/ggav-ufvc). We use the `id` value in Moped to key on a unique task order when adding/removing task orders to a project record. 
This PR swaps out `id` for the the `task_order.task_order` property, which is an alphanum string that uniquely identifies each task order. 
Until this is merged, it’s now possible to duplicate the same task order on the funding tab.
https://github.com/cityofaustin/atd-data-tech/issues/7931
**URL to test:** [Netlify dep prev](https://deploy-preview-607--atd-moped-main.netlify.app/)
Create a signal …
> Use a different  task_order property to key on unique task orders

- moped-editor/src/views/projects/projectView/ProjectComments.js
https://github.com/cityofaustin/atd-data-tech/issues/8001
https://8001-comments--atd-moped-main.netlify.app/moped/projects/1825?tab=comments
This is a tricky one to test, because I couldn't get the bug to consistently occur before my changes. But periodically, quickly toggling between comment type buttons would result in just a loading icon that would go away once you refresh the page. 
I believe it was because of two things: The loading icon appeared if `loading` was true or `!data` was true. Not always, but sometimes we would fall into the state of loading being false yet having no data. The network request tab did have a successful request, so something was getting stuck. I moved the loading icon to appear under the input since the input doesn't …
> Change loading icon and data refreshing on comments tab

- moped-editor/README.md
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryKnackDataTrackerSync.js
This PR is associated with and a child of PR #632 and is ultimately spawned from issue https://github.com/cityofaustin/atd-data-tech/issues/8868. 
This changes the field in the moped database which is used for the label field when synchronizing to Knack. I generally work from the first project in our seed data, and it just so happens to have the same value for hte `project_name` and `project_description` which caused me to mix up the two fields. This was my error and oversight 👎 .
While we can run the script provided by https://github.com/cityofaustin/atd-moped/pull/632 prior to this getting into production, there is opportunity for the data tracker app to very slowly drift out sync. Once this PR gets into production, if we run the script from …
> Change from description to name for label value in Knack Sync functionality

- moped-toolbox/README.md
_None_, however this PR is intended to implement @mateoclarke's [suggestion of including usage instructions](https://github.com/cityofaustin/atd-moped/pull/632) for the backfill script in the `README.md`.
None, however, please feel free to read and suggest any changes to the documentation that you think would be helpful.
---
> Add usage instructions for the Knack backfill script to README.md

- moped-editor/src/components/GridTable/GridTable.js
- moped-editor/src/components/GridTable/GridTableFilters.js
- moped-editor/src/components/GridTable/GridTableSearch.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
https://github.com/cityofaustin/atd-data-tech/issues/9038
Takes the same sort functions that we were using in Grid Table and overrides the Material Table sorting function to use ours. 
While testing this PR, I noticed that if you toggle columns and then open the advanced filter dropdown, your column configuration gets reset. I lifted the advancedSearchAnchor's state up one level so we can listen for any changes to it and store the column configuration then as well. 
https://9038-custom-sorting--atd-moped-main.netlify.app/moped/projects/
Click the arrow next the column header to sort by column. initially sorts asc, then if clicked again will sort desc. 
Signal IDs cannot be sorted as is, because of the way the data is in the material table. If you try …
> Use GridTable sort function in Material Table

- moped-database/docker-compose.arm64.yml
- moped-database/docker-compose.x86_64.yml
This PR disables (on our local, development database instances) a PostgreSQL feature which is not intended for the type of queries we utilize. Turning this feature off makes our development databases match the configuration of our production databases.
_none_
This change is the result of a discussion with @chiaberry regarding the query driving the `view` she is developing that had suddenly becoming slow when a sub-select was added to the `select` clause. 
After examining the `EXPLAIN ANALYZE` output, we observed that query compiler was using JIT optimizations for the query.  Here are some docs concerning the JIT optimizer: https://www.postgresql.org/docs/current/jit.html. From those docs:
> JIT compilation is beneficial primarily for long-running CPU-bound queries. Frequently these will …
> Disable JIT code compilation on local postgres

- moped-database/migrations/1652877867946_project-list-view-dedup-signal-assets/down.sql
- moped-database/migrations/1652877867946_project-list-view-dedup-signal-assets/up.sql
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
This PR intends to close [#9167](https://github.com/cityofaustin/atd-data-tech/issues/9167).
Testing requires a migration, so this needs to be on [_test_](https://moped-test.austinmobility.io/moped) or in your local development environment.
* Create a new project using a signal asset so you start out with a component and feature
* Add at least one more signal component, selecting another signal. 
* Navigate to the summary page and add 2+ project partners
* Navigate to the funding tab and add 2+ task orders
* Navigate to the project listing page
---
> Modify view underlying project listing page to address signal duplication

- moped-database/migrations/1653656860634_sidewalk_ramps_subtype_typo/down.sql
- moped-database/migrations/1653656860634_sidewalk_ramps_subtype_typo/up.sql
Resolves https://github.com/cityofaustin/atd-data-tech/issues/9313 🐏 
- locally or Moped Test
1. Navigate to a project's **Map** tab
2. Click the **Add new component** button
3. Select **Sidewalk** as the component **Type**
4. Select **Ramps** as the component **Subtype**
5. Select a location on the map and save the component
6. Verify that the component subtype is spelled "Ramps", not "Rams"
---
> Fixes typo in sidewalk ramps component_subtype

- moped-database/migrations/1654646507541_proj_list_view_fund_src_filter/down.sql
- moped-database/migrations/1654646507541_proj_list_view_fund_src_filter/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/9406
This needs to be tested on moped-test. I deployed it just a moment ago so it will be there if no one else needs it in the meantime.
1. Create a new non-signal project
2. Add a funding source with a status that is anything other than **Tentative**
3. Check the Project table view and see that the funding source is visible
4. Try every other funding source status, and you should see it visible in the table
5. Delete the funding source and you should see it removed from the Project table view
---
> [RC patch] Fix funding source filter in project_list_view to filter sources not soft deleted

- moped-editor/src/views/projects/projectView/ProjectTimeline.js
https://github.com/cityofaustin/atd-data-tech/issues/9410
https://9410-disable-editing-phase--atd-moped-main.netlify.app/moped/session/signin
Add a milestone to the milestone table. You should not have the option to edit the related phase. 
Editing a milestone also will not give you the option to edit the related phase. 
---
> Bug Fix - Disable editing related phase on milestones table

- moped-editor/src/views/projects/projectView/ProjectTimeline.js
I am specifying a width for the columns in the table, previously they would just automatically size, giving all the columns the same size (except the description column which we already give a width to)
https://github.com/cityofaustin/atd-data-tech/issues/9455
https://9455-column-width--atd-moped-main.netlify.app/moped/projects/1840?tab=timeline
compare these column widths to issue image or what is currently in staging/prod
---
> Adjust column width for milestone table

- moped-database/metadata/tables.yaml
- moped-toolbox/README.md
- moped-toolbox/amd_milestones_backfill/create_milestones.py
- moped-toolbox/amd_milestones_backfill/queries.py
- moped-toolbox/amd_milestones_backfill/requirements.txt
- moped-toolbox/amd_milestones_backfill/secrets.py
- moped-toolbox/amd_milestones_backfill/utils.py
This will resolve https://github.com/cityofaustin/atd-data-tech/issues/9257 once it's approved and tested in staging and run against production.
1. You'll need a python 3.x environment with `requests` installed.
2. Use the Moped editor to create a new project. Do not use the milestone template when you create the project.
3. Edit the project type of your project to one of "Signal - Mod", "Signal - New", "PHB - Mod", "PHB - New"
4. Run `create_milestones.py`, and set `--env (-e)` to `local` and the `max-date-added (-d)` arg date to be in the future
```
python create_milestones.py -e local -d '2022-06-17 00:00:00'
```
5. Navigate to your project timeline can confirm the template milestones have been added.
Other things you can test:
- Repeat the …
> Backfill projects with template milestones

- moped-editor/src/views/projects/projectView/ProjectStatusBadge.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/9174
https://deploy-preview-685--atd-moped-main.netlify.app/
1. Go to any project summary page.
2. Click on the three dots in the top right, select "Place on hold"
3. See the gray status button added next to the project title on the Project Details Page
4. Go to All Project table, and see all status buttons (including on hold projects) render
---
> Fixes bug preventing on hold status on projects pg

- moped-editor/src/views/projects/projectView/ProjectFundingTable.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/9216
https://deploy-preview-692--atd-moped-main.netlify.app/moped/session/signin
1. go to project funding tab
2. select add new funding source
3. add new funding source without selecting a 'source'
---
> Make fund source field not required

- moped-editor/src/theme/index.js
- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
When I was working on the subprojects table issue, I looked at the Team Table as reference and noticed that it still had the functionality to handle adding a Team member when creating a new project. I cleaned up the unused functions. And then when testing these changes, I noticed that when a team member has more than one role in staging, the word null is rendered in the notes. So I also fixed that. 
in staging: 
none
https://chia-person-table-cleanup--atd-moped-main.netlify.app/moped/projects/1815?tab=team
Add some personnel, remove some personnel. No functionality should change (except the bug fix)
---
> Clean up unused functions in personnel table

- moped-editor/src/views/dashboard/DashboardEditModal.js
- moped-editor/src/views/dashboard/DashboardView.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/9495
https://deploy-preview-689--atd-moped-main.netlify.app/
1. Add status updates to an existing project (for both a regular project and a signal project)
2. Follow the project and add yourself to the team
3. Go to comments tab and add formatting and an emoji to the comment 
4. Check the following views to ensure rich text is displayed: project summary, comments tab, all projects view, signals projects view, dashboard view (my projects and following)
Note: Rich text is already sanitized before being saved in comments view. Added sanitization when adding a new status update on summary page.
---
> Sanitize and render comments with rich text

- moped-editor/package.json
As discussed [here](https://github.com/cityofaustin/atd-moped/pull/695#issue-1282937937) and [in slack](https://austininnovation.slack.com/archives/CHZE6BC6L/p1655417502246739?thread_ts=1655413287.536209&cid=CHZE6BC6L), the `react-map-gl-draw` package has an outdated react dependency (`v16`) - which requires that we force install that package.
This PR adds a dependency override ([docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides)) to allow us to run a clean, lock-free install of Moped as necessary.
We'll need to keep an eye on this override as it may become undesired/outdated in the future.
This change has no effect on our installed packages and does not need to be UI tested. To see the effects:
1. Delete `package-lock.json` and `node_modules/`
2. `$ npm install` …
> Overrides react-map-gl-draw react dependency

- moped-editor/src/queries/project.js
- moped-editor/src/queries/subprojects.js
- moped-editor/src/views/dashboard/DashboardView.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryParentProjectLink.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectDescription.js
- moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js
- moped-editor/src/views/projects/projectView/ProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/9330
https://9330-link-to-parent--atd-moped-main.netlify.app/moped/projects/1841/
1. Add a child project to an existing project. Use the link from the subprojects table to visit summary page of child project. 
2.  Child project should have a link to parent project
3.  if there is no parent project, i.e. the project is not a subproject, the field in the summary page should not render. (You can tell a project is not a subproject by checking to see if the subprojects table is showing)
---
> Add link to parent project from subproject summary page

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/9472
https://deploy-preview-700--atd-moped-main.netlify.app/
go to a project with a status that was added by another user
attempt to edit the status on both the summary view and the comments page
you should not be able change the status, even if you are an admin
add a project status to an existing project
you should be able to edit the status in both the summary view and comments page
---
> Only allow users who wrote statuses to edit them

- moped-editor/src/queries/timelineLookups.js
- moped-editor/src/routes.js
- moped-editor/src/views/dev/LookupsView/RecordTable.js
- moped-editor/src/views/dev/LookupsView/index.js
- moped-editor/src/views/dev/LookupsView/settings.js
Hoping to replace [this spreadsheet](https://docs.google.com/spreadsheets/d/13EbvdJNoZRCXQOJZJdrUqTUb2-o2puMXhiZN_94_go0/edit#gid=217441231) in service of https://github.com/cityofaustin/atd-data-tech/issues/9593.
Depends on https://github.com/cityofaustin/atd-moped/pull/716.
**URL to test:** Moped test or local.
1. Navigate to `/moped/dev/lookups`
2. Tables with `moped_phases`and `moped_milestones` should render.
---
> Adds a secret view of moped phases and milestones

- moped-editor/src/components/CDN/Avatar.js
- moped-editor/src/layouts/DashboardLayout/TopBar.js
- moped-editor/src/queries/project.js
- moped-editor/src/utils/getInitials.js
- moped-editor/src/utils/test/userNames.test.js
- moped-editor/src/utils/userNames.js
- moped-editor/src/views/account/AccountView/Profile.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogDialog.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
- moped-editor/src/views/projects/signalProjectTable/SignalProjectTable.js
https://github.com/cityofaustin/atd-data-tech/issues/9673
This PR fixes a bug where inactivated users were showing as "Unknown User" in the team table and the activity log. The "Unknown User" came from two separate components and was implemented in two different ways so I pulled out some helpers to align how we are getting user full names and initials from the Hasura response or Local Storage and added some tests.
Let me know if some of these changes are not a good path forward. I think the two helpers cover our bases but I could also be looking at it naively. 🙏 
https://deploy-preview-721--atd-moped-main.netlify.app/moped/projects/1859?tab=summary
_The user in these steps is actually a soft deleted user account record with first name of **Inactive** …
> Show inactive users in activity log and team table

- moped-database/migrations/1658432462800_delete_moped_status_6_archived/down.sql
- moped-database/migrations/1658432462800_delete_moped_status_6_archived/up.sql
- moped-editor/src/queries/project.js
https://github.com/cityofaustin/atd-data-tech/issues/8238
This PR removes a `moped_status` row that was originally intended for project soft deletes. Those deletes now use `is_deleted` (see https://github.com/cityofaustin/atd-data-tech/issues/9300) so we no longer need this row.
https://deploy-preview-726--atd-moped-main.netlify.app/moped/projects/new
_The database migration can be tested locally_
Devs - I checked the staging and production read replicas and seed data for any projects that have `status_id` of 6, but I'd like if someone else can back me up that this update will not break any existing records.
1. Create a new project using a Timeline template to test that the change to the `ADD_PROJECT` mutation didn't break things
---
> Remove "Archived" row in `moped_status` table

- moped-database/metadata/tables.yaml
- moped-database/migrations/1659028303595_set_fk_public_moped_milestones_related_phase_id/down.sql
- moped-database/migrations/1659028303595_set_fk_public_moped_milestones_related_phase_id/up.sql
- moped-editor/src/queries/timelineLookups.js
- moped-editor/src/views/dev/LookupsView/RecordTable.js
- moped-editor/src/views/dev/LookupsView/index.js
- moped-editor/src/views/dev/LookupsView/settings.js
https://github.com/cityofaustin/atd-data-tech/issues/9871
**URL to test:** local or moped-test
1. Navigate to `/moped/dev/lookups/` 
2. Click on the link icon next to the **Moped phases** table
3. Observe that the table may scroll slightly into view, and the URL in your browser updates with the table's hash (`#moped-phases`)
4. Do the same thing with the **Moped milestones** table
5. Confirm that the **Related phase** column renders on the milestones table
6. Copy the full url with `#moped-milestones` into a new tab and confirm that the page scrolls to that table.
---
> Adds hash links and related phase column to lookups view

- moped-etl/prefect/tasks/ecs.py
Sibling PR: https://github.com/cityofaustin/atd-prefect/pull/32
Small change:
* Configures the health check on the ALB's target group so it can accurately tell if a graphql-engine is up and running nominally. 
This prevents the ALB from flapping the ECS task instance.
> Define ALB health check location and valid responses

- moped-etl/prefect/moped_test_create_flow.py
- moped-etl/prefect/tasks/migrations.py
* This PR intends to close https://github.com/cityofaustin/atd-data-tech/issues/10026.
* This PR has no substantive changes in the prefect repo and no sibling PR.
This configure the flow to, when presented with the value of `seed` for the parameter `database_seed_source` to build the DB from seed data and not replicate it from the read replica.
> Add ability to populate test deployment from seed data

- moped-database/metadata/tables.yaml
- moped-database/migrations/1660317454947_rename_purchase_orders_to_contracts/down.sql
- moped-database/migrations/1660317454947_rename_purchase_orders_to_contracts/up.sql
- moped-editor/src/queries/funding.js
- moped-editor/src/views/projects/projectView/ProjectContractsTable.js
- moped-editor/src/views/projects/projectView/ProjectFunding.js
- moped-toolbox/purchase_order_backfill/create_crontacts.py
- moped-toolbox/purchase_order_backfill/queries.py
Fixes https://github.com/cityofaustin/atd-data-tech/issues/9967
This is mostly a find/replace of https://github.com/cityofaustin/atd-moped/pull/720.
I did test the migrations against scenarios where we actually have existing records in the `moped_purchase_order` table.
**URL to test:** Moped test or local
Test deployment: https://9967-jc-rename-purchase-orders-to-contracts--atd-moped-main.netlify.app/moped
add / edit / delete / update records to the table on the funding tab.
to test locally, I added some contractors and DOs via the summary tab to various projects.
Then I ran the script (create_contracts.py -e local)
And checked on the funding tab that the information I added in the summary tab showed up on the PO table
---
> Rename purchase orders to contracts

- moped-etl/prefect/moped_test_create_flow.py
- moped-etl/prefect/tasks/activity_log.py
- moped-etl/prefect/tasks/api.py
- moped-etl/prefect/tasks/ecs.py
- moped-etl/prefect/tasks/migrations.py
- moped-etl/prefect/tasks/netlify.py
Sibling PR: https://github.com/cityofaustin/atd-prefect/pull/36
- This was failing silently and was maddening 
- Considering if this should go into the environment?
This is a messy PR, and in hindsight would have been better to break up. The practicality of doing that would have been questionable given how the tools have been used over the last few days -- but it does make it a bit more of a mess to review. Sorry about that! I am going to be much better about breaking them out into PRs as much as possible!
> Slugging, Seed application, API rebuild, & API correct version

- moped-database/migrations/1661803938508_add_four_more_moped_funds/down.sql
- moped-database/migrations/1661803938508_add_four_more_moped_funds/up.sql
- moped-editor/src/queries/funding.js
Fixes https://github.com/cityofaustin/atd-data-tech/issues/10136.
When Chia did https://github.com/cityofaustin/atd-data-tech/issues/10025, we discovered that there are eCapris projects with fund codes unknown to Moped. This PR adds those missing funds.
I decided to also add sorting to our `moped_funds` query, since that list has grown organically and is now quite long.
**URL to test:** Moped test.
https://10136-jc-more-fund-sources--atd-moped-main.netlify.app/moped/projects
1. go to **Funding** tab and add a new funding source
2. On the **Fund** dropdown, verify the fund names are sorted by fund code ascending.
3. Verify these funds are available:
```
4730 | PARKING CIP
PLAN | PLANNING FAOS
4720 | ATD TRANSPORTATION CIP
8071 | GCP-TRANSP MOBILITY IMPV P1/00
```
---
> Adds additional moped_funds

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/index.js
- moped-editor/src/views/dev/LookupsView/settings.js
https://github.com/cityofaustin/atd-data-tech/issues/10107
had to change the metadata and add an array relationship, so unfortunately this won't work on the netlify deploy. 
go to `/moped/dev/lookups#moped-components` and see the components with subcomponents. 
---
> Add components to lookups view

- moped-database/metadata/tables.yaml
- moped-database/migrations/1662486549080_set_fk_public_moped_project_added_by/down.sql
- moped-database/migrations/1662486549080_set_fk_public_moped_project_added_by/up.sql
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/6730
- adds a foreign key relationship between the project table and the moped_users table
- adds the object relationship
- includes the userid in the project creation mutation
This PR does not backfill previous projects with who created them
Testing locally, add a new project. If you query the database, you will see added_by is `1` whereas previous projects are `null`. (Locally, we are all signed in as JD. If you want to see a different user_id, change the id on line 104 of the file src/auth/user.js, sign out and sign back in. Add a project and the new user id is there.)
There is no change to the UI but this sets the groundwork for eventually being able to search by who added a project …
> Track who creates a moped project

- moped-database/migrations/1663082078687_adds_pd_subphases_and_updates_phase_description/down.sql
- moped-database/migrations/1663082078687_adds_pd_subphases_and_updates_phase_description/up.sql
- moped-database/migrations/1663083290227_alter_table_public_moped_subphases_alter_column_subphase_order/down.sql
- moped-database/migrations/1663083290227_alter_table_public_moped_subphases_alter_column_subphase_order/up.sql
- moped-database/migrations/1663084376667_alter_table_public_moped_subphases_add_unique_subphase_name_related_phase_id/down.sql
- moped-database/migrations/1663084376667_alter_table_public_moped_subphases_add_unique_subphase_name_related_phase_id/up.sql
Resolves https://github.com/cityofaustin/atd-data-tech/issues/10069
In addition to ☝️ - I went ahead and added a few constraints to the `moped_subphases` table:
- `subphase_order` cannot be null
- `subphase_order` must be unique
- The combination of `subphase_name` + `related_phase_id` must be unique: i.e., we cannot have duplicate subphase names related to the same phase.
**URL to test:** Local or [Moped test deploy](https://10069-jc-pd-phase-updates--atd-moped-main.netlify.app/moped)
Navigate to `moped/dev/lookups` and confirm the following changes:
- subphase "Preliminary Engineering Report" exists in the "Preliminary Engineering" phase
- subphase "Bid Preparation" exists in the "Pre-Construction" phase
- subphase "Substantially Complete" exists in the …
> Adds new subphases for Project Delivery Division

- moped-editor/package-lock.json
- moped-editor/src/components/ButtonDropdownMenu.js
- moped-editor/src/views/projects/newProjectView/DefineProjectForm.js
- moped-editor/src/views/projects/newProjectView/NewProjectView.js
- moped-editor/src/views/projects/projectView/MilestoneTemplateModal.js
- moped-editor/src/views/projects/projectView/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectMilestones.js
- moped-editor/src/views/projects/projectView/SubprojectFundingModal.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/10238
https://deploy-preview-796--atd-moped-main.netlify.app/moped/projects
1. Test project creation, I removed the option to choose a type from the project workflow. No milestones should show up after a project is created
2. Navigate to the timeline tab. Open the button dropdown, select "From Template"
3. A modal should appear, with a disabled button and an autocomplete to choose templates. 
4. after choosing the AMD choice, the list should populate with preselected milestones. (PMD is still empty because we dont have the "template" listed yet) Toggling them off will not include them in the mutation. 
5. any existing milestone on the table should not show up in the modal. You can test by …
> Support timeline templates for multiple workgroups

- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/settings.js
https://github.com/cityofaustin/atd-data-tech/issues/10319
**URL to test:** [Deploy preview](https://deploy-preview-800--atd-moped-main.netlify.app/moped/projects/1824?tab=map) on Netlify.
Navigate to `/moped/dev/lookups` and verify the "Project tags" nav link is functional as well as the "Project tags" table at the bottom of the page.
---
> Adds project tags to lookups view

- moped-editor/src/queries/dashboard.js
I removed the deprecated `status_id` (old soft-delete) fields from the DB recently, and there were some queries that were still requesting them. This PR removes it from those queries to get the Dashboard view working again.
https://github.com/cityofaustin/atd-data-tech/issues/10341
**URL to test:**
This can be tested locally
1. Create a project.
2. From the project summary, verify you are following the project - the bookmark icon in the top right should be filled.
3. Add your self to the project personnel in the project **Team** tab
3. Navigate to the Dashboard page
4. Your project should be listed in both the **My Projects** and **Following** tabs
---
> Remove `status_id` from queries

- moped-editor/src/queries/dashboard.js
I removed the deprecated `status_id` (old soft-delete) fields from the DB recently, and there were some queries that were still requesting them. This PR removes it from those queries to get the Dashboard view working again.
https://github.com/cityofaustin/atd-data-tech/issues/10341
**URL to test:**
https://deploy-preview-806--atd-moped-main.netlify.app/moped/
1. Create a project.
2. From the project summary, verify you are following the project - the bookmark icon in the top right should be filled.
3. Add your self to the project personnel in the project **Team** tab
3. Navigate to the Dashboard page
4. Your project should be listed in both the **My Projects** and **Following** tabs
---
~- [ ] Added to [QA test …
> Remove status_id from queries (update `main`)

- moped-editor/src/queries/tags.js
After merging https://github.com/cityofaustin/atd-moped/pull/813#issuecomment-1268768849, I noticed that a deleted tag is still available on the autocomplete menu.
[Netlify](https://deploy-preview-816--atd-moped-main.netlify.app/moped/projects/1878) or local
1. Visit project summary page.
2. Verify you cannot add a tag named "MAP Vision Zero Intersections Potential 2023"
---
> Exclude deleted moped_tags

- moped-editor/package.json
Puts us back on v1.10.0 after #818
> Bump Main (back) to v1.10.0

- moped-database/migrations/1665180093803_remove_deleted_contracts_again/down.sql
- moped-database/migrations/1665180093803_remove_deleted_contracts_again/up.sql
- moped-database/views/project_list_view.sql
See https://austininnovation.slack.com/archives/CNUEPKLB1/p1665179295381869
TLDR:
Two migrations conflict when applying locally but applied with a regression in staging. Using the same fix as [the last time something like this happened](https://github.com/cityofaustin/atd-moped/pull/680).
**Order applied in staging**
1. `1664467952757_remove_deleted_contracts_from_project_view` patched soft deleted contractors from returning from the view
2. `1664402014381_add_project_tags_to_view` added project tags to view but also reintroduced soft deleted contractors to the returned data
**Order applied locally**
1. `1664402014381_add_project_tags_to_view` adds project tags
2. `1664467952757_remove_deleted_contracts_from_project_view` replaces the view with a version that doesn't have project tags and …
> Fix migration conflicts in local Hasura cluster 

- moped-toolbox/component_geo_processing/create_components_geojson.py
- moped-toolbox/component_geo_processing/settings.py
https://github.com/cityofaustin/atd-data-tech/issues/10384
Adds `moped_proj_tags` to the components geojson extracts.
Steps to test:
1. Activate a local python environment with `requests` installed
2. Start local Moped DB and editor
3. Create a project with a few different component types e.g. Buffered bike lane and signals
4. Add Tags to the project.
5. Run the script `python create_components_geojson.py -e local`
6. Locate the `points` and `lines` geojson files in the `_output/` directory.
7. Search the output geojson to verify that the projects' tags are populated in the `moped_proj_tags` property.
8. You can upload these to [geojson.io](https://geojson.io/) to inspect the results.
9. Optionally, add `staging` or `prod` entries to `secrets.py` to process data against those …
> Updates component geojson extract to include project tags

- moped-editor/src/views/dashboard/DashboardView.js
I was opening an issue regarding a bug i found in the team table, and spotted this snackoo. 
https://github.com/cityofaustin/atd-data-tech/issues/10463
https://deploy-preview-827--atd-moped-main.netlify.app/moped/dashboard
Check out your dashboard. If you have fewer than 15 projects, you wont see pagination. But once it goes over 15, pagination appears with the option to increase the count to 30 or 100. 
I arbitrarily chose the number 15 as the minimum count, on the signals dashboard thing we have it as 30. 
---
> Increase number of default rows in dashboard 

- moped-editor/src/components/GridTable/GridTableFilters.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/10289
https://deploy-preview-804--atd-moped-main.netlify.app/
go to projects list view, click filter button, you should see an empty field. add a filter, search, delete a filter.
---
> Automatically show blank advanced search filter

- moped-editor/src/views/projects/projectView/DeleteConfirmationModal.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/10292
fixes https://github.com/cityofaustin/atd-data-tech/issues/10318
https://deploy-preview-815--atd-moped-main.netlify.app/
go to a project, add a comment, and click the delete icon. click cancel. click the delete icon again and click delete.
repeat the previous step on the project summary page for a project tag.
i created a reusable modal component that we should be able to implement in other places we want a delete confirmation modal. the only issue is that the delete icon on the project comments and the delete option on the chip on project tags act very differently, so the solution is not as elegant as i was hoping it would be, with a few conditionals and implementing the tag chip inside …
> Adds a delete confirmation modal to project tags and comments

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/9525
https://deploy-preview-838--atd-moped-main.netlify.app/moped/projects/1841
This is a deleted project: 
https://deploy-preview-838--atd-moped-main.netlify.app/moped/projects/1841 
~~You should see a banner above projects that have been deleted, no banner or empty space seen on normal projects.~~
There is now a dialog that pops up to inform you the project has been deleted. with a link to take you back to all projects. 
---
> Show alert banner on deleted projects

- moped-editor/src/views/projects/projectView/ProjectComponents/BasemapSpeedDial.js
- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
https://github.com/cityofaustin/atd-data-tech/issues/10405
This is best tested locally since the Netlify preview links are not on the approved list for the Moped NearMap token
1. Go to an existing or new project's **Map** tab
2. Using the speed dial, select the aerial basemap
3. You should see the NearMap tiles pulling in with the Mapbox street labels presented on top
4. You can also try a viewport 990px or below and see that the speed dial moves above the Mapbox info icon that now it appears on the aerial view since we are using their street labels.
---
> Add street labels over nearmap aerial imagery (#4)

- moped-editor/src/views/projects/projectView/ProjectTeamRoleMultiselect.js
- https://github.com/cityofaustin/atd-data-tech/issues/10609
**URL to test:**  [Deploy preview](https://moped.austinmobility.io/moped/projects/1720?tab=team)
1. Navigate to the Team tab of any project.
2. Add a team member
3. Edit the team member roles and observe:
- the drop-down menu is 50% of the screen width and is horizontally centered under the "Role" column
- when unfocused, the input menu has linebreaks between the selected role options
---
> Use wider team role select menu

- moped-editor/src/views/projects/projectView/ProjectTeamRoleMultiselect.js
The `ProjectTeamRoleMultiselect` component had conflicting props:
```
Material-UI: You can not change the default `anchorOrigin.vertical` value 
when also providing the `getContentAnchorEl` prop to the popover component.
Only use one of the two props.
Set `getContentAnchorEl` to `null | undefined` or leave `anchorOrigin.vertical` unchanged. 
```
Discussion [here](https://github.com/mui/material-ui/issues/7961#issuecomment-326215406).
> Fixes an MUI warning about conflicting menu props

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentEditModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils.js
https://github.com/cityofaustin/atd-data-tech/issues/10541
Adds icons to the component type options to show if they represent point or line geometries
Test locally
1. Go to a new or existing project's **Map** tab
2. Click **New Component** and then click on the **Component Type** dropdown
3. You should see an icon before each option label
---
> Add an icon to indicate if the component supports line or point geometry

- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/agolUtils.js
- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapStyleSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapUtils.js
https://github.com/cityofaustin/atd-data-tech/issues/10402
This PR updates the component draft mode to capture geometry from the same AGOL data that is populated in the map to show what lines and points are available to add to a component. Previously, we grabbed that geometry from a click event in the map library which led to the possibility of clipping geometries. Now, we click a feature, get the feature's unique ID, and then find the record within the features returned from AGOL to use its geometry and properties to eventually persist the component.
https://md-10402-clipped-geojson--atd-moped-main.netlify.app/moped/
**This PR update doesn't change the way the UI works so this is mostly verifying that points and lines are still selectable.**
1. Go to …
> Work around Mapbox's clipped geojson features (#6)

- moped-editor/src/components/Maps/ComponentsDrawControl.js
- moped-editor/src/styles/mapboxDrawStylesOverrides.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentDrawTools.js
- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/agolUtils.js
- moped-editor/src/views/projects/projectView/ProjectComponents/featureUtils.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapStyleSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapUtils.js
https://github.com/cityofaustin/atd-data-tech/issues/10403
Adds the draw tools to the components map refactor
Questions/concerns:
- there is some cross-activity when clicking a segment or point from CTN layers near a drawn line or point (capture below). The `clickBuffer` parameter of the draw tools could be updated to avoid this but I also don't want to make it super hard to click drawn features if we drop that too low.
https://md-10403-draw-tools--atd-moped-main.netlify.app/moped/ or test locally
1. Go to a new or existing project's **Map** tab and then click **New Component**
2. Choose component type **Access Control - Driveway Closure**
3. Zoom until you see the dashed lines of the CTN layer
4. Click the line drawing icon in the top right just above …
> Re-implement map draw tools

- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/index.js
- moped-editor/src/views/dev/LookupsView/settings.js
https://github.com/cityofaustin/atd-data-tech/issues/10740
This PR adds `moped_entities` to the data dictionary page, and it also adds an awkward icon button next to each table header which will take you back to the top nav. 
We clearly need to rethink the design of the data dictionary. Some ideas for improvement:
- Use a persistent sidebar nav (like Gitbook) to make it easy to navigate
- Make use of our comments in the DB schema itself to display definitions of tables and fields
- Make it clear to users where these values are used. E.g., the `moped_entities` column is reference by Lead, Sponsor, and Partners, but users will have no idea that's the case.
☝️ i'll put all that in a separate issue
**URL to test:** [Deploy preview](https://deploy-preview-853--atd-moped-main.netlify.app/) …
> Adds Entities to data dictionary

- .gitignore
- moped-toolbox/backfill_added_by/run.py
- moped-toolbox/backfill_added_by/secrets_template.py
https://github.com/cityofaustin/atd-data-tech/issues/10724
This script populates a project's `added_by` column based on the cognito user ID captured in the activity log. There's a grab bag of edge cases which are not covered, but are documented in the code. 
~In production, there will be 40 projects for which we cannot automatically find the `added_by` user ID. We can refine this script to use other project data to determine the author, or we can fix these projects manually/ad-hoc. I decided to leave it outside the scope of this script for now.~
Edit: after [some sleuthing](https://austininnovation.slack.com/archives/CNUEPKLB1/p1667967766423399?thread_ts=1667944441.541699&cid=CNUEPKLB1), we'll have just 3 projects in prod for which we cannot automatically assign an `added_by` value. 
The …
> Create script to backfill who created a project

- moped-toolbox/backfill_added_by/run.py
I uncovered a bug when i ran this against the staging database - i was not properly extracting a user ID from a `moped_user` object.
I ran this locally against the staging DB and it worked.
> Patches added_by backfill script

- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryLabel.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectEntity.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectPartners.js
https://github.com/cityofaustin/atd-data-tech/issues/10749
Maybe not the most elegant solution, but this addresses a frequent request from users to add definitions to these fields, particularly now that we also have a project lead.
I also experimented with helper text on the form inputs, but this would require some refactoring, particularly for the partners field. I think my preference would be that these definitions are persistent in fine print on the page at all times rather than on hover.
**URL to test:** [Deploy preview](https://deploy-preview-867--atd-moped-main.netlify.app/)
1. Navigate to the project summary page
2. Hover your mouse over the lead, sponsor, and partners field inputs and observe the tooltip appears with a definition of the field:
- **Lead**: …
> Add tooltips to project summary fields to define lead, sponsor, and partners

- moped-toolbox/backfill_project_lead/run.py
- moped-toolbox/backfill_project_lead/secrets_template.py
https://github.com/cityofaustin/atd-data-tech/issues/10747
This script sets the new `moped_project.project_lead_id` column based on the user who created a project. Because user workgroups do not map cleanly to `moped_entity`, I hardcoded the workgroup <> entity mapping within the script.
The script outputs `log.json` which identifies the reason we cannot update a given project. There will be three projects that cannot be processed due to the project having a null `added_by` column. 
**URL to test:** local
1. Start the hasura cluster and editor
2. Open the Hasura console (`localhost:8080`) and manually edit project ID `174` by setting `added_by` to user ID `27` (Ivonne)
3. Activate a python env with `requests` installed
4. Navigate to …
> Backfills project lead from project creator's workgroup

- moped-editor/src/layouts/DashboardLayout/TopBar.js
https://github.com/cityofaustin/atd-data-tech/issues/10786
Test locally and [deploy preview](https://deploy-preview-878--atd-moped-main.netlify.app/).
Verify the alert banner displays.
---
> Always show dev environment alert banner except in production

- moped-editor/src/queries/signals.js
https://github.com/cityofaustin/atd-data-tech/issues/7910
1. Start the cluster and editor as usual
2. Navigate to the signals dashboard: `https://localhost:3000/moped/views/signal-projects`
3. Observe that the page loads and there is one project in the table
---
> Remove status_id filters from signals query

- moped-editor/src/layouts/DashboardLayout/DashboardLayout.js
- moped-editor/src/layouts/DashboardLayout/TopBar.js
https://austininnovation.slack.com/archives/CNUEPKLB1/p1668810204891789
Punting on an environment-specific favicon - but this adds an orange banner in local and shows the env name in the banner.
URL to test: Local and [Netlify](https://deploy-preview-886--atd-moped-main.netlify.app/moped/projects)
Steps to test:
1. Check it out
> Use an alert banner component and fix padding in local env

- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/map.js
https://github.com/cityofaustin/atd-data-tech/issues/10426
This PR updates the components map to zoom to a bounding box that has all of a project's component features within. If there are no existing components, the map initializes to its default coordinates and zoom.
https://md-10426-zoom-on-load--atd-moped-main.netlify.app/moped/
1. Go to https://md-10426-zoom-on-load--atd-moped-main.netlify.app/moped/projects/156?tab=summary
2. Go to the **Map** tab and you should see the map zoom to the existing components
3. You can also create a new project to see the default zoom, add some components, and then leave and revisit the **Map** tab to see the zoom on load
---
> Set initial map extent from existing project components

- moped-database/docker-compose.yml
_none_
Our version of `graphql-engine` is getting a little long in the tooth @ 3 months old. I'd like to bump the version up to the latest and greatest while that change is still pretty small and easy to digest. 
This PR, while including a change to the local environment, is really a stand-in for the small change in the AWS configuration that will bring our ECS cluster up to date by updating the docker image that is run. Approving this PR indicates your support for moving forward with that update.
Unless anyone is opposed, I'd like to make the change to the staging ECS cluster, so it can be tested as part of the next moped formal testing. @johnclary, I'll touch base with you tomorrow after this has a day to simmer to see if that's suitable.
Local testing for this one. To test, fire up the …
> bump local graphql-engine version

- moped-database/migrations/1668918049780_set_fk_public_moped_user_followed_projects_project_id/down.sql
- moped-database/migrations/1668918049780_set_fk_public_moped_user_followed_projects_project_id/up.sql
- moped-database/migrations/1668918080369_set_fk_public_moped_proj_contract_project_id/down.sql
- moped-database/migrations/1668918080369_set_fk_public_moped_proj_contract_project_id/up.sql
- moped-database/migrations/1668918144295_set_fk_public_moped_proj_tags_project_id/down.sql
- moped-database/migrations/1668918144295_set_fk_public_moped_proj_tags_project_id/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/10848
1. Start the hasura cluster normally
2. Rollback this PR's migrations:
```shell
$ hasura migrate apply --down 3
````
3. In a SQL client, or through the console at `localhost:8080` - try to delete all projects. this should fail:
```sql
DELETE FROM moped_project WHERE 1=1;
````
5. Apply `up.sql` for each migration. You can try to delete projects each time you apply one of the migrations. This operation will fail until you've run all three migrations.
```shell
$ hasura migrate apply --up 1
```
I hope those steps make sense!
---
> Cascade project deletes on tags, contracts, and followed projects

- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/10671
this fixes the bug where the column sorting icon on the projects list view only appeared on hover. it's also a step toward completing https://github.com/cityofaustin/atd-data-tech/issues/10538
in order to do this, i had to hardcode a default sorting order, so i used  the existing default (descending by date modified) set `ProjectsListViewQueryConf`. ultimately, we would populate the new default using url parameters from the previous session. i thought it made sense to always have a column sorted since this is what it will ultimately be like when the sorting is persistent. also, it used to be that if you click a column name a third time, the arrow disappears and the table is sorted back to default. i thought this was …
> sets default project list sort and displays arrow

- moped-etl/prefect/moped_test_create_flow.py
- moped-etl/prefect/tasks/ecs.py
https://github.com/cityofaustin/atd-data-tech/issues/10600
and a bonus! https://github.com/cityofaustin/atd-data-tech/issues/10887
associated moped PR: https://github.com/cityofaustin/atd-moped/pull/883
associated prefect PR: https://github.com/cityofaustin/atd-prefect/pull/42
I need to add the endpoint for the graphql requests for the REST connector to work. 
https://cloud.prefect.io/dts/flow/7672e429-8787-45ba-8406-6e01fef0d416
---
> Add graphql endpoint variable to task definition

- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
https://github.com/cityofaustin/atd-data-tech/issues/10885
https://deploy-preview-890--atd-moped-main.netlify.app/moped/
- go to project list view, you should see 100 projects displayed sorted in descending order by date modified
- click the page forward button to see the rest of the records
- click a different column header, the table should rerender on page 1 with the top 100 records that match the column you clicked, in descending order
- go to the next page, you should see the remaining records according to the sort you applied
- reverse the sort, you should be taken back to the top 100 records (page 1) in ascending order according to the header you clicked
---
> sets project list view paging to 100

- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/10751
this pr moves the delete confirmation modal out of the scope within which tags, comments and status updates are iterated
https://deploy-preview-896--atd-moped-main.netlify.app/
- add five or more tags to any project
- delete one of the tags
- the delete confirmation modal background should be a normal opacity
- delete the tag and confirm the correct tag was deleted
- the opacity should not change as you delete tags
- repeat this step on the comments tab and in the status update modal (adding multiple comments/updates and deleting them)
---
> renders only one delete modal

- moped-database/docker-compose.yml
- moped-etl/prefect/tasks/ecs.py
Our test instances are lagging behind local, staging, and prod. I'm also hoping this clears an issue where Hasura occasionally crashes after replacing metadata.
I also noticed that we don't define a health check, which I think will help the container service restart more quickly if it fails. We don't use autoscaling, but I think the health check is a precursor for auto scaling.
[This test instance](https://4838-jc-migrate-access-db--atd-moped-main.netlify.app/moped/projects) is running these changes.
i need to learn from Chia + Frank on how to test this. 
---
> Bump Hasura test instances to v2.15.1

- moped-editor/src/components/FileUpload/FileUploadDialogSingle.js
- moped-editor/src/views/projects/newProjectView/DefineProjectForm.js
- moped-editor/src/views/projects/projectView/CommentInputQuill.js
- moped-editor/src/views/projects/projectView/ProjectContractsTable.js
- moped-editor/src/views/staff/StaffForm.js
- https://github.com/cityofaustin/atd-data-tech/issues/9144
[Netlify](https://deploy-preview-904--atd-moped-main.netlify.app/moped/projects)
Observe the input autofocusing in these places:
1. New project form: project name
2. New contract row in contracts table: contractor column
3. File upload - file name
4. Comments (from Dashboard, project summary, or comments tab): the comment input
5. Add/edit staff form: first name
I tried to apply autofocus in these two places, but it just wouldn't take (despite using patterns we have elsewhere):
- ❌ Milestones table
- ❌ Funding table
---
> Adds autofocus to various form inputs

- moped-editor/package-lock.json
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryParentProjectLink.js
Fixes cityofaustin/atd-data-tech/issues/10754
https://deploy-preview-909--atd-moped-main.netlify.app
1. Go to the project summary page for a new or existing project that has a parent project.
2. Ensure that the parent project field is now aligned with the rest of the fields.
3. Update the description and website fields to have very longgggggggg strings. The strings should now break and wrap when not editing.
---
> Enhancements to project summary fields

- moped-database/schemaspy/generate-pk-map.py
Our DB docs github action is failing. Technically, the docs are actually being deployed successfully, but the secondary step of generating a primary key map is failing, here: https://github.com/cityofaustin/atd-moped/actions/runs/3802004783/jobs/6467061851.
Note that we'll be able to deprecate this primary key map once we completely migrate our activity log to REST connectors.
- None :/ 
1. Start the Hasura cluster
2. From a python environment with `requests` installed, run the python script
```shell
$ python generate-pk-map.py
```
3. The script will print a JSON string of all Moped table names with each table's primary key column name.
```python
{"moped_activity_log": "activity_id", "moped_city_fiscal_years": "id", "moped_components": …
```
> Repairs db-docs build action

- moped-editor/package-lock.json
- moped-editor/package.json
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectComponents.js
- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeFeatureCollections.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/map.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMapFallback.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMapSourcesAndLayers.js
https://github.com/cityofaustin/atd-data-tech/issues/10995
https://github.com/cityofaustin/atd-data-tech/issues/10689
This PR updates the project summary map to show features that come from the `project_geography` view. I also updated the map to use some of the same config and patterns as the components map. I removed the `ErrorBoundary` component from the summary view since it isn't a pattern that we've used elsewhere in the app. Definitely up for debate because having those can be handy, but I think that if we remove it then I should remove the package for it as well.
local or https://md-10995-summary-map--atd-moped-main.netlify.app/moped/
1. Create a new project and, when you reach the summary page, notice that the fallback component with the map …
> Re-implement project summary map

- moped-editor/package-lock.json
- moped-editor/package.json
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectComponents.js
- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/features.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeFeatureCollections.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useUpdateComponent.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMapFallback.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMapSourcesAndLayers.js
https://github.com/cityofaustin/atd-data-tech/issues/10991
This PR updates the edit component map flow to enable removing all features from a component and to disable the **Save Edit** button when that happens. The button enables again when another feature is added.
local or https://md-10991-prevent-save--atd-moped-main.netlify.app/moped/
1. Create a new project and then add a new line or point component
2. Add some features and then save it
3. Edit the component that you just created and delete every feature by deselecting or using the trash can on drawn features
4. You should see the **Save Edit** button disable when you have no features left
5. Select a feature from the map or drawn one
6. The **Save Edit** button should be enabled again and you can …
> Prevent saving of map edits if there are no map features

- moped-database/metadata/tables.yaml
- moped-database/migrations/1672772477585_alter_table_public_moped_proj_notes_add_column_phase_id/down.sql
- moped-database/migrations/1672772477585_alter_table_public_moped_proj_notes_add_column_phase_id/up.sql
- moped-database/migrations/1672851579949_set_fk_public_moped_proj_notes_phase_id/down.sql
- moped-database/migrations/1672851579949_set_fk_public_moped_proj_notes_phase_id/up.sql
- moped-editor/src/queries/comments.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/dashboard/DashboardStatusModal.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectStatusBadge.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/10679
fixes https://github.com/cityofaustin/atd-data-tech/issues/11082
this pr stores the current phase of a project in the `moped_proj_notes` and table and displays it next to the associated status update or project comment. next pr will allow users to edit the associated phase!
[10679_relate_project_notes_to_current_phase--atd-moped-main.netlify.app/moped/](https://10679_relate_project_notes_to_current_phase--atd-moped-main.netlify.app/moped/)
- create a new project
- add a status update named 'potential' (for easier tracking during testing)
- the new status update should appear with the 'potential' badge next to it (the modal will close automatically)
- add a comment with the same name
- the …
> relates project notes to current phase and displays badge

- moped-editor/src/queries/dashboard.js
- moped-editor/src/views/dashboard/DashboardView.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
This PR does two things:
1. Fixes a bug where `phase_id` was not being set for notes added through the dashboard status modal
2. Causes the note's status badge to be hidden if the note has no `phase_id`. See discussion about that [here](https://austininnovation.slack.com/archives/CNUEPKLB1/p1672929622935829).
**URL to test:** [Netlify](https://deploy-preview-929--atd-moped-main.netlify.app/moped/projects) or local
1. Navigate to a project that has comments and a current phase, e.g. project ID [1700](https://deploy-preview-929--atd-moped-main.netlify.app/moped/projects/1700?tab=comments)
3. On the comments tab, observe that the status badge does not render for comments created before January 2023
4. Add a comment to the project - observe that the comment's status badge …
> Hides the note status badge if it has no `phase_id`

- moped-editor/src/queries/dashboard.js
This is a follow-up patch to https://github.com/cityofaustin/atd-moped/pull/929#pullrequestreview-1237676588
**URL to test:** [Netlify](https://deploy-preview-930--atd-moped-main.netlify.app/) or local
1. Follow a project who's current phase is not "Unknown".
2. Navigate to the dashboard view and switch to the "Following" tab of the projects table. Click into the status column to add a status update.
3. Click back into the status update modal to verify that the status you created renders with a status badge that matches the project's status badge.
> add phase_id to dashboard summary query

- moped-database/metadata/tables.yaml
- moped-database/migrations/1672415599589_set_note_added_by_user_id/down.sql
- moped-database/migrations/1672415599589_set_note_added_by_user_id/up.sql
- moped-database/migrations/1672420074371_set_fk_public_moped_proj_notes_added_by_user_id/down.sql
- moped-database/migrations/1672420074371_set_fk_public_moped_proj_notes_added_by_user_id/up.sql
- moped-editor/src/queries/comments.js
- moped-editor/src/queries/dashboard.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
- https://github.com/cityofaustin/atd-data-tech/issues/9644
Here's another patch I want to get squared away ahead of the access migration.
**URL to test:** Local only 
To test the migrations:
1. Follow all the steps to [load production](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/how-tos/how-to-load-production-data-into-a-local-instance) data into your local instance.
2. Connect to the prod read replica, and observe that `added_by_user_text` and  `added_by_user_name` do not match when you run this query:
```sql
select mpn.project_note_id, mpn.date_created, mpn.added_by as added_by_user_text, mu.first_name || ' ' || mu.last_name as added_by_user_name
from moped_proj_notes mpn
left join moped_users mu on mpn.added_by_user_id = …
```
> Normalize project notes author tracking

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
https://github.com/cityofaustin/atd-data-tech/issues/11124
This PR disables the **Continue** (or **Save** when creating a signal component) button in the modals that appears when creating a new component or when editing an existing component's attributes.
Button is disabled when:
- form does not have required fields complete
- for non-signal components: the component type field is required
- for signal components: the component type and signal fields are required
- the edit attributes modal is open but no edit has been made yet
local for now
1. Go to a new or existing project's **Map** tab
2. Click **New Component** and notice that the **Continue** button in the modal is greyed out and you can't click it
3. Add a Description and notice that the button …
> Disable "Continue" button when the create component form isn't complete

- moped-toolbox/populate_geometry_transform/Dockerfile
- moped-toolbox/populate_geometry_transform/README.md
- moped-toolbox/populate_geometry_transform/docker-compose.yml
- moped-toolbox/populate_geometry_transform/transpose_geometry.py
- In service of https://github.com/cityofaustin/atd-data-tech/issues/11186
- adds special handling of `feature_signals` features which no longer have a `source_layer` or `project_extent_id` column
- excludes deleted `moped_proj_features` from processing. a few of these were throwing errors due to corrupted geometries. i think it's safe to just exclude them but i'm curious what y'all think
- makes a small change to the Dockerfile and compose which was giving me problems when trying to mount a volume with `docker run`
- adds a short README for running the script with `docker run`. 
- See [readme](https://github.com/cityofaustin/atd-moped/blob/6341232d7000208e445a8a44ac88a60e78c4d767/moped-toolbox/populate_geometry_transform/README.md)
---
> Patches transpose geomtery script to align with front-end changes

- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useUpdateComponent.js
- https://github.com/cityofaustin/atd-data-tech/issues/11231
**URL to test:**  Local or [Netlify](https://deploy-preview-943--atd-moped-main.netlify.app/) 😎 
1. Create a bike lane component
2. Click on the component in the sidebar, then click the "edit" button
3. When the "What do you want to edit?" dialog opens, close it (or click away) without selecting "attributes" or "map"
4. Click anywhere on the map to "unfocus" from this component
5. Observe that you can still see this component on the map ✅ 
---
> Reset draft component on exit edit mode dialog

- moped-editor/src/views/projects/projectView/ProjectComponents/mapStyleSettings.js
We currently have four map feature colors:
- Default / not editing: `#fc0885` 
- Focused component / still not editing: `#1276D1`
- Focused component + editing: `#ffb300`
- Not focused / not being edited components: `#a6a2a2`
When not editing, I don't think we should use a distinct color for focused vs not focused. It's a bit confusing. As much as I love `#fc0885`, i think we can nix it and just use our primary blue. This PR switches things like so:
- Default / not editing: `#1276D1`
- Focused component / still not editing: `#1276D1`
- Focused component + editing: `#ffb300`
- Not focused / not being edited components: `#a6a2a2`
**URL to test:**  [Netlify](https://deploy-preview-945--atd-moped-main.netlify.app/)
1. Create a bunch of point and line components.
2. Focus, …
> Simplify map color styles

- moped-database/metadata/tables.yaml
- moped-editor/src/utils/activityLogFormatters/mopedPartnersActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
this pr updates the activity log to use REST connectors for 'project partners' activity log updates. it also updates the formatting of how these updates are displayed in the activity log.
fixes https://github.com/cityofaustin/atd-data-tech/issues/11167
[11167_refine_partners_activity_log_events--atd-moped-main.netlify.app/moped/](https://11167_refine_partners_activity_log_events--atd-moped-main.netlify.app/moped/)
- go to a project summary page
- add one or more project partners using the dropdown
- check the activity log to see that the activity is reflected (you may have to refresh the page)
- repeat the previous steps by deleting one or more project partners
- repeat the previous steps by adding one or more new partners and removing one or more …
> updates project partner activity log entries

- moped-database/metadata/tables.yaml
- moped-editor/package.json
- moped-editor/src/queries/project.js
- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
this pr adds 'public process status' to the activity log. merging this pr will update the [10833_public_process_field_ui](https://github.com/cityofaustin/atd-moped/tree/10833_public_process_field_ui) branch, which will then be ready to merge into main. i'm keeping the standard moped project update icon for this update in the activity log since this is somewhat intangible.
fixes https://github.com/cityofaustin/atd-data-tech/issues/11255
https://11255_add_public_process_status_to_activity_log--atd-moped-main.netlify.app/moped/
- go to a project summary page and add a public process status
- go to the activity log and refresh to see the update
- remove the public process status and note the change in the activity log
---
> adds public process status to activity log

- moped-database/metadata/tables.yaml
- moped-editor/package-lock.json
- moped-editor/src/queries/project.js
- moped-editor/src/utils/activityLogFormatters/mopedMilestonesActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
https://github.com/cityofaustin/atd-data-tech/issues/11092
https://deploy-preview-950--atd-moped-main.netlify.app/moped/projects/1912?tab=activity_log
From the timeline tab, add a new milestone to a project. "Added a new milestone: Cabinet set"
Edit a milestone's fields, you should the fields listed out, like:  "Edited a milestone's completion, description"
Delete a milestone. 
you may notice that what is presented here in the activity log doesn't match what John's mockups are in the issue. I've refactored the activity log work to look more like what the issues are requesting. That PR is here: https://github.com/cityofaustin/atd-moped/pull/949
---
> Use REST connector endpoint for project milestones

- moped-editor/src/utils/activityLogFormatters/mopedFundingActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedMilestonesActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedPartnersActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedTagsActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityEntry.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
No specific issue per se, but looking at activity log issues like the milestones one (https://github.com/cityofaustin/atd-data-tech/issues/11092), the current way in main to represent activity log updates, i.e., changeDescription and changeValue, was limiting how updates could be formatted. 
This refactoring doesn't tie us down to only two strings and opens the door for more flexibility. 
also this https://github.com/cityofaustin/atd-data-tech/issues/11233 (ecapris is stored as a number, and you cant find the lengths of numbers)
Test locally until its parent PR (milesontes) is approved and merged. 
This updates all of the existing activity log formatters
* funding
* milestones
* partners
* project
* tags
Add / edit / delete records on the funding …
> Refactor activity log text formatting

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/project.js
- moped-editor/src/utils/activityLogFormatters/mopedPhasesActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
this pr refines phases and subphase activity log events using REST connectors
fixes https://github.com/cityofaustin/atd-data-tech/issues/11279
https://deploy-preview-953--atd-moped-main.netlify.app/moped/
- add, edit and remove a phase with a subphase and a phase without a subphase while noting the activity log updates
- the changes should be reflected in the activity log with the subphase listed where appropriate
Create event
```markdown
Added **<phase-name> - <subphase-name-if-exists>** as a new phase
```
Edit event
```markdown
Edited the phase **<phase-name> - <subphase-name-if-exists>** by updating the <comma-separated-field names>
```
Delete event 
```markdown
Removed the phase **<phase-name> - <subphase-name-if-exists>**
```
---
> refines project phases activity log events

- moped-editor/src/views/projects/projectView/CommentInputQuill.js
- moped-editor/src/views/projects/projectView/ProjectComments.js
https://github.com/cityofaustin/atd-data-tech/issues/11126
This PR updates the `CommentInputQuill` component to set the style of text in it React Quill text box. It was previously inheriting from MUI styles which led to inconsistent styling depending on its wrapper.
https://deploy-preview-951--atd-moped-main.netlify.app/moped/
1. Go to the following places to create or edit a comment or status update and make sure the input text color matches our [`theme.palette.text.primary` color](https://www.google.com/search?q=%23212121):
- Project summary > Status update
- Project summary > Comments tab > New comment
- Project summary > Comments tab > Edit existing comment
- Dashboard > My Projects > Status update
- Dashboard > Following > Status update
---
> Fix comment edit style

- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryKnackDataTrackerSync.js
https://github.com/cityofaustin/atd-data-tech/issues/11224
The project summary UI wasn't always updating after a project was sync'd with Knack successfully and opened the door to duplicate syncs after the first one succeeded. It seems that, in the original chaining, sometimes the code would move forward to the `refetch` call before the mutation to update the project completed. The `refetch` would return stale data and miss the update, and the UI would not reflect the accurate Knack sync state.
This updates the promise chaining to refetch data and show the snack bar only after the Moped record successfully updates and after the Knack update request succeeds. I know, it is a mouthful. 😅 
Local only 💻 
1. Use the same test steps from …
> Moped projects being duplicated in the Data Tracker

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/project.js
- moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedMilestonesActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedPhasesActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
this pr refines components activity log events using REST connectors.
note: reflecting component feature changes in the activity log is outside the scope of this issue, that will be addressed in the future.
fixes https://github.com/cityofaustin/atd-data-tech/issues/10806
https://deploy-preview-954--atd-moped-main.netlify.app/
- add, edit and remove a component while noting the activity log updates
- the changes should be reflected in the activity log
---
> refines project components activity log events

- moped-database/metadata/tables.yaml
- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
https://github.com/cityofaustin/atd-data-tech/issues/11281
I also used this PR to fix the "record_id" that is being stored in activity log entries. John pointed out that I was using the project_id as the record_id when really it should be the id of the record that is being updated/changed. 
https://deploy-preview-965--atd-moped-main.netlify.app/moped/projects/1866?tab=activity_log
You can see the updated activity log entry in the link above. 
To test, add a signal and click the synchronize with data tracker link from the summary page. 
---
> [Enhancement] Update activity log formatting for Knack project ID

- .github/workflows/atd_moped_api.yml
- .github/workflows/atd_moped_build_stage.yml
- .github/workflows/atd_moped_cloudfront_cognito.yml
- .github/workflows/atd_moped_cognito_hooks_build.yml
- .github/workflows/atd_moped_database.yml
- .github/workflows/atd_moped_db_docs.yml
- .github/workflows/atd_sqs_activity_log.yml
- https://github.com/cityofaustin/atd-data-tech/issues/10631
You can read  [here](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/) about why this change is needed.
I do not know how to test this :/  
You can browse the release notes:
- [actions/checkout@v3 ](https://github.com/actions/checkout/releases/tag/v3.0.0)
- [actions/setup-python@v4](https://github.com/actions/setup-python/releases/tag/v4.0.0)
What do y'all think about merging to main yolo-style? 
---
> Bump checkout and python-setup actions to node16-based versions

- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/map.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useCreateComponent.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useUpdateComponent.js
https://github.com/cityofaustin/atd-data-tech/issues/11241
This PR updates the map to pan and zoom to the features of signal and non-signal components when saving on create or edit. I used the same padding that was used for the zoom that happens when you click on a list item's magnifier icon. That felt right, but open to any feedback on all of this. 🙏 
https://deploy-preview-970--atd-moped-main.netlify.app/moped/
1. Add a line or point component (that isn't a signal component) to a project
2. Select or draw some points or lines, drag the map away from the features, and then save
3. The map should zoom to the features in your newly created component
4. Create a signal component (PHB or Traffic) and save
5. The map should zoom to the location of the …
> Zoom to new components after create or edit

- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/signalProjectTable/RenderSignalLink.js
I was wrong to remove project name wrapping in the first place. I surrender 🏳️
- https://github.com/cityofaustin/atd-data-tech/issues/11500
**URL to test:**  [Netlify](https://deploy-preview-981--atd-moped-main.netlify.app/moped/session/signin)
1. Create a project with a very long name. See name wrap in project list.
2. To test the column config, use your debug console to delete the `mopedColumnConfig` from local storage.
3. Confirm the default visibility matches [here](https://github.com/cityofaustin/atd-data-tech/issues/11500).
---
> Wrap project name in project list and change default visible columns

- moped-editor/src/utils/activityLogFormatters/mopedFundingActivity.js
- https://github.com/cityofaustin/atd-data-tech/issues/11560
AMD raised a question about this during our most recent demo. IIRC Chia had suggested we implement this in the first place but I said no there's no time.
**URL to test:** [Netlify](https://deploy-preview-986--atd-moped-main.netlify.app/)
1. Add a funding source to a project with the "Source" column populated.
2. Edit the funding source amount.
3. Verify the activity log renders the edit by including the name of the funding source you selected.
4. Repeat, but populate the "Program" column instead of the "Source" column.
---
> Show fund source or program in activity log funding edits

- moped-database/config/.gitignore
- moped-editor/src/queries/project.js
- moped-editor/src/utils/activityLogFormatters/mopedProjectTypesActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-toolbox/backfill_user_id/run.py
- moped-toolbox/backfill_user_id/secrets_template.py
https://github.com/cityofaustin/atd-data-tech/issues/11513
Before the activity log refactor, we used to associate changes with a users's Cognito ID. However when we deactivate a user, we delete their cognito ID, so the activity log ends up saying "Unknown User"
This PR backfills all of the entries with a user's ID, which doesn't get deleted even when a user is deactivated. When I was testing against prod data locally, I found 4 cognito IDs that are not in the prod database. I went through the logs and tracked who the IDs belong to so we can backfill those in prod. 
Any missing IDs in staging will just stay as "Unknown User". 
While I was testing I found a WSOD bug on one of the projects.  (https://mobility.austin.gov/moped/projects/216?tab=activity_log) I patched that in this PR. 
**URL …
> Script to add moped user ID to old activity log entries

- moped-editor/src/queries/components.js
This patches a small regression that happened when we merged John, Tilly, and my code that touched the project components queries. Existing phases are not showing properly because the components query wasn't fetching that data to populate the form.
1. Go to https://moped.austinmobility.io/moped/projects/1924?tab=map and edit the attributes of **Bike Lane - Climbing** component
2. It will seem like there is not a component phase (the switch is off) but there are values for phase, subphase, and completion date in the database
3. Go to https://deploy-preview-989--atd-moped-main.netlify.app/moped/projects/1924?tab=map and edit the same component's attributes
4. You will see that it has an existing phase, subphase, and completion date
- Planned
- Study in …
> Patch regression in components query to show existing component phases

- moped-database/metadata/tables.yaml
fixes https://github.com/cityofaustin/atd-data-tech/issues/10809
local! since you need to access the hasura console to test. this one is a little tricky to test since these changes are only reflected in the `moped_activity_log` table, so i've included detailed testing instructions below.
this pr adds activity log tracking for project features. here are the tables and how to test them!
`feature_drawn_lines`
- create and save a project line feature component (e.g., bike lane - advisory)
- edit the component and click the map tool in the top right to add a line to the existing line feature
- reopen the component and delete the drawn line
- delete the component
- the `moped_activity_log` table in hasura console should show rows(s) for the actions …
> adds activity log triggers for project features

- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
I broke the project search via #992. To see for your yourself, login to staging and try to search for a project using the top nav or the search box on the project list. It will fail :/
This patch fixes the search config for `ecapris_subproject_id`.
**URL to test:** [Netlfiy](https://deploy-preview-997--atd-moped-main.netlify.app/moped/projects)
1. Put the value `7333.001` into the global search in Moped's top nav. You should see a handful of projects in the drop-down menu appear. Click on one. Great!
2. From the project list page, put the same value, `7333.001`, into the search input above the project list. Again, you should see a handful of results.
That's all 😅 
---
> Update project search to handle eCapris ID as text

- moped-database/docker-compose.yml
- https://github.com/cityofaustin/atd-data-tech/issues/11749
See the [v2.20 release notes](https://github.com/hasura/graphql-engine/releases/tag/v2.20.0) - this version includes a security patch as well.
1. Start the Hasura cluster and editor
Full testing will be captured by our v1.20 release testing.
---
> Bump hasura to v2.20.1

- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useUpdateComponent.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/11668
this took some digging to figure out but it turned out to be a one-line fix! there is a conditional in `ProjectSourcesAndLayers` which is based on a piece of state called `draftEditComponent` that filters out any layers that are currently being edited. this was filtering out the feature which the user had just edited using the edit attributes modal. this was because the command that is fired when you update features in `EditAttributesModal` (called `cancel_attributes_edit`, which lives in `useUpdateComponent`) was missing a line that sets `draftEditComponent` to `null`. adding this missing state change fixes the problem!
https://deploy-preview-1000--atd-moped-main.netlify.app/
- …
> fixes disappearing component bug

- moped-database/metadata/tables.yaml
- moped-database/migrations/1680618056213_alter_table_public_moped_milestones_add_column_is_deleted/down.sql
- moped-database/migrations/1680618056213_alter_table_public_moped_milestones_add_column_is_deleted/up.sql
- moped-editor/src/queries/project.js
- moped-editor/src/queries/tableLookups.js
https://github.com/cityofaustin/atd-data-tech/issues/11919
test locally
https://localhost:3000/moped/projects/227?tab=timeline
from the timeline table, select add milestone/new milestone 
check to see that you see the renamed milestones (ex "AE power complete" and "Signal turned on / asset updated") in the list of options
Also check that you do not see "Burn in period" or "Deficiency list created" or any of the other soft deleted milestones. 
---
> Add / Update milestones for new AMD templates

- moped-database/metadata/tables.yaml
- moped-database/migrations/1680198069231_drop_moped_subphase_columns/down.sql
- moped-database/migrations/1680198069231_drop_moped_subphase_columns/up.sql
- moped-database/migrations/1680199250609_add_new_subphases/down.sql
- moped-database/migrations/1680199250609_add_new_subphases/up.sql
- moped-editor/src/queries/project.js
- moped-editor/src/queries/tableLookups.js
https://github.com/cityofaustin/atd-data-tech/issues/11859
Database changes, so test locally
spin up database and editor, there are three new subphases with ids 25, 26, 27. 
checking the https://localhost:3000/moped/dev/lookups lookup page you can see one new one in potential phase and two new ones in the construction phase
---
> Add new potential and construction subphases

- moped-database/metadata/tables.yaml
fixes https://github.com/cityofaustin/atd-data-tech/issues/10525
this pr revokes hasura permissions for lookup tables. i believe i covered all of them! please let me know if i missed any or if i cut any that we should keep.
local
- i don't know that there is a good way to test this aside from looking at the tables.yaml file and confirming that the permissions that were cut all relate to lookup tables. or you can spin up the local hasura cluster and then look at the permissions we now have set for each table in the console. open to suggestions!
---
> revokes hasura permissions for lookup tables

- moped-editor/src/utils/timelineTemplates.js
- moped-editor/src/views/projects/projectView/MilestoneTemplateModal.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/11863
this pr is based on https://github.com/cityofaustin/atd-moped/pull/1009, please review that one first!
- this is best tested on a project that doesn't have any milestones
- from the timeline table, select add milestone/from template
- select 'AMD Inspection-only' and add click 'add milestones'
- you should see 8 milestones populated that match the milestones in the issue description
- delete the milestones
- add the milestones from the `AMD Signal Infrastructure` template
- you should see 13 milestones, those from the previous template plus five additional
---
> creates new AMD milestone templates

- moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/11884
this pr adds phase changes to the component activity log events. I tried to mirror the phases activity log events as closely as possible.
https://deploy-preview-1010--atd-moped-main.netlify.app/
1. add a project component and save it without a component phase
2. edit the project component and add a component phase with a subphase and completion date
3. go to the activity log to see the new entry, listing the phase, subphase and component name
4. edit the component phase to edit or remove the subphase and/or completion date
5. go to the activity log to see the updated fields listed
6. remove the component phase by clearing the toggle
7. go to the activity log to see the update
---
> adds component phases to activity log

- moped-api/files/files.py
This small patch is in service of debugging a file upload issue related to the `&` symbol in filenames. I cannot reproduce the issue locally so I'd like to add this logging to see exactly what data the lambda function is parsing.
- https://github.com/cityofaustin/atd-data-tech/issues/11900#issuecomment-1505588952
---
> Include filename in API error response

- moped-database/migrations/1681854063780_filter_deleted_projects_from_projects_list_view/down.sql
- moped-database/migrations/1681854063780_filter_deleted_projects_from_projects_list_view/up.sql
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/10582
there won't be a perceptible change since this just moves the filter that excludes deleted projects from `ProjectsListViewQueryConf` to `project_list_view`
Local (since there are database changes)
1. go the projects list view, select a project and delete it
2. go back to the projects list view, the project should no longer display
---
> Removes deleted projects from projects list view

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditModeDialog.js
I believe I have unraveled what is happening here, and I think it has something to do with the react-hook form controller. It is changing the date format into something that `parseISO` can't handle. I did a lot of console logging and used the `onAccept` function to see what the date looks like when the form is accepted. I found that parsing the date with new Date() can handle it. See our slack for more detailed explanation
https://deploy-preview-1029--atd-moped-main.netlify.app/moped/projects
add a component phase. Edit the date and save. refresh the page, edit again and it should not completely fail on you. 
---
> Prevent white screen crash when editing component phase date

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- https://github.com/cityofaustin/atd-data-tech/issues/11968
This change unbreaks [a previous patch](https://github.com/cityofaustin/atd-moped/pull/978/files#diff-be66300e240d2abb87784e0db4a1a85c1c9040251d43a82a17500c9091b4f63c) which is preventing users from selecting/editing subcomponents.
This feels a wee bit hacky, since it only works because we do not allow users to edit their component's type/subtype. If that were not the case this would be a lot harder!
**URL to test:** [Netlify](https://deploy-preview-1032--atd-moped-main.netlify.app/)
1. Start creating a new bike lane component and select the "Raised pavement markers" subcomponent
2. Before you save, switch the component type to Traffic signal.
3. Observe that the subcomponent input is cleared ("Raised pavement …
> Fixes subcomponent editing

- .github/workflows/atd_moped_cognito_hooks_build.yml
- moped-auth/cognito-pre-token-hook/requirements/production.txt
This bumps our production cognito hook requirements. Not in the diff, but we are working around a known Lambda env limitation (discussed [here](https://github.com/pyca/cryptography/issues/6391)) by installing the `manylinux2014_x86_64` packages with  `--only-binary=:all:`.
See here: https://github.com/cityofaustin/atd-moped/blob/60a015765b6cdccdefb74354a102181540134c51/.github/workflows/aws-moped-cognito-helper.sh#L26
I did make some other changes to the github action and helper while debugging this, starting with [this commit.](https://github.com/cityofaustin/atd-moped/commit/991d73f8005024a2833ee5bcd96ca45d4bf10f20)
This is deployed on staging so you can test staging.
> Upgrades production cognito lambda packages

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/ProjectMilestones.js
- moped-editor/src/views/projects/projectView/ProjectPhases.js
- moped-editor/src/views/projects/projectView/ProjectTeamTable.js
I noticed that the delete icon is missing on the phases table and the timeline table
This PR defines the icon so it shows up. 
https://deploy-preview-1037--atd-moped-main.netlify.app/moped/projects/1933?tab=timeline
---
> Patch 1.22.1 - define DeleteIcon

- moped-editor/src/views/projects/projectView/ProjectComponents/utils/map.js
https://github.com/cityofaustin/atd-data-tech/issues/12213
Mapbox's fitBounds method can fail with certain combinations of its padding parameter and browser screen widths. You can check out https://stackoverflow.com/a/76011418 for more background. This adds some handling of that failure and some logging in case we need a better fix down the line.
https://deploy-preview-1042--atd-moped-main.netlify.app/moped/
1. Go to https://deploy-preview-1042--atd-moped-main.netlify.app/moped/projects/1933
2. Go the summary page, open dev tools, and decrease your screen width until you see a console message that looks like `fitBounds failed, trying again without padding`. I'm getting 512px or smaller on my screen
3. Go to the Map tab and do the same and you should …
> Fix bug where Mapbox fitBounds fails with small screen widths

- moped-database/metadata/tables.yaml
- moped-database/migrations/1683643688424_create-component-tags/down.sql
- moped-database/migrations/1683643688424_create-component-tags/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/12222
Same deal as https://github.com/cityofaustin/atd-moped/pull/1014, the rows in `moped_component_tags` are going to change after MUG feedback, but the schema should be sound.
Using the Hasura console / graphiql:
- insert some proj component tags
```graphql
mutation InsertProjComponentTags {
insert_moped_proj_component_tags(
objects: [
{ component_tag_id: 1, project_component_id: 2 }
{ component_tag_id: 2, project_component_id: 2 }
{ component_tag_id: 3, project_component_id: 2 }
]
) {
affected_rows
}
}
```
- query project components with the nested component tag relationships
```graphql
query ProjComponent {
moped_proj_components_by_pk(project_component_id: 2) {
project_component_id …
```
> Add DB support for component tags

- moped-database/metadata/tables.yaml
- moped-database/migrations/1683740879611_alter_table_public_moped_components_add_column_is_deleted/down.sql
- moped-database/migrations/1683740879611_alter_table_public_moped_components_add_column_is_deleted/up.sql
- moped-editor/src/queries/components.js
- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/settings.js
- moped-editor/src/views/projects/projectView/ProjectMilestones.js
https://github.com/cityofaustin/atd-data-tech/issues/12248
https://github.com/cityofaustin/atd-data-tech/issues/12255
This PR removes the last remaining `status_id` column. 🥲
_**Note: merging of this and https://github.com/cityofaustin/atd-moped/pull/1014 will have to be coordinated since this update affects a query in there.**_
Local
1. Make sure the local stack spins up with the new migration
2. To make sure the updated query still works, go to the Map tab of a project and try to add a new component
3. If you see components in the dropdown of the new component form, this is working. 👍
4. Go to the Timeline tab and you should see the first header in the Milestone table is `Milestone` instead of `Milestone name` (this is also updated in the data …
> Replace status_id column with is_deleted on moped_components table

- moped-database/migrations/1684262757917_update-component-tags/down.sql
- moped-database/migrations/1684262757917_update-component-tags/up.sql
In service of:
- https://github.com/cityofaustin/atd-data-tech/issues/12177
This PR revises the component tags lookup values based on review of the Access DB and discussion with NW.
Follow the steps in https://github.com/cityofaustin/atd-moped/pull/1049. You should see these tag options:
- Bikeways - AAA Network - 2014 Plan
- Bikeways - AAA Network - 2019 Plan
- Bikeways - AAA Network - 2023 Plan
- Bikeways - AAA Network - Proposed
- Bikeways - AAA Network - Other Jurisdiction
- Bikeways - Work Plan - 2017
- Bikeways - Work Plan - 2018
- Bikeways - Work Plan - 2019
- Bikeways - Work Plan - 2020
- Bikeways - Work Plan - 2021
- Bikeways - Work Plan - 2022
- Bikeways - Work Plan - 2023
- Bikeways - Work Plan - Future
- Urban Trails - Tier 1
- Urban …
> Updates component tags

- moped-database/migrations/1683826893015_list-view-contruct-complete-date/down.sql
- moped-database/migrations/1683826893015_list-view-contruct-complete-date/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/12264
1. Create a new project.
2. Add a "Construction" phase to the project with a start date populated.
3. Add another "Construction phase to the project with a start populated that is **later** than the previous phase you added.
4. Add a "Completed" phase to the project with the end date populated.
5. Add another Completed phase to the project with no end date populated.
6. From the project list view, confirm that your project's "Construction start" and "Completion date" columns are populated with the dates you entered in step 2 and step 4, respectively. 
---
> Ensures correct construction and completion dates are shown in project list view

- moped-editor/src/queries/components.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useProjectComponents.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
- moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js
https://github.com/cityofaustin/atd-data-tech/issues/12262
This PR updates the summary map to show subproject components even if the current project has no components of its own. I updated the summary map to use the same hooks and layers that the component map uses. I also updated the project summary query to fetch the components for the current project _and_ its subprojects so that we can refetch that top-level data when adding or removing subprojects in the `SubprojectTable` component. That way the summary map updates without a page refresh.
@johnclary and everyone else - I couldn't decide on whether the initial map zoom should include subprojects. The components map in the **Map** tab only zooms to components in the current project - not related projects. So, that is what I did here. …
> Show summary map if a project's subprojects are mapped

- moped-database/migrations/1684865704636_flashing-beacon-components/down.sql
- moped-database/migrations/1684865704636_flashing-beacon-components/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/11860
This PR:
- Creates new "Flashing beacon" components and changes the Signage - RRFB component to be part of the "Flashing beacon" group
- Soft deletes the old "Signal - RRFB" component and migrates that data to the Flashing Beacon component, which was actually hidden from users before we overhauled the components UI.
Note that AMD has also requested to have the ability to pick these beacon components from a list, in the same way that Signals + PHBs are selectable, but that is out of scope for now.
1. Create a new component by typing "RRFB" into the component autocomplete.
2. Verify that the only available option is "Flashing Beacon - RRFB".
3. Now type "flashing beacon" into the component …
> Creates flashing beacon components and updates old RRFB components

- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/map.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryLabel.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
https://github.com/cityofaustin/atd-data-tech/issues/12353
This PR updates the project summary map to zoom to a project's components and subproject components on load. The padding around components on the map has also been reduced.
https://deploy-preview-1059--atd-moped-main.netlify.app/moped/projects/1941
1. Go to [this project in staging](https://moped.austinmobility.io/moped/projects/1941?tab=summary), and you should see that the project summary map shows the components of subprojects in green but you must zoom out to see them.
2. Now, go to [the same project in the deploy preview](https://deploy-preview-1059--atd-moped-main.netlify.app/moped/projects/1941?tab=summary).
3. You should see the summary map load with all project components and …
> Refine map default zoom/fit behavior

- moped-database/metadata/tables.yaml
- moped-database/migrations/1685733117665_alter_table_public_moped_proj_components_add_column_srts_id/down.sql
- moped-database/migrations/1685733117665_alter_table_public_moped_proj_components_add_column_srts_id/up.sql
- moped-editor/src/queries/components.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeComponentData.js
https://github.com/cityofaustin/atd-data-tech/issues/12338
This PR adds a **SRTS Infrastructure ID** field to the project component attributes create and edit forms. There are a couple of bug fixes in here too:
- updated the edit form to send `null` instead of an empty string for `description` just like how it does on create
- added the edit component attributes mutation to send tag edits along with the other values
Local
1. Create a project component and add a value for the **SRTS Infrastructure ID** field
2. Check the new component to make sure that you can edit its attributes and see the current value of the SRTS id field
3. Close the map modal and then go back to the **Map** tab
4. Check the component to make sure that your value came through in …
> Add "SRTS Infrastructure ID" field to component form

- moped-editor/src/views/projects/projectView/DateFieldEditComponent.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
https://github.com/cityofaustin/atd-data-tech/issues/12356
This PR updates the component phase completion date part of the component attribute edit form to use `DateFieldEditComponent`. This fixes an issue where the format of the date set in the picker wasn't quite what the MUI component was expecting. This should keep it working in the same way the project milestone and phase date pickers work going forward in Chrome, Firefox, and Safari.
https://deploy-preview-1064--atd-moped-main.netlify.app/moped/
**Using Firefox**
1. Go to https://deploy-preview-1064--atd-moped-main.netlify.app/moped/projects/1945?tab=map or your own new project
2. Edit a component phase completion date and make sure the the form accepts your new date selected in the picker on the …
> Unable to edit component completion date in Firefox and Safari

- moped-editor/src/queries/components.js
- moped-editor/src/views/projects/projectView/DateFieldEditComponent.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentListItem.js
- moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ProjectComponentsList.js
- moped-editor/src/views/projects/projectView/ProjectComponents/SignalComponentAutocomplete.js
- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeFeatureCollections.js
https://github.com/cityofaustin/atd-data-tech/issues/11612
This PR updates the component attributes edit form to fix an issue where the previous values briefly flashed in the UI when saving. I included a diagram of the refactor but it comes down to updating the UI through the new edits through the same channel that the initial data comes through. This PR also pulls out all of the data prep for the form fields out of a custom hook and into individual helpers.
Local
1. Through a project's Map tab, create a signal component (Signal - PHB or Signal - Traffic) and another non-signal component with all parts of the component form filled in
2. Edit these attributes and make sure the previous values don't show as the modal is closing
3. Try creating other …
> Edit component attributes form briefly shows previous values on save

- moped-database/migrations/1688663620552_add_opm_workgroup/down.sql
- moped-database/migrations/1688663620552_add_opm_workgroup/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/12726
This is a quick fix to get OPM into Moped so I can issue a few new accounts. The workgroups/entities/departments data model is quite a mess, which is why I am not touching ATD/PWD/TPW in this PR.
1. Navigate to the staff form
2. In the workgroup field, observe **Office of Performance Management** as an option.
---
> Adds Office of Performance Management workgroup

- moped-editor/src/layouts/DashboardLayout/NavBar/DropdownMenu.js
- moped-editor/src/layouts/DashboardLayout/NavBar/MobileDropdownMenu.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryParentProjectLink.js
https://github.com/cityofaustin/atd-data-tech/issues/12485
https://github.com/cityofaustin/atd-data-tech/issues/12377
This updates the mobile navigation with the data dictionary link. I might have gone a bit overboard on reusing the config for both and handling internal vs. external links, but I wanted to give it a shot. I also fixed the issue with the parent project name link not using the full width available to it.
https://deploy-preview-1077--atd-moped-main.netlify.app/
1. Test the navigation bar help links in mobile and desktop widths to make sure they still go to the right places
2. Add a parent project to a project and then update the parent project's name to something really long like `Demo Project #1 Demo Project #1 Demo Project #1 Demo …
> Add data dictionary link to mobile nav and make parent project name full-width

- moped-editor/src/utils/dateAndTime.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
- moped-editor/src/views/projects/projectView/ProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/12832 -- format long titles
https://github.com/cityofaustin/atd-data-tech/issues/10596 -- style changes to project summary status updates
https://deploy-preview-1079--atd-moped-main.netlify.app/moped/projects/1950
Project 1950 has a super long title, check to see that the title doesnt overlap with the project tabs
The status update author's name shouldn't be bolded, and the timestamp should be relative to now. 
---
> [Enhancement] Refinements to project summary status update

- moped-editor/src/views/staff/StaffListView.js
https://github.com/cityofaustin/atd-data-tech/issues/13031
**URL to test:** [Netlify](https://deploy-preview-1084--atd-moped-main.netlify.app/moped/staff/)
1. Go to the staff page.
2. Use the search input at the top-right corner of the staff list to search for a staff member. 
🎉 
---
> Enables searching on staff list

- moped-editor/src/queries/staff.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivitiesTable.js
- moped-editor/src/views/staff/StaffForm.js
- moped-editor/src/views/staff/components/NonLoginUserActivationButtons.js
- https://github.com/cityofaustin/atd-data-tech/issues/13153'
This also resolves a bug i created [here](https://github.com/cityofaustin/atd-moped/pull/1085/files#diff-0aaf9775780004fb06632bc543b836ac98b0f690c74ec3f8862609e75749094e) which broke the users query. Sorry I missed this 😑 
**URL to test:**  [Netlify](https://deploy-preview-1087--atd-moped-main.netlify.app/) or local
1. Go to the staff page and create a non-login user
2. Edit that user by changing the name or workgroup
3. ☝️ please do not edit any users you did not create — the staging user pool needs to stay in sync with the access DB for the migration.
---
> Fixes non-login user editing

- moped-database/migrations/1691181649099_alter_table_public_moped_proj_component_work_types_add_unique_project_component_id_work_type_id/down.sql
- moped-database/migrations/1691181649099_alter_table_public_moped_proj_component_work_types_add_unique_project_component_id_work_type_id/up.sql
- moped-database/migrations/1691442787520_refresh-component-work-types/down.sql
- moped-database/migrations/1691442787520_refresh-component-work-types/up.sql
- moped-editor/src/queries/components.js
- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/settings.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ControlledAutocomplete.js
- moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/makeComponentData.js
- https://github.com/cityofaustin/atd-data-tech/issues/12230
**URL to test:** Local :/
1. Navigate to the [data dictionary](https://localhost:3000/moped/dev/lookups#moped-components)  and verify that every component has three work types listed in the "Work types" column. The bike lane and signal type components have some extra/special work types as well. This list is going to change a bit over time. There are more work types coming soon via the access migration and user feedback.
2. Go to a project's Map tab and click "New component" to bring up the new component form.
3. Observe that there is a **Work type** field immediately below the component type field with a pre-populated selection of `New`. Nice!
4. Click into the **Work type** field and observe two additional …
> Adds work type select input to component form 

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentMapToolbar.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ProjectName.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/map.js
- moped-editor/src/views/projects/projectView/ProjectNameEditable.js
https://github.com/cityofaustin/atd-data-tech/issues/13129
https://deploy-preview-1089--atd-moped-main.netlify.app/moped/projects/1950?tab=map
Look at the super long titled projects -- the map tab's titlebar should be the same size as titlebar on short project names and should not be overflowing on the component list or map. 
Try resizing the screen to confirm the title maxWidth shrinks so the project id and the phase chip and close map buttons are still visible at smaller sizes. 
Right now the title is scrollable horizontally, but it could also be ellipsis truncated. I put instructions in a comment on the files if you want to try that. If we like the scroll, ill clean up that part and remove the ellipsis part. 
---
> [BUG] Long project names overflow component list + map

- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
https://github.com/cityofaustin/atd-data-tech/issues/13336
Caught this while working on the layers earlier this week. It was a quick fix. You can see the bug in the recording in the bug issue, or you can test in staging using the steps below.
https://deploy-preview-1099--atd-moped-main.netlify.app/moped/ or local
1. Go staging and find or make a project with components that has a subproject with components ([here is one](https://moped.austinmobility.io/moped/projects/1703?tab=map))
2. Go to the Map tab and click on a green feature on the map of a related component
3. After that first click, click a blue feature (current project component)
4. You should see the blue feature turn green even though it isn't a related component
5. Go to this deploy preview …
> Fix project components showing in green when clicking from a related component

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
https://github.com/cityofaustin/atd-data-tech/issues/13120
https://deploy-preview-1097--atd-moped-main.netlify.app/moped/projects/
Add a new component. Toggle the "Use component phase" 
Only add a completion date, but leave the phase blank. 
Save.
Open the component attributes again, and check that the completion date is there, and that the toggle is selected. 
Open an existing component and repeat the steps above. Confirm the completion date saves, even if there is no phase. 
---
> [Enhancement] Ability to set component completion date without setting a component phase

- moped-api/users/helpers.py
- moped-api/users/validation.py
- moped-database/metadata/tables.yaml
- moped-database/migrations/1691507775643_add-staff-mug-tracking/down.sql
- moped-database/migrations/1691507775643_add-staff-mug-tracking/up.sql
- moped-database/seeds/1602292389297_initial_seed_staging.sql
- moped-editor/src/queries/staff.js
- moped-editor/src/views/staff/NewStaffView.js
- moped-editor/src/views/staff/StaffForm.js
- moped-editor/src/views/staff/StaffListView.js
- moped-editor/src/views/staff/components/NonLoginUserActivationButtons.js
- https://github.com/cityofaustin/atd-data-tech/issues/13274
I decided to add a "note" column as well, because there are a handful of special users in our DB that would benefit from a note. Eg. the "unknown" user ([discussion](https://austininnovation.slack.com/archives/CNUEPKLB1/p1691170753237639)).
**Steps to test the Moped user API changes:**
I'm not sure how to test the API changes. I've tried in the past to run the test fixtures but have not been able to configure the local setup. I am happy to be on standby to patch this code on staging. Any suggestions?
**Steps to test the Moped editor changes:**
1. Start the Hasura cluster and editor.
2. Navigate to the staff page and observe the new MUG member column on the staff list. Observe that Patricia is listed as …
> Adds MUG tracking to user profiles

- moped-editor/src/utils/signalComponentHelpers.js
- https://github.com/cityofaustin/atd-data-tech/issues/13413
**URL to test:**  [Netlify](https://deploy-preview-1103--atd-moped-main.netlify.app/) ✨ 
1. Create a new project using the "From signal" toggle, which enables you to select a signal from a list.
2. Navigate to your new project's map and confirm that the component's work type is populated as `New` in the attribute edit modal.
3. Create a non-signal project and make sure it is created without any errors.
---
> Sets component work type when creating a signal project

- moped-database/migrations/1692285495049_delete_work_type_construction_inspection/down.sql
- moped-database/migrations/1692285495049_delete_work_type_construction_inspection/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/13426
1. Start your Moped
2. Create a new signal component. On the component attributes form, confirm that "construction inspection" is not available as a work type.
3. You can also peep the data dictionary and there should be no trace of this component work type.
---
> Deletes "Construction Inspection" work type

- moped-editor/src/views/staff/EditStaffView.js
- moped-editor/src/views/staff/StaffListView.js
- moped-editor/src/views/staff/StaffListViewCustomComponents.js
- https://github.com/cityofaustin/atd-data-tech/issues/13507
**URL to test:**  [Netlify](https://deploy-preview-1110--atd-moped-main.netlify.app/)
1. Navigate to the Staff page
2. Find your user account and edit it so that you are a MUG member and also add a note. Save.
3. Find you user account and click the edit icon to verify your changes were saved. Now return to the staff list.
4. Add a filter to staff list: **MUG Member** **equals**  **Yes**
6. Now use the menu above the top-left of the staff list to copy all Moped User Group email addresses.
7. Paste your clipboard somewhere and observe that the email addresses you pasted match the filtered staff list.
8. Now use the same menu to copy **All active users**. Paste your clipboard and observer it is a long list that only includes active …
> Adds ability to copy user email addresses from staff list

- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/settings.js
https://github.com/cityofaustin/atd-data-tech/issues/13099
Adds roles to the data dictionary and sorts them by the set `role_order`
https://deploy-preview-1112--atd-moped-main.netlify.app/moped/
1. Go to the Data Dictionary link
2. Click the **Roles** button at the top and you should arrive at the list of roles
3. You can check them against the local DB or one of the read replicas
---
> Add project personnel roles to data dictionary

- moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchInput.js
- moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchQueryConf.js
- moped-editor/src/libs/GQLAbstract.js
https://github.com/cityofaustin/atd-data-tech/issues/7659
This PR fixes a bug where the config for the advanced search and the global search were intertwined. My leading theory is that GQLAbstract was using the same object reference for both the global search and the advanced search since the global search recycled the project list view config. So, both components were mutating the same object. Pretty gnarly! 
[Here are the lines](https://github.com/cityofaustin/atd-moped/blob/caffff6ffac648ba034f13b0163dd68f81533599/moped-editor/src/libs/GQLAbstract.js#L11-L12) where the GQLAbstract class assigns the object reference to its instance property called `initConfig` instead of creating a new reference. This remains a bug with GQLAbstract, but I didn't want to make such a large change in this …
> Global search is affected by previous advanced search

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryCouncilDistricts.js
https://github.com/cityofaustin/atd-data-tech/issues/10894
https://deploy-preview-1122--atd-moped-main.netlify.app/moped/projects
Check different projects and see that their council districts appear under the summary map. 
If there is no council district, you will see a blank space. 
Question -- should it be sorted in numerical ascending order? 
---
> Add council districts to project summary tab

- moped-database/migrations/1694711478835_backfill-com-loc-desc/down.sql
- moped-database/migrations/1694711478835_backfill-com-loc-desc/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/13800
1. Start Moped!
2. Open the map for project 228—observe that the signal component has the location description "365:  CESAR CHAVEZ ST / ROBERT T MARTINEZ JR ST"
---
> backfills location description with signal location

- moped-database/migrations/1694809058492_list_view_optimize/down.sql
- moped-database/migrations/1694809058492_list_view_optimize/up.sql
- moped-database/migrations/1694809881268_moped_project_updated_at_index/down.sql
- moped-database/migrations/1694809881268_moped_project_updated_at_index/up.sql
- https://github.com/cityofaustin/atd-data-tech/issues/13857
It's going to be hard to notice the performance improvements without a large number of projects. But definitely you want to test that the list view loads normally.
1. Start yer Moped
2. Make sure the project list view loads normally.
3. Make all columns visible.
4. Try some advanced search filters
To test the query performance itself you can connect to the read replica!
1. Connect to the prod read replica
2. Run the `up` version of the view sql. (exclude the "CREATE OR REPLACE VIEW..." bit).
3. Run the `down` version of the view sql (exclude the "CREATE OR REPLACE VIEW..." bit).
I am seeing a roughly 50% speed up versus the old list view query. ~500ms vs 1000ms once the query is warm.
---
> Rework signal feature in project list view query

- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
https://github.com/cityofaustin/atd-data-tech/issues/13898
https://deploy-preview-1135--atd-moped-main.netlify.app/moped/projects
To reproduce:
1. Load the project list view. 
2. Use your browser's dev tools to delete `mopedColumnConfig` from local storage.
`localStorage.removeItem("mopedColumnConfig")`
4. Refresh the page. The list view has the default columns visible. Good.
5. Update the list view column settings to show one of the hidden columns.
6. Refresh the page. Your column choice should be the only change you see. 
---
> BUG -- hidden columns not persisting

- moped-editor/src/components/GridTable/GridTableFiltersCommonOperators.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/13904
https://deploy-preview-1138--atd-moped-main.netlify.app/moped/
Toggle the "has subprojects" column to be visible
Advanced filter, choose Has Subprojects as the field. 
Choose either yes or no. 
See the results. 
I also added the has subprojects column and the parent project name column to the csv export. 
---
> Advanced filter for projects with Subprojects

- moped-database/metadata/tables.yaml
- moped-database/migrations/1696622988854_add_feature_length_column/down.sql
- moped-database/migrations/1696622988854_add_feature_length_column/up.sql
- moped-database/migrations/1696624355279_add-length-to-views/down.sql
- moped-database/migrations/1696624355279_add-length-to-views/up.sql
- moped-database/views/project_geography.sql
- moped-database/views/uniform_features.sql
- https://github.com/cityofaustin/atd-data-tech/issues/14155
1. Create a project component using a mix of selected street segments and drawn lines. 
2. Use google maps (or your favorite mapping platform) to measure the approximate distance of your components.
3. Compare those measurements to the length stored in the DB. This query will sum up `length_feet` from all line features in a component:
```sql
SELECT
project_id,
project_component_id,
description,
sum(length_feet) AS total_component_length
FROM (
SELECT
project_id,
mpc.project_component_id,
mpc.description,
length_feet
FROM
feature_street_segments
LEFT JOIN moped_proj_components mpc ON mpc.project_component_id = feature_street_segments.component_id
WHERE
feature_street_segments.is_deleted = FALSE
UNION ALL …
```
> Adds length column to line features

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentListItem.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ProjectComponentsList.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/componentList.js
- https://github.com/cityofaustin/atd-data-tech/issues/14160
1. Start your local Moped andnrun these SQL statements to delete features from components:
```SQL
delete from feature_street_segments where 1=1;
delete from feature_intersections where 1=1;
```
2. Open project 227's map: `https://localhost:3000/moped/projects/227?tab=map`
3. Observe the error alerts in the component list. Map each component and and observe the alert disappear.
4. Repeat these steps with drawn lines and drawn points.
5. What should the alert text say?  Is "Component is not mapped" ok?
---
> Show error alert when component is unmapped

- moped-database/migrations/1696964354076_update-council-district-trigger/down.sql
- moped-database/migrations/1696964354076_update-council-district-trigger/up.sql
- moped-toolbox/backfill_council_district/backfill_council_district.sql
- https://github.com/cityofaustin/atd-data-tech/issues/13915
1. You are going to create project components that are near multiple council districts. An easy way to do this is to inspect the `council_district` column of the [open traffic signals dataset](https://data.austintexas.gov/Transportation-and-Mobility/Traffic-Signals-and-Pedestrian-Signals/p53x-x73x/data) to find some signals that have multiple district associations. For example, create signal components using the following signals:
- `419: BRODIE LN / WILLIAM CANNON DR` - districts 5 & 8
- `427: STASSNEY LN / 35 SVRD` - districts 2 & 3
- `488: MANOR RD / BERKMAN DR` - districts 1 & 9
2. As you add/remove these signals, navigate to the project summary tab and observe the council districts listed below the …
> Updates council district trigger to include "100ft" buffer

- moped-editor/src/components/GridTable/FiltersCommonOperators.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/views/projects/projectsListView/ProjectsListView.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useCsvExport.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useProjectListViewQuery.js
https://github.com/cityofaustin/atd-data-tech/issues/14068
This PR ports the existing CSV export generation into a custom hook. Lots of the existing logic was reused but moved out of the `Search` component.
Local
1. Spin up the stack locally [with production data](https://app.gitbook.com/o/-LzDQOVGhTudbKRDGpUA/s/-MIQvl_rKnZ_-wHRdp4J/dev-guides/how-tos/how-to-load-production-data-into-a-local-instance). Seed data can be used but there will be fewer projects to test this feature on. You can also compare prod exports to the export that come out of this branch if you use prod data.
2. Try exporting data with different order by columns
3. Try exporting data with simple search filters applied
4. Try exporting data with advanced search filters applied
5. You …
> Use project list view query hooks for csv export

- moped-editor/src/views/projects/projectView/ProjectComponents/DraftComponentList.js
- moped-editor/src/views/projects/projectView/ProjectComponents/DraftComponentListItem.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/componentList.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/14166
https://deploy-preview-1156--atd-moped-main.netlify.app/moped/projects/1759?tab=activity_log
1. Go to a projects map view.
2. Create a new component with a location description. When mapping the component in create mode, the component list item should have the Component Type - Subtype on the first line, and the second line should have the location description, similar to the non-editing state of a components list item.
4. Save the component and test editing it. The above should also be true.
---
> Show location description in draft/edit component list item

- moped-editor/src/utils/activityLogFormatters/mopedContractsActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
https://github.com/cityofaustin/atd-data-tech/issues/13000
https://deploy-preview-1155--atd-moped-main.netlify.app/moped/projects/1759?tab=activity_log
Add and edit work activities, check the activity tag to see that the new columns appear. 
---
> Add work activity fields to activity log formatter

- moped-editor/src/utils/signalComponentHelpers.js
- https://github.com/cityofaustin/atd-data-tech/issues/14247
**URL to test:** Netlify....
1. Create a new project with a signal
2. Open the project map and verify the signal component has the location description populated
---
> Set location description when creating a new signal project

- moped-toolbox/backfill-task-orders/backfill_task_orders.py
- moped-toolbox/backfill-task-orders/secrets_template.py
- https://github.com/cityofaustin/atd-data-tech/issues/14246
1. Start local with production data
2. Login to local editor with JD's login and copy your `Authorization` token from the graphql request headers.
3. Save `secrets_template.py` as `secrets.py` and add your auth token to the `local` entry.
4. Fix your user ID in the prod database: 
```sql
update moped_users set user_id = 1 where first_name = 'JD';
```
5. from a python environment with `requests` installed, run the script
```shell
$ python backfill_task_orders.py -e local
```
6. Success!
---
> create task order backfill script

- moped-editor/src/views/projects/projectView/ProjectComponents/mapSettings.js
- https://github.com/cityofaustin/atd-data-tech/issues/14278
**URL to test:** [Netlify](https://deploy-preview-1165--atd-moped-main.netlify.app/moped/projects)
Browse some projects. The summary map should render the project extent without animated zooming.
Similarly, project map should render the project extent without animation. Clicking the mag icon in the component list should trigger an animated zoom-in.
When you close the project map, the summary map should still render without animated zooming 👍 
---
> Disables zoom animation on initial map load

- moped-database/metadata/tables.yaml
- moped-database/migrations/1697232878272_task_orders_work_activity_plv/down.sql
- moped-database/migrations/1697232878272_task_orders_work_activity_plv/up.sql
- moped-database/views/project_list_view.sql
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
https://github.com/cityofaustin/atd-data-tech/issues/14261
please test locally
Using up to date prod data, toggle the task order column to be visible on the project lists. 
Advanced search for projects with no task orders, with task orders, contains the word signal etc. 
I also checked the csv export to see that the task order names are still downloading as before
---
> Update task order column in project list view to pull from work activities

- moped-database/metadata/tables.yaml
- moped-database/migrations/1697768359465_dedupe_plv_tks/down.sql
- moped-database/migrations/1697768359465_dedupe_plv_tks/up.sql
- moped-database/views/project_list_view.sql
1. Use the editor add a few work activities to projects with multiple task orders.
2. Make sure the list view loads normally
3. these two statements should have the same result:
- `select count(project_id) from project_list_view;`
- `select count(project_id) from moped_project where is_deleted = false;`
---
> Reworks work activities in the project list view

- moped-database/metadata/tables.yaml
- moped-database/migrations/1697829614737_track_migrated_projects/down.sql
- moped-database/migrations/1697829614737_track_migrated_projects/up.sql
This PR addresses the need to be able to cleanly rollback the Access DB migration.
- Add a  field will allow us totrack any projects created through the Access DB migration so that we can delete them if needed. We can delete this column after we successfully migrate. 
- Disable Hasura event triggers on `delete` operations. We do not allow records to be deleted through Hasura except by our admin/root user. This change removes Hasura `delete` event triggers entirely, because the only conditions under which we are deleting records will be for admin purposes that we presumably to not want to track as events.
In order to completely roll back the migration we'll need to run [these commands](https://github.com/cityofaustin/atd-moped/blob/4838-jc-migrate-access-db/moped-toolbox/access_migration/mi …
> Prep DB for rolling back the Access DB migration

- moped-database/migrations/1698070704301_backfill_confirmed_phase_dates/down.sql
- moped-database/migrations/1698070704301_backfill_confirmed_phase_dates/up.sql
from https://github.com/cityofaustin/atd-data-tech/issues/14350: 
Since we https://github.com/cityofaustin/atd-data-tech/issues/14300 - we need to backfill the existing project phases based on the same logic. For both phase_start and phase_end, if the date is today or earlier it's corresponding confirmation flag can be set to true.
I tested by loading prod data, running the migrations and then checking 
`select phase_start, is_phase_start_confirmed, project_phase_id from moped_proj_phases mpp where phase_start > current_date` and `select phase_start, is_phase_start_confirmed, project_phase_id from moped_proj_phases mpp where phase_start < current_date` to see if they made sense. 
---
> Backfill phase start/end date confirmation status

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryCouncilDistricts.js
https://github.com/cityofaustin/atd-data-tech/issues/14305
because there is a change to the metadata, you will have to test this locally
Create a project with no mapped components, but with child projects that have mapped components. Or if you are using prod data, https://localhost:3000/moped/projects/509. The summary tab has council districts
Also test a project with mapped components that also has child projects with mapped components, and a project without any child projects
---
> add child project council districts to summary tab

- moped-editor/src/views/projects/projectView/NoteInputQuill.js
- moped-editor/src/views/projects/projectView/ProjectNotes.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/14381
https://deploy-preview-1176--atd-moped-main.netlify.app/moped/ 
1. Go to the summary tab of a project, click on the status update.
2. You shouldn't see the note type radio buttons here when creating a new status in the modal or when editing an old status from here.
3. Test making a new status from this modal, make sure it saves correctly.
4. Test editing an old status from here and make sure it saves correctly. 
---
> Hide the note type selector when creating a status update

- moped-editor/src/views/projects/projectView/ProjectView.js
- https://github.com/cityofaustin/atd-data-tech/issues/14434
**URL to test:**  Netlify
1. Visit the project summary for any project. Click around on the map tab, then use your browser's back button to return to the previous tab.
2. Repeat, but use the "Close Map" button to return to the project summary tab.
3. Finally, try navigating to each tab, then use your browser's back button a bunch to make sure you are returned to each previous tab correctly.
---
> Restores ability to use back button from the project map tab

- moped-database/migrations/1698257789139_update_component_geom_type/down.sql
- moped-database/migrations/1698257789139_update_component_geom_type/up.sql
- moped-database/migrations/1698428471744_create_signage_line_component/down.sql
- moped-database/migrations/1698428471744_create_signage_line_component/up.sql
- moped-editor/package.json
- https://github.com/cityofaustin/atd-data-tech/issues/14408
After this change, I will manually update project components in Moped that need to be re-mapped against their new geometry type. This query will reveal that todo list:
```sql
SELECT
*
FROM
moped_proj_components mpc
LEFT JOIN moped_components mc ON mc.component_id = mpc.component_id
WHERE
mpc.component_id in (25, 27, 40, 48, 49, 50, 57, 58, 2, 21, 35, 45);
```
1. Create any of the component types listed in the issue. They should follow the following geometry type:
- Dynamic Speed Display Device - line
- Highway - Access Ramp - line
- Pavement Marking - School Zone - line
- Speed Management - Speed Cushions (Asphalt) - line
- Speed Management - Speed Cushions (Rubber) - line
- Speed Management - Speed Humps …
> Update various component geometry types

- moped-editor/src/utils/activityLogFormatters/mopedProjectUpdateMigrationActivity.js
- moped-editor/src/utils/activityLogHelpers.js
I've added a separate activity log entry for cases where we have updated an existing project with Access DB data. there are not going to be any other events for these, because the access DB 
Steps to test:
1. Take a look at the code
2. I'm pushing this to the Access migration [test instance](https://4838-jc-migrate-access-db--atd-moped-main.netlify.app/moped/projects). So you can check out [project ID 280](https://4838-jc-migrate-access-db--atd-moped-main.netlify.app/moped/projects/280?tab=activity_log).
Here's the new event I'm adding for projects updated via the migration:
And here's the original event that we have for a project created through the migration:
> Adds another activity log record type for projects updated via the migration

- moped-database/metadata/tables.yaml
- moped-database/migrations/1698783764345_add_generated_column_moped_components/down.sql
- moped-database/migrations/1698783764345_add_generated_column_moped_components/up.sql
- moped-database/migrations/1698786867086_add_component_subtype_to_view/down.sql
- moped-database/migrations/1698786867086_add_component_subtype_to_view/up.sql
- moped-database/views/project_list_view.sql
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityToolbar.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/14301
local
Spin up the database /  run the new migrations. Toggle the "components" column to visible in the project list table, you should see a comma delimited list of each projects components. 
Use the advanced search to see how many projects contain a Signal or a PHB by searching the Components field. 
---
> Add list of components to project list view and advanced search

- moped-editor/src/views/projects/projectView/ProjectNameEditable.js
- moped-editor/src/views/projects/projectView/ProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/14487
https://deploy-preview-1192--atd-moped-main.netlify.app/moped/projects
https://deploy-preview-1192--atd-moped-main.netlify.app/moped/projects/1926
Visit this project. Click its parent project link. Check that the project title, description, sponsors etc. reload between projects. Use the back button in your browser to navigate back, the project should reload. 
---
> Fix bug Project summary data persisted when navigating between parent/child projects

- .github/workflows/atd_moped_etl_arcgis_docker.yml
- moped-editor/src/components/GridTable/Filters.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/SearchBar.js
- moped-editor/src/views/projects/projectView/ProjectView.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/helpers.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useProjectListViewQuery.js
https://github.com/cityofaustin/atd-data-tech/issues/11282
This PR:
- adds an advanced search radio group to select either **and** or **or** logic
- updates `useAdvancedSearch` to handle and apply that logic to the advanced filters in the GraphQL query
- updates the code to use React Router [useSearchParams](https://reactrouter.com/en/main/hooks/use-search-params#usesearchparams) to manage the url query strings
https://deploy-preview-1187--atd-moped-main.netlify.app/moped/
1. Go to the project list view in the deploy preview
2. Add an advanced filter by click the filter icon in the search box
3. Try searching for:
- **ALL**
- **Lead is COA ATD Project Delivery**
- **Sponsor is COA ATD Active Transportation & Street Design**
- Notice that there are …
> Ability to advanced search using multiple filters as "or"/"any" condition

- moped-editor/src/views/projects/projectView/ProjectView.js
This patches a bug where the project view would WSOD after the redirect that happens when creating a new project. The lack of React Router state was not being handled in `ProjectView`.
https://deploy-preview-1201--atd-moped-main.netlify.app/moped/
1. Create a new project
2. When redirected to the new project view, you should see the project view load and not a WSOD
---
> Handle when queryString from react router state is null

- moped-editor/src/views/projects/projectView/ProjectView.js
n/a
More cache = more problems! This PR strips out caching from the project view, which was having the weird effect of causing the page to reload/scroll to top when editing on the project summary.
1. Edit various fields on the summary tab.
---
> Fixes screen flashing when editing project data

- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/views/projects/projectView/ProjectView.js
This fixes the key to access the state passed with React Router. It was the wrong name so the value was `undefined`. 😑 Also, the `filter` and `isOr` query string parameters were not clearing in the url when switching from advanced search to simple search so I patched that up while I was at it.
https://deploy-preview-1205--atd-moped-main.netlify.app/moped/
1. Create a new project and make sure the project list view loads after the redirect
2. Go to the project list view and add advanced filters
3. Click on the project link or parent project link and make sure that your filters are retained when you click "< ALL PROJECTS" on the project view page
4. When linked back to the project list view with advanced filters active, enter a search value into the …
> Fix project view link back to project list view with previous filters

- moped-database/metadata/tables.yaml
- moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
Ooops, we do not want our activity log event trigger to fire when a component's updated_at/updated_by column.
1. Create and edit components.
2. Check the activity log to verify your changes are being tracked.
---
> Exclude audit fields from proj component event

- moped-database/migrations/1700067187681_add_zicla_barriers_subcomponent/down.sql
- moped-database/migrations/1700067187681_add_zicla_barriers_subcomponent/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/14556
run locally
You can see which components have the new zicla barriers as potential subcomponents
```sql
select mc.component_id, mc.component_name_full, ms.subcomponent_name 
from moped_components_subcomponents mcs 
join moped_subcomponents ms  on ms.subcomponent_id = mcs.subcomponent_id
join moped_components mc on mc.component_id =mcs.component_id 
where ms.subcomponent_name = 'Protection Type - ZICLA Barriers'
order by component_id
```
And also check in the editor that the subcomponent options appear for these components 
```sql
select count(*) from moped_components_subcomponents mcs where component_id = 36 
```
Before down migration the answer should be 13, afterwards 12! bakers dozen -> dozen
---
> Create new moped subcomponent, zicla barriers

- moped-database/migrations/1700515730257_fix_delete_component_bug/down.sql
- moped-database/migrations/1700515730257_fix_delete_component_bug/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/14663
locally
spin up your moped. 
Add a component to a project. (Of a component type that doesnt already exist on the project) Delete the component. 
Go back to the project list view, and making sure the components column is visible, confirm that your deleted component doesnt appear. 
If you run the down migration, you should see your deleted component appear. 
---
> Exclude deleted components from components column of the project list view 

- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/14708
This PR fixes a bug where outdated columns in local storage were breaking the new method of fetching only the data shown in the table. The root of the problem was that we need to clean up outdated columns in user's local storage if we want to rely on those columns to fetch data. This was luckily caught early since `task_order` changed to `task_orders` which surfaced the issue fast. 🏎️ 🙌
Below is a quick summary of the changes and the value of `mopedColumnConfig` local storage for each step.
**Previous method**
```md
// This works because we were fetching all columns every render.
{
"task_order": false, <- This entry was never consumed by the app and ignored.
"task_orders": false,
...config for any other column set previously …
```
> Update project list view local storage to support new columns and clear outdated ones

- moped-editor/src/components/Maps/GeocoderControl.js
This PR aims to close https://github.com/cityofaustin/atd-data-tech/issues/9311.
Make the street name search work for any street that could reasonably be expected to be used in Moped.
The existing bounding box was smaller than the effective metropolitan area of Austin, TX. I have established a new bounding box by:
* Taking the comprehensive street network (SRID 2277, NAD83 / Texas Central (ftUS)) 
* Dissolving it into a single feature
* Taking its convex hull
* Buffering this by 1 kilometer
* Reprojecting this into WGS84
* Taking the bounding box of the resulting shape
Please see [this geojson file](https://gist.github.com/frankhereford/e40a89d94568cc0ea86bf114766a9e4a) for the bounding boxes visualized by the github gist system. The small one is the old bounding box and the new one is …
> Update bounding box limiting our geocoding scope

- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/SearchBar.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/helpers.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/14693
this pr adds a loading spinner when refetching data on the projects list table, specifically when the user searches (regular and advanced) or toggles on a new column
https://deploy-preview-1218--atd-moped-main.netlify.app/
- go to the projects list view
- open dev tools and set throttling to slow 3g (you might have to make a custom throttling profile to slow network activity down enough to see the loading spinner)
- run a regular search, you should see a spinner pop up briefly in the top left corner of the table above the headers
- follow the same procedure with an advanced filter (try searching 'status' for a single character)
- follow the same procedure by toggling off all but one …
> 14693 Adds visual feedback while refetching table data

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/14768
this pr allows the description field to be nullable/optional so users can clear descriptions without breaking form validation
https://deploy-preview-1221--atd-moped-main.netlify.app/
- Create a component and fill in the Description field
- Edit the component by removing the text from the description field
- The form's save button should remain enabled and you should be able to save this change
---
> fixes error clearing proj component description

- moped-editor/src/components/GridTable/Filters.js
- moped-editor/src/utils/numberFormatters.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/14582
https://deploy-preview-1225--atd-moped-main.netlify.app/moped/ 
1. [Current behavior](https://moped.austinmobility.io/moped/projects) for number type filter fields such as ID is that if you type something like "1e1" into the input, the search button will appear after the second `1` and the user can search with this invalid input causing an ugly graphql error to slip into the UI.
2. Now in the deploy preview try to replicate that error. You should find that the search button is disabled until valid input is entered. If invalid input is entered the text box will turn red and give the user an error warning and the search button disables again.
3. Also test adding multiple filters, make one …
> Advanced filters with number inputs can break gql query with allowed characters

- moped-database/migrations/1703786941217_modify_files_user_id_constraint/down.sql
- moped-database/migrations/1703786941217_modify_files_user_id_constraint/up.sql
- moped-database/seeds/1602292389297_initial_seed_staging.sql
- moped-editor/src/auth/user.js
- moped-editor/src/views/account/AccountView/Profile.js
- moped-toolbox/encrypt_or_decrypt_dynamo_db_claims/README.md
- moped-toolbox/encrypt_or_decrypt_dynamo_db_claims/claims.py
https://github.com/cityofaustin/atd-data-tech/issues/15039
This PR:
- updates the seed data to match up with the staging admin and editor users stored in 1PW
- adds a migration that fixes a foreign key constraint issue that is blocking the final task in the issue above
- adds a script to help encrypt/decrypt our user claims (also part of the final task in the issue above)
Local
1. Start Moped locally (using `./hasura-cluster start` and not from production data)
2. Log in using the username/pw stored in the 1PW entry called **Moped Local Editor User Login**
3. Add a status or note to a project or anything else that is tracked in the activity log
4. You should see that there is no foreign key error and that the activity log shows the correct user for the …
> Unify various logins for Moped testing and development

- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
https://github.com/cityofaustin/atd-data-tech/issues/15120
https://deploy-preview-1234--atd-moped-main.netlify.app/moped/projects
Sign in as a user, create a project. 
Sign in as a different user and edit that project. 
The activity log should only show the actual changes, and make no mention of "updated by", or show undefined labels. 
---
> Ignore updated by user id in activity log

- moped-editor/src/components/GridTable/Filters.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/helpers.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
https://github.com/cityofaustin/atd-data-tech/issues/15049
https://github.com/cityofaustin/atd-data-tech/issues/15074
This PR:
- updates the `filterParameters` state to have the same shape and key-value pairs (field, operator, and value) as the `filters` state that powers the query
- moves a lot of functions defined within the `Filters` component into a helpers file
- removes code that used to access configuration about a field and then store it in state so that it now accessing that configuration as needed
If you want to visualize the biggest change, run locally and log `filterParameters` in the `Filters` component as you add advanced filters. Compare what that looks like with this branch versus `main` branch.
https://deploy-preview-1236--atd-moped-main.netlify.app/moped …
> Refactor filterParameters state to use search params state shape and filter config

- moped-editor/src/components/GridTable/Filters.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/SearchBar.js
- moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchInput.js
- moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchResults.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useSearch.js
https://github.com/cityofaustin/atd-data-tech/issues/15206
This PR adds a `search` param that is set by the project list view search box. It maintains the current way that we use either the search box or the advanced filter individually and never combine the two when filtering the project list results.
Local
1. In the search box at the top of the project list view, enter a search term like **lamar** and press enter. You should see matching results in the view.
2. Check the url and you should see the search parameter like `https://localhost:3000/moped/projects?search=lamar`
3. Open the advanced filters by clicking the filter button in the search box
4. Add a filter like **Name contains kramer** and click "Search". The search box should clear, the url …
> Persist search term in project list URL parameters

- moped-editor/src/layouts/DashboardLayout/NavBar/DropdownMenu.js
- moped-editor/src/layouts/DashboardLayout/NavBar/MobileDropdownMenu.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/15036
https://deploy-preview-1244--atd-moped-main.netlify.app/moped/
1. Click on the help menu navbar, test clicking on the icons of each menu item. Clicking on the icon should redirect you. Also clicking on the very edge of the menu item should redirect you.
2. Now test on mobile. Before this update clicking on the very edge of the menu item wouldn't redirect you, now it should.
---
> Help menu icons are not hyperlinked

- moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityEntry.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
https://github.com/cityofaustin/atd-data-tech/issues/14614
https://github.com/cityofaustin/atd-data-tech/issues/15119
https://deploy-preview-1231--atd-moped-main.netlify.app/moped/projects/1974?tab=activity_log
Interact with a component
Check the activity log, see the component linked.
---
> Add component hyperlinks to the activity log

- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/settings.js
- https://github.com/cityofaustin/atd-data-tech/issues/15377
**URL to test:** [Netlify](https://deploy-preview-1253--atd-moped-main.netlify.app/)
On the data dictionary, look at the **Phase name - simple** column of the **Phases** section.
---
> Add phase name - simple to data dictionary

- moped-editor/src/views/staff/StaffListView.js
- https://github.com/cityofaustin/atd-data-tech/issues/15380
**URL to test:** [Netlify](https://deploy-preview-1248--atd-moped-main.netlify.app/)
Go to the **Staff** view and sort the **Last seen** column. Look at it 👀 🧠  
---
> Fixes "last seen" sorting on staff list

- moped-database/migrations/1706117943942_add_dashboard_load_event/down.sql
- moped-database/migrations/1706117943942_add_dashboard_load_event/up.sql
- moped-editor/src/App.js
- moped-editor/src/components/ActivityMetrics.js
- moped-editor/src/views/dashboard/DashboardView.js
- https://github.com/cityofaustin/atd-data-tech/issues/15392
You will use your SQL client to inspect activity events as they are logged.
1. Start Moped locally. Log out, so that you're looking at the login screen.
2. Open your SQL client, and delete any records in the `moped_user_events` table:
```sql
DELETE FROM moped_user_events WHERE TRUE;
``` 
3. Login to Moped. There should now be one event in the `moped_user_events` table. The event name should be `app_load`.
4. Navigate to the **Dashboard** page. There should now be a second event in the `moped_user_events` table with the name `dashboard_load`.
5. While still on the **Dashboard** page, refresh the page in your browser. This will create two new events: `app_load` and `dashboard_load`.
6. Now navigate to the …
> Add an activity event to track when when the Dashboard page loads

- moped-editor/src/utils/localStorageHelpers.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityToolbar.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/helpers.js
- https://github.com/cityofaustin/atd-data-tech/issues/15430
**URL to test:** [Netlify](https://deploy-preview-1257--atd-moped-main.netlify.app/)
1. Start by making sure the project list view columns are being persisted normally. Edit their visibility, refresh your page. Edit them again. Refresh your page. 
2. Now do the same thing on the **Work Activities** table (on the **Funding** tab). 
3. You can try being adversarial by manually editing your local storage value for `workActivityTableColumnConfig`. Try adding a column name that doesn't exist. or try changing the whole blob to `"pizza"`. Shouldn't be a problem.
I think that's it?
---
> Persist work activity column visibility in local storage

- moped-editor/src/utils/activityLogFormatters/mopedPhasesActivity.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/15397
this pr adds phase start and phase end confirmation updates to the activity log. it also fixes a small bug that was responsible for displaying extra commas in the activity log for phase updates.
https://deploy-preview-1261--atd-moped-main.netlify.app/
- go to a project's timeline, select a phase and invert the checkbox booleans for the phase start and phase end 'confirmed' values
- you should see these changes cleanly reflected in the activity log ✨
---
> adds phase start and end confirmation to activity log

- moped-editor/src/components/GridTable/FiltersCommonOperators.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/15052
We have some code that used to handle "special cases" where we received the string `None` from the the project list DB view instead of `null` like many of the other columns. These special cases no longer exist due to enhancements to the DB view over time ✨ so we no longer need to handle them.
https://deploy-preview-1262--atd-moped-main.netlify.app/moped/projects
1. In staging or production and one filter at a time, apply the following and note the count of the results that you see:
- **Lead is blank** - 0 results in production (as of end of day 1/30/24)
- **Lead is not blank** - 3106 results in production out of 3293 total projects
- **Sponsor is blank** - 0 results in production
- **Sponsor is …
> Fix special case null value handling in advanced search

- moped-editor/src/components/forms/ControlledSwitch.js
- moped-editor/src/components/forms/RegisteredSwitch.js
- moped-editor/src/views/projects/projectView/ProjectPhaseForm.js
https://github.com/cityofaustin/atd-data-tech/issues/15529
This PR fixes an issue where recent updates to the Phase form in the Timeline tab broke the default values from showing up in the form for existing phases to be edited.
https://deploy-preview-1265--atd-moped-main.netlify.app/
**Same steps as last time but the last step covers the regression that this PR fixes**
1. Go to a project's **Timeline** tab
2. Add a new phase and, before you choose a start date, toggle the **Current phase** switch
3. You should see the start date autofill with today's date and see the **Confirmed** checkbox checked next to it
4. Before saving, add some text to the **Status Update** text box
5. Save and you should see your new phase in the table with the current phase …
> Current phase value is not correct when editing a current phase

- moped-editor/src/components/GridTable/Filters.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/SearchBar.js
- moped-editor/src/components/GridTable/helpers.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useProjectListViewQuery.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useSearch.js
https://github.com/cityofaustin/atd-data-tech/issues/15371
This PR updates the project list search box and advanced filtering to work together so users can filter down filtered rows down in either direction. The logic is:
search box term (query with OR logic between search box fields shown in placeholder text)
AND 
advanced filters (query with AND or OR logic between rows of advanced filters)
https://deploy-preview-1263--atd-moped-main.netlify.app/moped/projects
1. Go to the project list view and enter a search value like **testing** in the search box and press **Enter**. You should see filtered results. Note the number of results and the search params as you continue through the steps.
2. Open the advanced filters and add a filter like **Status is …
> Ability to use basic search + filters at the same time

- moped-database/metadata/tables.yaml
- https://github.com/cityofaustin/atd-data-tech/issues/15856
1. Create a project phase
2. Edit the phase you created, but only fill in the Status update field
3. Does the activity log ok? 
---
> Exclude audit field from project phase event trigger listener

- moped-editor/src/views/projects/projectsListView/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/15895
https://deploy-preview-1281--atd-moped-main.netlify.app/moped/projects
Toggle the parent project column to be visible. You should see links to the parent project summary page, if the project has a parent. Currently in prod you only see a blank space. 
While testing this, I noticed that the column headers should also have a white background, as opposed to a transparent one. This is what can happen now in prod: 
Confirm this does not happen on my preview branch. 
---
> Bug - Fix parent project name not showing in project list

- moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
No issue, but as I was restoring deleted components from https://mobility.austin.gov/moped/projects/2854?tab=activity_log, I realized that our activity log never expected to handle undeleting. 
https://deploy-preview-1282--atd-moped-main.netlify.app/moped/projects/1925?tab=activity_log
See this one project's activity. i deleted a component, and then restored it. Unlike in prod, it does not say "removed" multiple times. 
**note** I'd like to get this into a patch release this week
> Update activity log handler to represent restoring a project

- moped-database/metadata/tables.yaml
- moped-database/migrations/1708036428508_alter_table_public_moped_proj_notes_alter_column_date_created/down.sql
- moped-database/migrations/1708036428508_alter_table_public_moped_proj_notes_alter_column_date_created/up.sql
- moped-database/seeds/1602292389297_initial_seed_staging.sql
- moped-editor/src/queries/dashboard.js
- moped-editor/src/queries/notes.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
- moped-editor/src/views/projects/projectView/ProjectNotes.js
- moped-editor/src/views/projects/projectView/ProjectPhase/helpers.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryStatusUpdate.js
- moped-toolbox/knack_migration/1_prepare_projects.py
- moped-toolbox/random_project_seeds/index.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/15489
local
- go to a project's notes section and add a note
- confirm that the update is registered in the activity log
- edit the note and check the activity log
- go to the new note record in the db and confirm the created_at, updated_at, created_by_user_id and updated_by_user_id columns are correct. there should no longer be a date_added or added_by_user_id column
- delete the note and confirm in the activity log
- confirm in the db that the record was set to `is_deleted` is `true`
- try adding a note from the project summary page status update modal
- try adding a note from the phases table
---
> replace moped_proj_notes rest connectors with db triggers

- moped-database/views/project_list_view.sql
- moped-editor/src/utils/activityLogFormatters/mopedPhasesActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
https://github.com/cityofaustin/atd-data-tech/issues/15932
https://deploy-preview-1287--atd-moped-main.netlify.app/
- delete a current phase from a project's timeline
- delete a non-current phase from a project's timeline
- check the activity log, the two actions should render the same "x Deleted the phase x"
---
> fixes deleting phase in activity log

- moped-editor/package.json
- moped-editor/src/queries/dashboard.js
The dashboard in prod is not loading because the dashboard query was only fixed for projects a user is a member of, and not the followed projects
https://github.com/cityofaustin/atd-moped/pull/1280
https://deploy-preview-1294--atd-moped-main.netlify.app/moped/dashboard
Load your dashboard and see projects. 
Once this is approved, I'll open a patch to fix prod. 
---
> Update the followed at projects order by as well

- moped-editor/package-lock.json
- moped-editor/package.json
- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryMap.js
https://github.com/cityofaustin/atd-data-tech/issues/16245
When we first added `react-map-gl` v7 during the project components overhaul, there was a error that was fixed using the workaround described [in the code here](https://github.com/cityofaustin/atd-moped/blob/f3720efe86f9cd5d39818fe42bf7f85e04fa4ec7/moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js#L41-L45). This implements the recommended fix, and it is the same one used map upgrade in https://github.com/cityofaustin/atd-vz-data/pull/1398.
https://deploy-preview-1296--atd-moped-main.netlify.app/moped/
1. Go to a project and makes sure the map loads and shows the components related to the project. Test the street/satellite layer toggle, the zoom controls, and that scrolling …
> Use alternate Mapbox error fix

- moped-editor/src/views/projects/projectView/ProjectComponents/RelatedComponentsList.js
- moped-editor/src/views/projects/projectView/ProjectComponents/index.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useComponentLinkParams.js
https://github.com/cityofaustin/atd-data-tech/issues/16334
https://github.com/cityofaustin/atd-data-tech/issues/16332
https://deploy-preview-1299--atd-moped-main.netlify.app/moped/projects/1998?tab=map
Navigate to a project that has related components mapped, such as a project that is part of a parent project, or a project that has subprojects. 
From the components list: 
Select one of the projects components, see that the other components on the map now have gray iconography. 
Now select one of the related components, it should behave the same way as the project components. 
The component id of the component you selected should also be in the url.
Repeat the testing by selecting components from the map. Same as before, the other components should go …
> Add ability to select related components on the map

- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/16159
https://deploy-preview-1304--atd-moped-main.netlify.app/
- go to the project list view and toggle on the description column (it should be off by default) located between 'status' and 'team'
- confirm the descriptions are displayed in the table
- export the table to csv and confirm the description column is included
- I would also recommend pasting a long description into one of the columns to see how it fits into the overall layout (I believe it's out of the scope of this issue but we discussed whether it would be worth truncating longer descriptions)
- toggle off the description column to remove it from the table
---
> adds description column to projects list table

- moped-database/docker-compose.yml
- moped-database/metadata/tables.yaml
- moped-database/migrations/1709753345334_audit_fields_proj_files/down.sql
- moped-database/migrations/1709753345334_audit_fields_proj_files/up.sql
- moped-editor/src/components/FileUpload/FileUploadDialogSingle.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectFiles.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
https://github.com/cityofaustin/atd-data-tech/issues/16156
local
Edit the description of an existing file. Check that your id is the updated by user id and that the updated timestamp works, and that the project itself has a last updated timestamp that matches. 
Add a new file by using the file url option, you can use a random url or comment like "in g drive", and check that the audit fields make sense. 
Note: I merged Tilly's recent work into this, so its using the new and improved trigger function
---
> Add audit fields to moped_project_files table

- moped-editor/src/queries/components.js
https://github.com/cityofaustin/atd-data-tech/issues/16367
https://deploy-preview-1309--atd-moped-main.netlify.app/moped/projects/1936?tab=map&project_component_id=2470
Open the dropdown for the component tags, they should now be in alphabetical order, the Bikeways for example should all be up at the top. 
---
> Order the component tags alphabetically

- moped-database/metadata/tables.yaml
- moped-database/migrations/1711054060504_add_component_work_types_tags_audit_fields/down.sql
- moped-database/migrations/1711054060504_add_component_work_types_tags_audit_fields/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/14946
This PR adds the audit fields and triggers to the `moped_proj_component_tags` and `moped_proj_component_work_types` tables so that their records and the parent component and parent project records get audit column updates when a user adds or updates them.
Local
1. Start up the local stack and find a project.
2. If there isn't already a component, add one to the project.
3. Use the SQL below with your project ID # filled in to monitor the changes that happen through these test steps.
4. Open the component attributes form and add a tag.
5. Use the SQL below to check that:
- the project, project component, and project component tag `updated_by_user_id` match and are your user table ID
- the …
> Configure additional audit field triggers for component work types and component tags

- moped-editor/src/layouts/DashboardLayout/NavBar/NavigationSearchInput.js
- moped-editor/src/utils/gridTableHelpers.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useSearch.js
https://github.com/cityofaustin/atd-data-tech/issues/15050
https://deploy-preview-1289--atd-moped-main.netlify.app/
- try searching a double-quote (") and/or a backslash (\\) in the nav search bar, it should react as if you searched an empty query
- try searching a normal query using an integer and/or a string and confirm it works as expected
- repeat the steps above using the main search bar above the table
- repeat the steps above using the advanced search ``name`` ``contains`` field
---
> escapes double quotes and backslash in search

- moped-editor/package.json
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
n/a
Fixes a mismatch between the column name in the app config for advanced searching status updates and the column in the database view that is queried.
https://deploy-preview-1315--atd-moped-main.netlify.app/moped/
1. Try an advanced search with `Status update contains potential` on staging or visit https://moped.austinmobility.io/moped/projects?filters=%5B%7B%22field%22%3A%22project_note%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22value%22%3A%22potential%22%7D%5D&isOr=false. See error.
2. Try the same search on the deploy preview or visit https://deploy-preview-1315--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22project_status_update%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22val …
> Fix status update advanced search

- moped-editor/src/views/projects/projectView/ProjectNameForm.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/16810
https://deploy-preview-1319--atd-moped-main.netlify.app/
1. Go to a project, create a secondary name.
2. Now delete the secondary name and save, instead of an empty string being saved the value should be nullified. Check in the project list view that there is no trailing hyphen. 
---
> Cannot remove secondary project name

- moped-database/metadata/tables.yaml
- moped-database/migrations/1713466319581_moped_proj_tags_audit_fields/down.sql
- moped-database/migrations/1713466319581_moped_proj_tags_audit_fields/up.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/16180
Local
1. Add some project tags to a project. 
2. Check the `moped_proj_tags` table and see that the new columns have been updated - `updated_at`, `created_at`, `updated_by_user_id`, `created_by_user_id`. 
3. Now check the `moped_project` table, you should see the same values in the audit fields for the project you just added tags to.
4. I dont think there is a way to edit tags right? You can just add or delete them?
5. Test the down migration
---
> Update and add audit fields to moped proj tags

- moped-database/migrations/1713206648608_add_2025_component_tag/down.sql
- moped-database/migrations/1713206648608_add_2025_component_tag/up.sql
- moped-editor/src/queries/components.js
https://github.com/cityofaustin/atd-data-tech/issues/16673
https://github.com/cityofaustin/atd-data-tech/issues/16811
I forgot the Map Bikeways 2025 tag in this PR https://github.com/cityofaustin/atd-moped/pull/1313.
edited to add: And Nathan forgot two tags off the list, adding them here too. 
Also when testing this PR, I noticed that the tags were only being alphabetically sorted by the Type, which meant that 2024 was showing up ahead of 2019. I am further sorting them by name. 
run locally, check for the missing tag in the component tag drop down, and for the missing tag in the project tags
---
> Add additional project tag and component tags

- moped-database/metadata/tables.yaml
- moped-database/migrations/1713896796482_add_full_name_to_list_view/down.sql
- moped-database/migrations/1713896796482_add_full_name_to_list_view/up.sql
- moped-database/views/component_arcgis_online_view.sql
- moped-database/views/project_list_view.sql
- moped-editor/src/queries/dashboard.js
- moped-editor/src/queries/project.js
- moped-editor/src/queries/subprojects.js
- moped-editor/src/views/dashboard/DashboardView.js
- moped-editor/src/views/projects/projectView/ProjectComponents/MoveComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryParentProjectLink.js
- moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js
- moped-editor/src/views/projects/projectView/ProjectView.js
https://github.com/cityofaustin/atd-data-tech/issues/16919
you will have to run locally to do the full test, since there are changes to the metadata and the project list view. 
I've switched the project name to use the full project name in the following places:
project list page, parent project name column
project summary page, parent project name
project summary page, subprojects list, what is shown and the options that are in the autocomplete
project name on the map tab
move component selector on the map tab
dashboard project names
Besides visually seeing the full project name shown, there are few places where I've updated the autocomplete choices. 
Test finding projects to move the component to in the map tab. 
Test the subprojects table on the …
> Use project full name instead of primary name

- moped-database/metadata/tables.yaml
Closes https://github.com/cityofaustin/atd-data-tech/issues/16913
This cleans up the activity trigger for `moped_proj_components`. The update mutation removed from the config is a duplicate of the update already made by a trigger that uses the DB function called `update_self_and_project_updated_audit_fields`.
Local
1. Use a new or existing project and test adding, updating, and soft-deleting components from the map tab.
2. You can use the SQL below to check that the audit fields on the `moped_project` and `moped_proj_components` tables are still updating as expected. Using different test accounts can help see the updates to the user fields more easily.
3. Check the activity log to see that your creates, updates, and deletes display.
```sql
SELECT …
```
> Remove user project update from project components activity trigger

- moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/16778
This PR updates the project tags in the summary view to show inline and wrap instead of as a single column list. I used the [MUI multiline chip example](https://mui.com/material-ui/react-chip/#multiline-chip) for chips with long text on smaller screens.
https://deploy-preview-1323--atd-moped-main.netlify.app/moped/projects/1909
1. Go to the link above
2. Scroll down to the **Tags** section and:
- See that the many tags are now displayed inline and not in a single column
- Click the X icon to remove a tag in the middle of the list and see they adjust to fill the empty space
- Add a tag and see that it adds to the list at the end
- **Question**: Should we update the order that the tag …
> Update tag styles to display inline

- moped-editor/src/queries/project.js
https://github.com/cityofaustin/atd-data-tech/issues/16964
This one updates the project lead and sponsor mutations to accept null when clearing them out in the project summary view.
https://deploy-preview-1327--atd-moped-main.netlify.app/moped/projects/1909
1. Go to staging and try to clear out a project lead or sponsor and see that there is a GraphQL error message shows in a snackbar
2. Go to this deploy preview and try the same, and it should work
---
> [Bug] Unable to remove Lead or Sponsor in Project summary view

- moped-editor/src/components/GridTable/Filters.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/SearchBar.js
- moped-editor/src/components/GridTable/helpers.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/16889
I addressed the bug and also added a few other improvements. Previously when you deleted a filter it would update the URL search params before you hit apply. Now the URL search params are only updated once you click apply. I also made it so that when you edit filters and dont apply your changes, close out of advanced search, and open again, ur unsaved changes are not persisted which is what users said they would expect. 
https://deploy-preview-1335--atd-moped-main.netlify.app/moped/projects
1. Open the advanced search. See that the Search button now says Apply.
2. Create a filter, add an operator and value and hit apply. Open up advanced search again. Clear out the Field part of the …
>  [Bug] Error happens when not completely removing an advanced search filter

- moped-database/hasura-cluster
- moped-editor/src/views/staff/StaffListView.js
https://github.com/cityofaustin/atd-data-tech/issues/17287
Regression introduced and now fixed!
https://deploy-preview-1345--atd-moped-main.netlify.app/moped/staff
do you see mug staff yes? then yay
---
> Fix regression displaying MUG status on staff page

- moped-editor/src/components/GridTable/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/17277
https://deploy-preview-1346--atd-moped-main.netlify.app/moped/projects?search=creator
There is a search already populated in the link above, open the advanced filters and see if a blank filter set is prepopulated
Now try the same here: https://moped.austinmobility.io/moped/projects?search=test. No blank filter!
---
> Add empty filters if basic search is populated

- moped-editor/src/components/GridTable/Search.js
n/a
Small change brought over from the in-progress projects map MVP. h/t to @chiaberry for suggesting to pull this change in and not wait on the map. Targeting for this to release this week.
https://deploy-preview-1348--atd-moped-main.netlify.app/moped/projects
1. Go to the project list view
2. Open the advanced filter dropdown, try out different widths from desktop down to mobile and make sure the dropdown's width stays the same as the search box above it
---
> Update filter dropdown responsive widths

- moped-database/metadata/tables.yaml
- moped-database/migrations/1715277419652_add_moped_proj_partners_audit_triggers/down.sql
- moped-database/migrations/1715277419652_add_moped_proj_partners_audit_triggers/up.sql
- moped-database/seeds/1602292389297_initial_seed_staging.sql
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/17017
local
- run the sql command below and note the values for the audit fields (created_by_user_id, created_at, updated_by_user_id, and updated_at) for the moped_project and moped_proj_partners tables
- add and/or remove a project partner to a project
- updated_by_user_id and updated_at should have updated for all records on the project table, and all audit fields should have updated for the record you created/edited on the moped_proj_partners table
```sql
SELECT
mp.project_id,
mp.updated_by_user_id,
mp.updated_at,
mpp.proj_partner_id,
mpp.created_at,
mpp.updated_at,
mpp.created_by_user_id,
mpp.updated_by_user_id,
mpp.is_deleted
FROM
moped_project mp
LEFT JOIN moped_proj_partners mpp ON …
```
> adds moped_proj_partners audit triggers

- moped-database/hasura-cluster
- moped-database/metadata/tables.yaml
- moped-editor/src/queries/staff.js
- moped-editor/src/views/staff/EditStaffView.js
- moped-editor/src/views/staff/StaffListView.js
- moped-editor/src/views/staff/components/NonLoginUserActivationButtons.js
https://github.com/cityofaustin/atd-data-tech/issues/17286
Test by updating login users here. nonlogin users will not work on the netlify app
https://deploy-preview-1350--atd-moped-main.netlify.app/moped/staff 
1. Change a name or title. 
2. Go back to the page list view
3. see that your updates is there
4. navigate back to the profile you just updated. see that the user details matches your updates
To test updating nonlogin users you will have to test locally
same steps as above, but only for a nonlogin user 
---
> Prevent staff list from showing stale data

- moped-editor/src/views/staff/StaffListView.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/16519
sets an initial filter state to show only active users on the staff list view. users can choose to remove this filter to see all users.
https://deploy-preview-1352--atd-moped-main.netlify.app/
- go to the staff list view
- see that only active users are listed and that this initial filter is already applied
- remove the filter and see that the table displays all users
- refresh the page and see that the initial filter has been reapplied
---
> display only active users by default

- moped-database/migrations/1717191608945_update_user_events_constraint/down.sql
- moped-database/migrations/1717191608945_update_user_events_constraint/up.sql
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/17601
Closes https://github.com/cityofaustin/atd-data-tech/issues/17480
This PR adds a user analytics event so we can track adoption of the projects map, and it also stores the map toggle state in the query params so filtered map view urls can be saved or shared.
Local
1. Start the local stack and explore the `moped_user_events` table in your DB GUI. You should see that the `event_name` column has a new value in its constraint called `projects_map_load`
2. In your local editor, go to the projects list view and toggle the map switch on. You should see a new row in the `moped_user_events` table capturing this event
3. Also, notice that the url query parameters include a new k/v pair for `map` …
> Add map user analytics event and save map toggle state in search params

- moped-database/metadata/tables.yaml
- moped-database/migrations/1716843075050_add_line_rep_to_proj_geo_view/down.sql
- moped-database/migrations/1716843075050_add_line_rep_to_proj_geo_view/up.sql
- moped-database/views/project_geography.sql
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectSummary/utils/useProjectGeographies.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewMap.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewTable.js
- moped-editor/src/views/projects/projectsListView/components/MapDrawer.js
- moped-editor/src/views/projects/projectsListView/components/ProjectsMap.js
- moped-editor/src/views/projects/projectsListView/components/mapStyleSettings.js
- moped-editor/src/views/projects/projectsListView/useProjectGeographies/useProjectGeographies.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/9918
Local
1. Go to the project list view and toggle the Map switch
2. You should see all project components load in the map and a collapsed sidebar on the left of the map
3. Expand the sidebar, see that there is a message that no components are selected, and then collapse it again
4. Hover components on the map and find a place where multiple of them overlap
5. Click and see that the sidebar opens and show a list of unique projects that have components overlapping in the place you clicked
6. You should see that all components associated with the projects in the list remain their status color and the rest are a muted gray
7. If you click a spot on the map where there are not components, the …
> Add sidebar with project details on selection of project components in map

- moped-editor/src/views/projects/projectView/ProjectComponents/TheMap.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useComponentLinkParams.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/useToolbarErrorMessage.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/17518
https://deploy-preview-1355--atd-moped-main.netlify.app/moped/projects/
1. Visit a project (for example
https://deploy-preview-1355--atd-moped-main.netlify.app/moped/projects/2022?tab=map&project_component_id=2627)
2. Move a component from your project to another project, and then try to visit the previous link. Alternately, make up a component id that doesnt exist: (https://deploy-preview-1355--atd-moped-main.netlify.app/moped/projects/2022?tab=map&project_component_id=262300) Make sure you can see the alert. 
3. Test adding a component, but be zoomed out -- verify the "zoom in to select features" alert appears. And disappears when you zoom in. 
4. This project has related project …
> [Bug] Alert that a moved component cannot be found in original project is missing

- moped-editor/src/views/staff/StaffForm.js
- moped-editor/src/views/staff/helpers.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/17285
https://deploy-preview-1358--atd-moped-main.netlify.app/moped/staff/new
Fill out the new user form, every required field. Try a one letter password, you will see both error messages. 
Now try one that is longer than 8, but still not correct. 
---
> [Bug] User password requirement error is not translating correctly

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/NoteInputQuill.js
https://github.com/cityofaustin/atd-data-tech/issues/17450
this is a holdover to replace the react-quill library with a patched version that is compatible with upcoming Chrome updates
we will remove this library once we have [lexical-react](https://www.npmjs.com/package/@lexical/react) in place as our new rich text editor
https://deploy-preview-1375--atd-moped-main.netlify.app/
- open a project notes tab and ensure that the rich text editor is working
---
> replaces react-quill with react-quill-new

- moped-editor/package.json
- moped-editor/src/views/projects/projectView/FundingDeptUnitAutocomplete.js
https://github.com/cityofaustin/atd-data-tech/issues/18340
This PR removes the inactive status filter on the Socrata query that we use to populate the **Dept-unit** dropdown options in the Funding sources table. This will allow Moped users to track spent money (closed or "inactive" Dept-unit numbers).
https://deploy-preview-1380--atd-moped-main.netlify.app/
1. Visit [this filtered financial codes dataset](https://data.austintexas.gov/Transportation-and-Mobility/Transportation-Department-Financial-Codes/bgrt-2m2z/explore/query/SELECT%0A%20%20%60dept_unit_id%60%2C%0A%20%20%60dept_id%60%2C%0A%20%20%60dept%60%2C%0A%20%20%60unit%60%2C%0A%20%20%60unit_long_name%60%2C%0A%20%20%60unit_short_name%60%2C%0A%20%20%60dept_unit_status%60%0AWHERE%20caseless_eq%28%60un …
> Show inactive rows for Dept-unit in Funding table

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
https://github.com/cityofaustin/atd-data-tech/issues/18451
During Chia's demo in dev sync the other day, she showed this bug and then it clicked for me today. All 14 phases should be available for search on this status field. 
https://deploy-preview-1386--atd-moped-main.netlify.app/moped/
1. Go to the projects list view and advanced search on **Status**
2. Notice that **all phases** show in the status badges in the table are now available and not just the simple names.
3. Make sure the search still works.
---
> Update status filter to show all phase options

- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/18270
This PR updates the column used for funding in the project list view from `funding_source_name` to `funding_source_and_program_names`. I also updated the column in the table export while I was in here.
https://deploy-preview-1385--atd-moped-main.netlify.app/
1. Go to the project list view in the deploy preview and search for project ID 1909 or 2031 or any other project with rows in its funding table with both source and program entered
2. You should see both the source and program names separated by a dash. Either source or program if one is present and not the other.
3. Export the table with either the all or only visible option. Check the export to make sure that the same source and …
> Update project list view funding source row and export to show source and program

- moped-editor/src/views/projects/projectView/ProjectComponents/CreateComponentModal.js
- moped-editor/src/views/projects/projectView/ProjectComponents/EditAttributesModal.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/17095
https://deploy-preview-1388--atd-moped-main.netlify.app/
- go to a project map page and click 'new component'
- click outside of the new component dialog, nothing should happen
- close out of the component by completing it or clicking the 'x'
---
> disables modal close on backdrop click

- moped-editor/src/components/ExternalLink.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectECapris.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectWebsite.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryWorkOrders.js
https://github.com/cityofaustin/atd-data-tech/issues/17595
This PR updates the project summary eCapris, website, and work orders links to use the existing external link component so they behave and look the same. It also updates `ExternalLink` with an optional prop to stop the link click event from propagating in order to prevent entering edit mode when navigating to an external link.
1. Open up the project summary page of project 1846 in both [staging](https://moped.austinmobility.io/moped/projects/1846) and in the [deploy preview](https://deploy-preview-1389--atd-moped-main.netlify.app/moped/projects/1846). This project shows the website, eCapris, and work orders links needed to test this PR.
2. Notice that, in staging:
- the external link icon in …
> Clean up click event capture in the eCapris and website links in Project Summary view

- moped-editor/src/views/projects/projectView/DeleteConfirmationModal.js
- moped-editor/src/views/projects/projectView/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectNotes.js
- moped-editor/src/views/projects/projectView/ProjectSummary/TagsSection.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js
https://github.com/cityofaustin/atd-data-tech/issues/18639
https://deploy-preview-1399--atd-moped-main.netlify.app/moped/projects
The delete confirmation modal is used in the 
Funding Table
Work Activity table
Notes
Tags (on project summary page)
Add records on each type, test deleting the record and check that the modal closes. 
Also test cancelling the delete and confirm the modal still closes. 
---
> Close delete confirmation modal only after mutation is complete

- moped-editor/src/utils/dateAndTime.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
https://github.com/cityofaustin/atd-data-tech/issues/18795
We store these phase dates as timestamps w/ timezone in the DB, and this updates the export to format them as dates only since we don't save the actual hours/minutes/seconds of phase dates.
https://deploy-preview-1398--atd-moped-main.netlify.app/moped/
1. Export the project list view and see that **Construction Start** and **Completion Date** are formatted as dates and not timestamps
2. Compare to staging or production exports
3. Check the **Date uploaded** column in the Project files table to make sure it still renders the same. This PR modifies the helper used for it. 
---
~- [ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1- …
> Format phase date fields exported from the project list view as month/date/year

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
https://github.com/cityofaustin/atd-data-tech/issues/18361
Going to use this PR to make some small changes to the funding sources filter and come back to the funding program after some more changes. 
To test: 
https://deploy-preview-1394--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22funding_source_name%22%2C%22operator%22%3A%22string_is_null%22%2C%22value%22%3Anull%7D%5D&isOr=false
Confirm the filter options for the funding sources have been pared down. 
---
The issue description says both funding source and funding program should search on `funding_source_and_program_names`, but I ran into issues with two different entries in the config searching on the same field. Rather than refactor the entire filter config I instead left the funding source searching on the …
> Update project list view advanced search funding sources

- moped-editor/src/components/GridTable/FiltersChips.js
https://github.com/cityofaustin/atd-data-tech/issues/17956
[Deploy Preview with filters applied](https://deploy-preview-1400--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22project_name_full%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22value%22%3A%22test%22%7D%2C%7B%22field%22%3A%22project_name_full%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22value%22%3A%22Mike%22%7D%5D&isOr=false)
Add more than one filter to the advanced search filters. Apply filters
Click on the Matching *all* filters chip. 
Confirm that it switches to any filters, the url params update (the end of the params says `isOr=true`) and the search results update. 
Click again! Search goes back to filtering on all, url …
> Add ability to toggle filters on any or all in the search filters chips

- moped-editor/src/components/GridTable/FiltersChips.js
https://github.com/cityofaustin/atd-data-tech/issues/18940
When I updated the chips to format dates to be more legible, I neglected to check if the date actually existed or was `null`
Compare https://deploy-preview-1410--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22completion_end_date%22%2C%22operator%22%3A%22date_is_null%22%2C%22value%22%3Anull%7D%5D&isOr=false 
to in staging 
https://moped.austinmobility.io/moped/projects?filters=%5B%7B%22field%22%3A%22completion_end_date%22%2C%22operator%22%3A%22date_is_null%22%2C%22value%22%3Anull%7D%5D&isOr=false
---
> Fix filter chips so they don't show a date with "is blank" operator

- moped-editor/src/layouts/DashboardLayout/Footer.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js
https://github.com/cityofaustin/atd-data-tech/issues/19047
Just needed to set the Link to display as `block` for the other styles to take effect. 
I also decided to move a function out of the Footer definition, just to try to cut down on the calls to get the github tag. 
https://deploy-preview-1426--atd-moped-main.netlify.app/moped/projects/2039?tab=funding
I updated the project linked above to have the same long link as the project in the issue description, so compare above to https://mobility.austin.gov/moped/projects/3598?tab=funding
---
- Added test for version link
> Fix text overflowing outside of the Work Order Link column

- moped-editor/package.json
- moped-etl/arcgis/components_to_agol.py
- moped-etl/arcgis/requirements.txt
- moped-etl/arcgis/utils.py
n/a
See https://austininnovation.slack.com/archives/CHZE6BC6L/p1727122151675579
I'll keep running the ETL manually tomorrow to give us time to review. Thanks y'all!
n/a
1. Start the local stack and get a fresh snapshot
2. Go to `atd-moped/moped-etl/arcgis` and follow the readme to set up your `env_file`
3. Run the ETL (the date arg in the command captures the project status update to project 3601 that surfaced the bug):
```bash
$ docker compose run arcgis -d 2024-09-23T19:18:34.543Z
```
4. You should see the script run and log one instance of the message `Invalid HTML tag found in project_id: 3601. Escaping HTML...` for project 3601. Other than the message, you'll see the script deleting updated features from the 4 AGOL layers and replacing the …
> Patch Moped AGOL ETL to handle invalid HTML (into `main`)

- moped-database/metadata/tables.yaml
- moped-editor/src/utils/activityLogFormatters/mopedPersonnelActivity.js
https://github.com/cityofaustin/atd-data-tech/issues/16950
this issue stems from the ``moped_proj_personnel_roles`` table not being associated with a ``project_id`` (rendering that field as ``null``) and therefore not returning records as part of the ``moped_activity_log`` query. investigating this has uncovered some potential tech debt when it comes to the activity log triggers (as noted in this pr), but @mddilley and i decided in the short term to fix the activity log rendering incorrect associations in the ui by assuming that a change made to the ``moped_proj_personnel`` table that is not related to a user or note is related to a role.
https://deploy-preview-1424--atd-moped-main.netlify.app/
- go to a project team and add or edit a team member
- …
> fixes bug where role update is reflected as notes update

- moped-editor/src/queries/components.js
- moped-editor/src/views/projects/projectView/DateFieldEditComponent.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19113
This PR updates the component form validation and behavior so that:
- Completion Date is required if the Phase is **Complete** or **Post-Construction** (both have a simple name of Complete - see `moped_phases` table for reference)
- Completion Date is only available to be added if the Phase is **Complete** or **Post-Construction**
https://deploy-preview-1430--atd-moped-main.netlify.app/
1. Go to an existing project and create a new component in the map tab
2. While using the create form, toggle the **Use component phase** switch on and choose any phase except for **Complete** or **Post-Construction**
3. You should see that the **Completion Date** field is now hidden with any phase except …
> Update component phase inputs to require both phase and completion date if phase simple is "Complete"

- moped-database/metadata/tables.yaml
- moped-database/migrations/1727450092173_rename-school-beacon-component/down.sql
- moped-database/migrations/1727450092173_rename-school-beacon-component/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/19040
I also addressed https://github.com/cityofaustin/atd-data-tech/issues/19171, remove delete permissions for the feature tables
Test locally
Add a new component to the map, search for a Beacon - School Zone
You can see the new name in the sidebar, as well as in the project list view. 
---
> Rename school beacon component

- moped-editor/src/views/projects/projectView/ProjectStatusBadge.js
https://github.com/cityofaustin/atd-data-tech/issues/19256
https://deploy-preview-1440--atd-moped-main.netlify.app/moped/projects?map=false&filters=%5B%7B%22field%22%3A%22project_name_full%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22value%22%3A%22agave%22%7D%2C%7B%22field%22%3A%22project_name_full%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22value%22%3A%22kingfisher%22%7D%2C%7B%22field%22%3A%22project_name_full%22%2C%22operator%22%3A%22string_contains_case_insensitive%22%2C%22value%22%3A%22loblolly%22%7D%5D&isOr=true
Go to the deploy preview, I have prefiltered projects with post construction, planned and preconstruction statuses. Toggle on the map tab and you can see that the project in post construction is …
> Change Post Construction badge color to match Completed

- moped-editor/src/components/GridTable/FiltersCommonOperators.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/19052
https://deploy-preview-1439--atd-moped-main.netlify.app/
- note the number of records in the project view with no filters applied
- add an advanced filter for 'components' 'contains', select an option and note the number of records
- replace the filter with the same query but using the 'does not contain' operator, and note whether the number of records makes up the difference. also check to make sure records with no value in the 'component' field appear.
- repeat the steps with the 'is' and 'is not' operators for a different field (such as 'type')
- confirm that fields with the 'is' and 'contains' operators also include their opposites
---
- Added to the existing "contains" test to check …
> adds components dropdown and contains not operator

- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js
- moped-editor/src/views/projects/projectView/ProjectComponents/utils/form.js
https://github.com/cityofaustin/atd-data-tech/issues/19221
https://deploy-preview-1443--atd-moped-main.netlify.app/moped
Go to a project's map, add a component or edit an existing component. 
Open your developer console, make sure you have default levels on, or at least able to see warnings. 
Toggle on "use component phase"
Choose a phase and subphase. The warning does not appear. 
However, if you choose a phase and a subphase, and then switch to a different phase with subphases, you will see the warning appear. The form [resets the subphase](https://github.com/cityofaustin/atd-moped/blob/main/moped-editor/src/views/projects/projectView/ProjectComponents/ComponentForm.js#L169) when the phase changes, but the new phase's options are loaded in the …
> Fix warnings in Component Form

- moped-database/docker-compose.yml
This PR is intended to close https://github.com/cityofaustin/atd-data-tech/issues/18960. 
This is the easiest thing to test in the world. Please check out this branch, `cd` into the `moped-database` directory, and execute a `hasura-cluster start`. Did it work? Did you get a running postgres container and a running graphql-engine container?
The number of retries is chosen out of thin air -- it can be 30, 300, 3000, whatever -- just not 1. It needs to be large enough to keep `graphql-engine` retrying the PG container long enough for the PG container to initialize the fresh DB, which it does on start before it begins accepting connections. I'm asking that everyone who is a regular moped contributor to test this because really, I want to test that this magic number 30 works for all of us. …
> Docker compose restart pragma

- moped-etl/arcgis/README.md
- moped-etl/arcgis/cli.py
- moped-etl/arcgis/components_to_agol.py
- moped-etl/arcgis/settings.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/19233
Local
**Note: I added a test mode (dry run) that does not update the AGOL dataset to make it easier to test this fix.**
1. Generate an ISO string timestamp using this JS or however you'd like
```js
const dateObj = new Date();
dateObj.toISOString();
```
2. Start your local Moped stack and set up an `env_file` for this script using the instructions in the readme if needed
3. Create a new project and add one point type component (like Bike Box) to **delete** in a later step
4. Create another new project and add one line type component (like Bike Lane) to **edit** in a later step
5. Run the script in test mode from `atd-moped/moped-etl/arcgis` with your ISO string timestamp:
```shell
docker …
```
> Fix missed project and component deletes in AGOL ETL incremental runs

- moped-editor/src/constants/projects.js
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingToolbar.js
- moped-editor/src/views/projects/projectView/ProjectPhaseToolbar.js
- moped-editor/src/views/projects/projectView/ProjectPhases.js
- moped-editor/src/views/projects/projectView/ProjectSubstantialCompletionDate.js
https://github.com/cityofaustin/atd-data-tech/issues/19258
https://deploy-preview-1456--atd-moped-main.netlify.app/moped/projects
Find a project with a substantial completion date (like [this one](https://deploy-preview-1456--atd-moped-main.netlify.app/moped/projects/1848?tab=timeline)) You can see the date now!
Hover over the date to get the tooltip. It is the same text as [Tilly's tooltip PR](https://github.com/cityofaustin/atd-moped/pull/1454).
Now find a project without a completion date, or create a new project. Check that you don't see any date under the Phases title, especially not the dreaded 1/1/1970. 
Add a confirmed date for post construction or complete phase, upon submitting the edit, you should see the date update in the component. 
---
- …
> Show substantial completion date in the Phases table of the project Timeline tab

- moped-database/migrations/1729117324147_create_new_component_tags_for_map_transit_enhancement/down.sql
- moped-database/migrations/1729117324147_create_new_component_tags_for_map_transit_enhancement/up.sql
fixes https://github.com/cityofaustin/atd-data-tech/issues/19489
local
- go to a project and add or edit a component
- in the tags dropdown, check to see the following tags are visible
- MAP Transit Enhancement - 2022
- MAP Transit Enhancement - 2023
- MAP Transit Enhancement - 2024
- MAP Transit Enhancement - 2025
- run the down migration and ensure those tags are removed
---
> adds MAP Transit Enhancement tags

- moped-editor/src/views/projects/projectsListView/helpers.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/19259
based off pr  https://github.com/cityofaustin/atd-moped/pull/1453
I believe the placement of this definition is centralized since we can import this helper object into the project view, but please let me know if there would be a better place to store it!
https://deploy-preview-1454--atd-moped-main.netlify.app/
- in the projects list view, hover over 'Substantial completion date'
- note that a tooltip appears reading 'The earliest confirmed start date of a project phase that has a simple phase name of Complete (Complete or Post-Construction)'
---
- Added to sort by headers test
> adds substantial completion date tooltip

- moped-database/metadata/tables.yaml
- moped-database/migrations/1729197757693_remove_completion_date_from_project_list_view/down.sql
- moped-database/migrations/1729197757693_remove_completion_date_from_project_list_view/up.sql
- moped-database/views/component_arcgis_online_view.sql
- moped-database/views/exploded_component_arcgis_online_view.sql
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
- moped-toolbox/component_geo_processing/settings.py
fixes https://github.com/cityofaustin/atd-data-tech/issues/19435
local
- got to the `project_list_view` table and confirm the `completion_end_date` column is no longer present
- go to the project list view and confirm the 'Completion date' column is no longer present
- click the column list and confirm the field is no longer present
- confirm the csv export works and does not include the column
- go to the advanced filters and confirm the field is not present
- run the down migration and confirm the `completion_end_date` reappears in the `project_list_view` table
---
> remove completion date from project list view

- moped-database/README.md
- moped-database/views/README.md
- moped-editor/src/queries/project.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19437
and the last part of https://github.com/cityofaustin/atd-data-tech/issues/18869 that i owe
This PR adds some sorting that I missed in previous issue scoping, and it adds more info to the database view readme since we learned new information about the GH action output.
https://deploy-preview-1464--atd-moped-main.netlify.app/
1. Go the projects list view and make sure that the dropdown options for funding source and funding program are ordered by name ascending
2. Read the updates to the docs about the DB views. Do they make sense? See any improvements? Thanks!
---
- ~[ ] Product manager added to [QA test script](https://docs.google.com/spreadsheets/d/1n_O6MLh9cwwPf57HUM394Ea-z9uuoEV1-QW4ax …
> Update funding lookup sorting and DB view docs

- moped-editor/src/components/GridTable/Search.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19413
https://deploy-preview-1470--atd-moped-main.netlify.app/moped/projects
Open the advanced search filter, now click out of it to close it.
---
> Add click-away listener to advanced search dropdown

- moped-editor/src/views/projects/projectView/ProjectPhases.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js
https://github.com/cityofaustin/atd-data-tech/issues/19499
https://deploy-preview-1471--atd-moped-main.netlify.app/moped/projects/2039?tab=funding
Check out the Work Activities table on the Funding tab and the Phases table on the Timeline tab. 
Double click in any of the cells to bring up the edit modal. 
Question -- would you want to be able to hit Enter when a cell is selected and also have the edit modal pop up?
---
> Double click to open editor modal

- moped-database/metadata/tables.yaml
- moped-database/migrations/1729197757695_add_agol_geometry_type/down.sql
- moped-database/migrations/1729197757695_add_agol_geometry_type/up.sql
- moped-database/views/component_arcgis_online_view.sql
- moped-database/views/exploded_component_arcgis_online_view.sql
- moped-etl/arcgis/settings.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/19301
**This should not be released until this field is added in https://github.com/cityofaustin/atd-data-tech/issues/17971** ✅
Local
1. Start your local stack and the inspect the `component_arcgis_online_view` database view
2. You should see that a new column called `geometry_type` is added and that it contains "Point" or "Line" as its value. You can check the geometry in the `geometry` to make sure it matches up - Multipoint -> "Point" and MultiLineString -> "Line". 
---
> Populate "geometry_type" in AGOL dataset

- moped-editor/package.json
- moped-editor/src/queries/components.js
- moped-editor/src/views/projects/projectView/ProjectComponents/ComponentListItem.js
- moped-editor/src/views/projects/projectView/ProjectPhases.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js
https://github.com/cityofaustin/atd-data-tech/issues/11429
https://deploy-preview-1473--atd-moped-main.netlify.app/moped/projects/1951?tab=map
I linked a project above that has a component with a different phase from its project, and I gave the component a location description and a long description. 
Test by adding more components with or without phases. 
One thing to note, is that if a component has a phase defined, it will show the badge, even if the component is in the same phase as the parent project. 
---
- Added "Notice that the component list item now has a phase badge."
> Render component phase in the component map list item

- moped-editor/src/views/projects/projectView/ProjectPhases.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/19436
https://deploy-preview-1467--atd-moped-main.netlify.app/
- go to a project's timeline tab and click the delete icon next to a phase
- confirm that an mui confirmation modal appears asking 'Are you sure you want to delete this phase?'
- click 'delete' and confirm the correct phase was deleted
---
> updates phases table to use mui confirmation modal

- moped-editor/src/views/projects/projectView/ProjectPhases.js
- moped-editor/src/views/projects/projectView/ProjectWorkActivity/ProjectWorkActivityTable.js
Reintroducing the changes in https://github.com/cityofaustin/atd-moped/pull/1471 that we accidentally reverted
Deploy preview
These are the same changes from https://github.com/cityofaustin/atd-moped/pull/1471 so compare the two? I tested locally, and this works just like in the original PR.
---
> Restore the fancy double click modal triggering

- moped-editor/src/components/ButtonDropdownMenu.js
https://github.com/cityofaustin/atd-data-tech/issues/19647
https://deploy-preview-1485--atd-moped-main.netlify.app/moped/projects/1973?tab=timeline
Click the Add Phase or Add Milestone button, it shows a menu "add [one record] / From template" 
Click From template. The menu closes when the modal appears. 
Compare to https://moped.austinmobility.io/moped/projects/1822?tab=timeline, where the dropdown menu stays open. 
---
> Make DataGridPro table button dropdowns close after item selection

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
https://github.com/cityofaustin/atd-data-tech/issues/19889
https://deploy-preview-1489--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22project_and_child_project_council_districts%22%2C%22operator%22%3A%22council_districts_array_contains%22%2C%22value%22%3A%226%22%7D%5D&isOr=false
> Add dropdown options from layer_council_districts table to display when the is and contains operators are used for the council district advanced search
Confirm you see the dropdown options when searching on is and contains
---
> Add dropdown options to council district search in project list view

- moped-editor/src/utils/errorHandling.js
- moped-editor/src/views/projects/projectsListView/helpers.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19687
https://deploy-preview-1480--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22current_phases%22%2C%22operator%22%3A%22string_equals_case_insensitive%22%2C%22value%22%3A%22Planned%22%7D%5D&isOr=false
1. Go to [this link](https://deploy-preview-1480--atd-moped-main.netlify.app/moped/projects?filters=%5B%7B%22field%22%3A%22current_phases%22%2C%22operator%22%3A%22string_equals_case_insensitive%22%2C%22value%22%3A%22Planned%22%7D%5D&isOr=false) that contains a non-existent field name in the filter search params part of the url
2. Read the error message displayed in the app and check if it makes sense to you
3. Click the "click here" link to navigate to the DTS service …
> Handle outdated advanced search urls

- moped-database/migrations/1730931541884_reorg_funding_sources/down.sql
- moped-database/migrations/1730931541884_reorg_funding_sources/up.sql
https://github.com/cityofaustin/atd-data-tech/issues/19853
This PR updates the funding source lookup table to reflect the merge of ATD and PWD into TPW.
Local
1. Start your local stack and replicate from the production read replica. Then, use the two test queries below to see that there are now no project funding records that use the soft-deleted `Austin Transportation` and `Public Works` rows. There should be around 66 rows associated with the new TPW funding source.
2. Run the same queries on the production read replica to see that the opposite is true.
3. Check a project like ids 399, 3491, or 553 to see that the project funding records in the Funding table for these projects now show `Austin Transportation and Public Works` as the funding source. …
> Update project fund sources to reflect reorganization

- moped-database/migrations/1731971700176_add_all_way_comp/down.sql
- moped-database/migrations/1731971700176_add_all_way_comp/up.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/19747
This PR adds a component type named **Signage - All Way Stop** and its associated work types.
Local
1. Start up your local stack and test creating a new intersection component called **Signage - All Way Stop**
2. See that **New** is the only available component work type
3. When mapping the component, you should see that it selects from the intersections point layer.
---
> Add Signage - All Way Stop component type

- moped-editor/src/views/projects/projectView/ProjectFiles.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19873
https://deploy-preview-1490--atd-moped-main.netlify.app/moped/projects/1822?tab=files
- Add a file to a project with a very long `Name`. Something over ~25 characters should be enough depending on your viewport. For example, [this project](https://deploy-preview-1490--atd-moped-main.netlify.app/moped/projects/1822?tab=files) in the deploy preview.
- Confirm that the long name has been shorted with the ellipsis `...` styling right before it would overflow into an adjacent cell.
---
> Update Name column in Files table so that long names don't render outside of cells

- moped-database/migrations/1732661952305_department_reorg/down.sql
- moped-database/migrations/1732661952305_department_reorg/up.sql
- moped-etl/README.md
Closes https://github.com/cityofaustin/atd-data-tech/issues/19852
Closes https://github.com/cityofaustin/atd-data-tech/issues/19717
This PR updates the department table to merge ATD and PWD into TPW. It also adds some foreign key constraints that are missing where primary key values from the workgroup, department, and organization tables are used in other tables. It also removes an outdated row in `moped_department` that had an id of 0 and value of 'None' that is not used.
Local
1. Start your local stack and explore the `moped_department` table in your local database. You can connect to the production or staging database to compare the changes in this PR to the current schema and values.
2. You should see that this table now has an `is_deleted` column …
> Update moped_department to reflect reorganization

- moped-editor/src/views/dashboard/DashboardView.js
https://github.com/cityofaustin/atd-data-tech/issues/19820
https://deploy-preview-1494--atd-moped-main.netlify.app/moped/projects/1965/
1. Follow the project linked above, or follow/create any project that has a secondary name. 
2. Go to the dashboard tab, find your project either in my projects or following
3. Click the status badge, a modal will pop up. Confirm the full name is at the top of the modal 
4. Click on status update/comment. Same deal, modal appears, confirm full name.
5. Now click on the milestones percent completed. Modal appears, confirm full name appears at the top. 
---
> Make Dashboard modals show full project name

- moped-database/migrations/1733184698645_add_comp_work_types/down.sql
- moped-database/migrations/1733184698645_add_comp_work_types/up.sql
- moped-database/views/component_arcgis_online_view.sql
- moped-database/views/exploded_component_arcgis_online_view.sql
- moped-database/views/project_list_view.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/20016
The PR adds a new column to the `project_list_view` that creates a de-duped list of all work types added to all components in a project.
Local
1. Start up your local stack and then create a new non-signal project
2. Filter the `project_list_view` database view to the project id that you just created
3. You will see that the value of the `component_work_type_names` is `NULL` since there are no components in the project yet
4. Go to the project map and create a component that has a work type of "New"
5. You should see that the value of the view column updates to `New`
6. Now, create another component with a work type of "New"
7. You should see that the value of the view column is still …
> Add component work types to project_list_view DB view

- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/RecordTable.js
- moped-editor/src/views/dev/LookupsView/settings.js
https://github.com/cityofaustin/atd-data-tech/issues/20325
https://deploy-preview-1513--atd-moped-main.netlify.app/moped/dev/lookups#moped-phases
There are now badges on the table instead of just the phase name. 
---
> Add project phase status badges to the Data dictionary

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryAutocomplete.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryComponentWorkTypes.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectPartners.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryWorkOrders.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/20019
This PR updates the project summary to display the list of component work types. There are also some Prettier changes that came along as I was looking at our components that render the summary items.
Local because of the Hasura metadata update
1. Start your local stack and create a new, non-signal project
2. Go to the summary view and see the new item called `Component work types`
3. Since the new project has no components, the UI should show `-`
4. Now, add a component with a few works types to the project
5. Back in the summary view, you should see each component work types in a list with each type on a new line. The list should not highlight when hovered since it is not editable in …
> Add component work types summary field to project summary view

- moped-database/metadata/tables.yaml
- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewExportConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewFiltersConf.js
- moped-editor/src/views/projects/projectsListView/ProjectsListViewQueryConf.js
- moped-editor/src/views/projects/projectsListView/helpers.js
https://github.com/cityofaustin/atd-data-tech/issues/20020
you will need to test locally because of metadata until Mike's PR gets merged
use prod data if you can
1. from the projects page, click on the columns menu in the upper left hand corner of the table and toggle on the  "Component work types" column
2. Try sorting on that column
3. With the column visible, download records. confirm the column is in your csv
4. now try to advanced search on work types. contains, is, is blank etc
---
> Add component work types to project list view and make exportable/searchable

- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectFunding/SubprojectFundingModal.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/18179
This PR migrates the eCapris subproject funding source table in the "FROM ECAPRIS" modal to use DataGridPro.
Local or [deploy preview](https://deploy-preview-1517--atd-moped-main.netlify.app/moped/)
This table fetches rows from an open dataset by the eCapris subproject ID set on a project. Some IDs match many results while other only match a few so you can use both **11280.006** which will show 18 rows in the table and **7333.001** which will show 4 rows in the table.
You can find other eCapris subproject IDs to test using [this query on the open dataset](https://data.austintexas.gov/Transportation-and-Mobility/Transportation-Capital-Project-Financial-Codes/jega-nqf6/explore/query/SELECT% …
> Migrate subproject funding modal to DataGridPro

- moped-database/metadata/tables.yaml
- moped-database/migrations/1735340549358_add-funding-status-description/down.sql
- moped-database/migrations/1735340549358_add-funding-status-description/up.sql
- moped-database/views/project_list_view.sql
- moped-editor/src/queries/tableLookups.js
- moped-editor/src/views/dev/LookupsView/settings.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19665
Test locally since there is a migration required.
1. Run local migrations
2. Go to https://localhost:3000/moped/dev/lookups
3. Click the "FUND STATUS" button on the far right of the lookups listed and confirm it takes you to the new lookup table at the bottom of the page AND/OR use this link with an anchor tag: https://localhost:3000/moped/dev/lookups#moped-fund_status
4. After scrolling to the bottom of the page, you should see the Fund Status lookups listed as pictured in the screenshot above.
5. (Optional) Test the down migration with a command like `hasura migrate apply --down 1` and confirm that the `funding_status_description` field is dropped properly.
---
- ~[ ] Product manager …
> Add fund status table to Data Dictionary with funding status descriptions

- moped-database/metadata/tables.yaml
- moped-database/migrations/1734717637542_update_workgroups/down.sql
- moped-database/migrations/1734717637542_update_workgroups/up.sql
- moped-editor/src/queries/workgroups.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/19854
This PR updates workgroups with [Sidewalks and Urban Trails](https://www.austintexas.gov/department/transportation-public-works) and updates any users with Sidewalks or Urban Trails as their workgroup to fall under the new workgroup.
Local
1. Start your local stack with production data
2. Explore the `moped_workgroup` table and see that:
- there is now a soft-delete column
- the Sidewalks row is soft-deleted
- the Urban Trails row is soft-deleted
- there is now a row for Sidewalks and Urban Trails (SUTD)
3. Log into the Moped app as an admin (`Moped Test Admin` in our vault or your own account) so you can see the staff form in later steps and then go to the Staff tab
4. Filter the staff …
> Update moped_workgroup to reflect reorganization

- moped-editor/src/views/projects/projectView/ProjectStatusBadge.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/20514
This PR updates the status badge background colors and text to put more emphasis on projects in construction and less emphasis on potential projects. It also differentiates construction with a simple phase of "Construction" from other phases that have a simple phase of "Active" and are green.
https://deploy-preview-1525--atd-moped-main.netlify.app/moped/dev/lookups#moped-phases
1. Go to the deploy preview to see the updated phase colors in the Data dictionary
2. See that "Potential" is badge is now grey with black text and the "Construction" badge is now orange with black text
3. The badge component or badge colors are also used in:
- project list view
- dashboard view
- projects map …
> Update phase badge colors

- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useCsvExport.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/20659
Mike found a bug while testing the Zacate release, that if a user had the type column visible before it was removed from the codebase, localStorage still has that column in its visible column config. 
in your localStorage as the column config
`['project_id', 'current_phase', 'project_lead', 'updated_at', 'type_name', 'funding_source_and_program_names', 'substantial_completion_date', 'parent_project_id', 'components', 'project_id', 'parent_project_name']` 
see that you can still download visible columns, even tho the type_name column is 🗑️ 
---
> check if export column exists before attempting download

- moped-editor/src/views/dashboard/DashboardTimelineModal.js
- moped-editor/src/views/dashboard/DashboardView.js
https://github.com/cityofaustin/atd-data-tech/issues/20860
Adds the snackbar to the dashboard view for feedback on the mutations in the phase and milestone modals
Local or the deploy preview when it is done
1. Follow a project or add yourself to a project team
2. Click into the status badge and add or update a phase. You will see a snackbar appear after editing
3. Do the same with the milestone progress chart
---
> Add snackbar to dashboard view

- moped-editor/src/queries/project.js
- moped-editor/src/views/projects/projectView/ProjectTeam/ProjectTeamTable.js
- moped-editor/src/views/projects/projectView/ProjectTeam/TeamAutocompleteComponent.js
https://github.com/cityofaustin/atd-data-tech/issues/20880
https://deploy-preview-1535--atd-moped-main.netlify.app/moped/projects/
In order to add the email address I changed how the table/field handles its value, moving from just the name or id to the entire moped_user object. (I am going to do something similar to other fields when I refactor all of the autocomplete fields in a next PR). So please test all of the operations with the autocomplete
1. Add a new user
2. Search for Amenity -- there are two of her in the staging dataset, and you should only see two in this list. Current behavior in staging is for her name to multiply as you keep searching for her. 
3. choose anyone, fill out the rest of the row. 
4. Leave some required fields blank. check …
> Show user email in team table dropdown choices

- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectDescription.js
None. This fixes a UI bug from [my PR](https://github.com/cityofaustin/atd-moped/pull/1533) where loading state is triggering error highlighting briefly.
[Deploy preview](https://deploy-preview-1536--atd-moped-main.netlify.app/moped/projects)
1. Make an edit to a project description and make sure the text input doesn't highlight red while the change is saving
---
> Remove loading state from description error prop

- moped-editor/src/components/ApolloErrorHandler.js
- moped-editor/src/views/projects/projectsListView/useProjectListViewQuery/useAdvancedSearch.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/21145
This issue mentions doing further research to refine future improvements to make this even better, i started looking into that and will post my findings in the issue but i want to go ahead and get this PR reviewed
https://deploy-preview-1545--atd-moped-main.netlify.app/moped/
**Steps to test**
1. Go to the [following](https://deploy-preview-1545--atd-moped-main.netlify.app/moped/projects/?filters=[{%22field%22%3A%22project_and_child_project_council_districts%22%2C%22operator%22%3A%22council_districts_array_contain%22%2C%22value%22%3A%227%22}]&isOr=false) URL and see the new more helpful error message
2. Compare with the [previous](https://mobility.austin.gov/moped/projects/?filters=%5B%7B%22field%22%3A%22pr …
> Handle invalid operators in project list view search params

- moped-database/metadata/tables.yaml
- moped-database/migrations/1739832264646_agol_view_is_mapped/down.sql
- moped-database/migrations/1739832264646_agol_view_is_mapped/up.sql
- moped-database/views/component_arcgis_online_view.sql
- moped-database/views/exploded_component_arcgis_online_view.sql
- moped-etl/arcgis/settings.py
Closes https://github.com/cityofaustin/atd-data-tech/issues/20901
**DO NOT MERGE UNTIL https://github.com/cityofaustin/atd-data-tech/issues/20825 is complete.**
This PR adds a column that can be used to surface components that need mapping in Moped from an AGOL map like https://austin.maps.arcgis.com/apps/webappviewer/index.html?id=404d31d56b57491abe53ccfd718fcaee.
Local
1. Run the SQL below and make sure your results match up with the comments
```sql
-- Should return 0 rows
SELECT * 
FROM component_arcgis_online_view
WHERE is_mapped = 'Yes' AND geometry IS NULL;
-- Note this count as the total
SELECT count(*) 
FROM component_arcgis_online_view;
-- Note this count to add to the next count
SELECT count(*) 
FROM component_arcgis_online_view
WHERE …
```
> Add column to components database view to show if a component is mapped or not

- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
n/a
Local or deploy preview
These came straight from the QA sheet. 🍝 
1. Use "Add funding source" button to add a blank funding source to the funding table.
2. Fill out all fields and save the row - verify that you can't use a funding amount with a decimal or non-numeric characters
3. Double-click a cell to edit. Click away to cancel without editing. This should not create a new edit event in the activity log. Now, edit a value this way. This should save the edit and create an activity log row.
---
> Fix funding table to not save on clickaway when there is no change

- moped-database/migrations/1739832264647_agol_view_is_mapped_bool/down.sql
- moped-database/migrations/1739832264647_agol_view_is_mapped_bool/up.sql
- moped-database/views/component_arcgis_online_view.sql
- moped-database/views/exploded_component_arcgis_online_view.sql
n/a
This is an adjustment made to changes made in https://github.com/cityofaustin/atd-moped/pull/1547 based off new info.
Local
Read the small difference between this diff and the one in https://github.com/cityofaustin/atd-moped/pull/1547 and/or test the SQL below. Another similar column to compare to is `is_within_city_limits`.
```sql
-- Should return 0 rows
SELECT * 
FROM component_arcgis_online_view
WHERE is_mapped = true AND geometry IS NULL;
-- Note this count as the total
SELECT count(*) 
FROM component_arcgis_online_view;
-- Note this count to add to the next count
SELECT count(*) 
FROM component_arcgis_online_view
WHERE is_mapped = true;
-- This count plus the previous count should add up to the total number of rows in the view
SELECT count(*) …
```
> Update `is_mapped` to be a real actual boolean

- moped-editor/src/views/projects/projectView/ProjectTeam/ProjectTeamTable.js
- moped-editor/src/views/projects/projectView/ProjectTeam/TeamAutocompleteComponent.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/21199
Even though theres minimal code changes i found this to be way more complicated to untangle/implement than i thought it would! 
https://deploy-preview-1551--atd-moped-main.netlify.app/moped/
1. Test adding new members to a team table. You shouldnt be able to add members that are already on the team, they shouldnt be an option
2. Edit a team member row. You shouldnt see options for members that are already on the team, but you should be able to click on a diff member and then click back to the original member of the row before you edited it and save that, therefore not really updating anything.
3. Test deleting members, updating, adding fields, etc try to break something!
4. See that the …
> Update team table so that duplicate team members cannot be added

- moped-editor/src/views/projects/projectView/ProjectFiles.js
https://github.com/cityofaustin/atd-data-tech/issues/20881
https://deploy-preview-1555--atd-moped-main.netlify.app/moped/
1. Go to a project's files table with files (like project [290](https://localhost:3000/moped/projects/290?tab=files) in a production snapshot) or add some files
2. Use your browser dev tools to set your connection to "Offline"
3. Delete a file and see that an error snackbar appears and the row does not change. 
---
> Fix files table to only remove row from state after mutation succeeds

- moped-editor/src/views/projects/newProjectView/NewProjectView.js
None
This fixes a bug where the user ID of the project creator is missing from the create mutation payload.
Local or deploy preview
1. Create new a project in Moped
2. Check the project list table and make sure the **Created By** column contains the user you are logged in as
---
> Fix missing value for project created by

- moped-database/migrations/1742416187184_update_current_phase_view_drop_distinct_on/down.sql
- moped-database/migrations/1742416187184_update_current_phase_view_drop_distinct_on/up.sql
- moped-database/views/current_phase_view.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/21593
Local preferably for prod data
1. Apply migration
2. Replicate prod data so we can rly make sure everything is snappy and no more timeouts
3. Test "Status is Complete" advanced search filter, this was timing out for me on prod and now is super fast
4. Test other options
5. Test down migration
---
> Remove current phase edge case handling from current_phase_view database view

- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectMilestones.js
- moped-editor/src/views/projects/projectView/ProjectTeam/ProjectTeamTable.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/21366
The problem is that in any column where we are using a function to render the cell without actually changing the internal value of the row (such as `valueFormatter`, `renderCell`), the datagrid internal sort is trying to sort on the fields internal value, not what is rendering in the cell. Oftentimes that value is an Object so the sorting just doesnt work, or in cases like the funding status, it was sorting the under the hood value, not what users see in the column on the front end. 
This means we either need to use a custom sort function on these columns or use `valueGetter` instead which actually sets the value, but in order to implement that we would have to refactor a lot, like the `LookupAutocompleteComponent` and …
> Fix sorting in team, milestone, and funding tables

- moped-editor/src/constants/projects.js
- moped-editor/src/utils/validation.js
- moped-editor/src/utils/validationHelpers.js
- moped-editor/src/views/projects/projectView/NoteInput.js
- moped-editor/src/views/projects/projectView/ProjectNotes.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/21263
This PR adds yup schema validation to status update entry to keep us under the length limit in the AGOL feature service. I also add some docs and updated some variable names and assignments as I was thinking through the code.
https://deploy-preview-1575--atd-moped-main.netlify.app/moped/ or local
1. Find your favorite ipsum generator (https://pizzaipsum.com/, https://baconipsum.com/)
2. Go to a project summary and click into the Status update area to create a new status update
3. Enter a long update, and you should see a validation error message in red and the save button should be disabled when it becomes too long
4. Change the text to be very short and save to make sure you can still …
> Add length validation to project status update input

- moped-database/docker-compose.yml
- moped-database/env_template
- moped-database/hasura-cluster
We are renaming the production moped database when we transfer it today, and this PR reflects that in the environment template.
@mddilley & @chiaberry: I am so surprised that this is the extent of what I think needs to be renamed in the codebase. Do you all agree?
---
> Change default DB name in env template

- moped-editor/src/utils/activityLogFormatters/mopedMilestonesActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
https://github.com/cityofaustin/atd-data-tech/issues/19761
A very snacky snackoo
compare the first activity here
https://deploy-preview-1590--atd-moped-main.netlify.app/moped/projects/1924?tab=activity_log
to 
https://moped.austinmobility.io/moped/projects/1924?tab=activity_log
---
> Update milestone activity log config to show "milestone" instead of "id"

- moped-database/migrations/1745881623802_decom_and_new_subcomponents/down.sql
- moped-database/migrations/1745881623802_decom_and_new_subcomponents/up.sql
- moped-database/recipes/copy_subcomponents_to_components.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/22248, Closes https://github.com/cityofaustin/atd-data-tech/issues/22232
This PR makes changes to component tags to make it easier to mark and filter out decommissioned components and also to be able to add protection type subcomponents like flex posts to some of the Access Control component types.
Local 🙏
1. Start up you local stack and then go to the data dictionary https://localhost:3000/moped/dev/lookups
2. Load the staging data dictionary to compare https://moped.austinmobility.io/moped/dev/lookups
3. Navigate to the component tags section and notice that the tag with type "Bikeways - Performance Measure" and name "Upgrades Existing" now only has name "Upgrades Existing Component"
4. Note …
> Add/edit tags to track decomissioned components and add protection type subcomponents to Access Control components

- moped-editor/src/components/GridTable/FiltersChips.js
- moped-editor/src/components/GridTable/Search.js
- moped-editor/src/components/GridTable/SearchBar.js
- moped-editor/src/views/projects/projectsListView/components/SaveUserViewModal.js
fixes https://github.com/cityofaustin/atd-data-tech/issues/22452
https://deploy-preview-1595--atd-moped-main.netlify.app/
- go to project list view and execute a simple search
- the "save view" button should appear, click on it and note the description field is autopopulated with the search term
- save the view and confirm it appears in the saved views table and the link works
- go to project list view and execute a simple search, then add a filter (or vice versa)
- the "save view" button should appear, click on it and note the description field is autopopulated with the search term plus the filters applied
- save the view and confirm it appears in the saved views table and the link works
try out different combinations, adding a simple search and …
> adds ability to save simple search as view

- moped-editor/src/utils/dataGridHelpers.js
- moped-editor/src/views/dashboard/UserSavedViewsTable.js
- moped-editor/src/views/projects/projectView/ProjectFiles.js
- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectMilestones.js
- moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js
- moped-editor/src/views/projects/projectView/ProjectTeam/ProjectTeamTable.js
Relates to https://github.com/cityofaustin/atd-data-tech/issues/20826 as a follow-on from #1600 
---
- Added to existing test: "As you fill out fields, tab through them to make sure they are keyboard accessible and that choosing a dropdown option by pressing enter does not save the whole row."
> Apply default override to all DataGridPro instances with `editMode="row"`

- moped-editor/src/views/projects/projectView/ProjectNotes.js
- moped-editor/src/views/projects/projectView/ProjectNotes/NoteTypeButton.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/22702
Local
1. Use prod replica data so you can actually see projects that have eCAPRIS statuses
2. Go to the Notes tab of a project that has an eCAPRIS id (For example: https://localhost:3000/moped/projects/3248?tab=notes). Use the toggle button to turn off eCAPRIS syncing
3. See that the "Synced from eCAPRIS" filter button gets disabled and has a tooltip when you hover
4. Turn the syncing toggle back on and see that you can now see and filter to eCAPRIS statuses
5. Test removing the eCAPRIS id from the summary or funding page, then return to the Notes tab and see that the button is disabled again
---
- ~[ ] Product manager added to [QA test …
> Disable eCAPRIS Notes Filter

- moped-database/migrations/default/1750186599182_set_should_sync_ecapris_false/down.sql
- moped-database/migrations/default/1750186599182_set_should_sync_ecapris_false/up.sql
- moped-database/views/project_list_view.sql
Closes https://github.com/cityofaustin/atd-data-tech/issues/23041
Local
1. Before applying migrations, start your local DB and find a project in `moped_projects` table without an `ecapris_subproject_id`. See that the `should_sync_ecapris_statuses = true`. Copy that project id to look up later
2. Apply migrations, now look up that project id and see that it now has `should_sync_ecapris_statuses = false`
3. New projects will default to `should_sync_ecapris_statuses = false`
---
> Update should_sync_ecapris_statuses to false for projects without eCAPRIS IDs

- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/23350
Local
1. Start your local stack and go to https://localhost:3000/moped/projects/3834 and notice that this project does not have an eCAPRIS subproject ID associated with it
2. Run the following statements on your local DB in your DB client:
```sql
-- Query the subproject id and sync status of the project
SELECT project_id, ecapris_subproject_id, should_sync_ecapris_statuses FROM moped_project
WHERE project_id = 3834;
-- Switch the sync column from TRUE to FALSE without changing the subproject id
UPDATE moped_project SET should_sync_ecapris_statuses = FALSE WHERE project_id = 3834;
-- Verify that the value has updated
SELECT project_id, ecapris_subproject_id, should_sync_ecapris_statuses …
```
> Handle eCAPRIS sync activity in log when there is no eCAPRIS subproject id

- README.md
- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
- moped-editor/src/views/projects/projectView/ProjectActivityLogTableMaps.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/22431
Note: It's not in scope here, but I'd recommend a follow-up issue to make it so that Activity Log data automatically refreshes instead of having to manually refresh to see updates in the tab. cc/ @mddilley 
Will have to test locally since this is a branch off a branch.
- Go to any project
- On the summary page...
- a. If the project has an eCAPRIS Subproject ID, delete it. Check the Activity tab and refresh the page (this is needed to requery the activity log data). You should see a new activity log entry that says the ID was removed and the sync was disabled.  
- b. If the project doesn't have an eCAPRIS Subject ID, add one (ex: 7333.001). Check the Activity tab and refresh the page (this is needed to …
> Show eCapris status syncing updates in project activity log

- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummary.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryAutocomplete.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryIconButtons.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryInterimID.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectECapris.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectPartners.js
- moped-editor/src/views/projects/projectView/ProjectSummary/ProjectSummaryProjectWebsite.js
https://github.com/cityofaustin/atd-data-tech/issues/21884
https://deploy-preview-1617--atd-moped-main.netlify.app/
- select a project
- click **project lead**, you should see a checkmark and an x icon button and the checkmark button should be disabled until you make or change the selected value
- click the x icon to confirm the change is canceled
- change the value and save the change, then click the field again to ensure the checkmark icon is disabled until you select a new value
- try doing the same thing without using a mouse by tabbing and shift tabbing through the options
- repeat the steps above for the remaining fields:
- Sponsor
- Partners
- Public process
- Website
- Interim MPD (Access) ID
- eCapris Subproject ID
---
- ~[ ] Product manager …
> 21884 update project summary check and x icons

- moped-editor/src/components/GridTable/Filters.js
Closes https://github.com/cityofaustin/atd-data-tech/issues/23129
https://deploy-preview-1616--atd-moped-main.netlify.app
1. First test the behavior on [staging](https://moped.austinmobility.io/moped/projects). Open the advanced search on the projects page and select Full name as the field, and then type "        test    " in with a whole bunch of spaces before and after. See that you get zero results.
2. Also check the link in the url and see a whole bunch of +++ before and after your search value 
3. Now test this deploy preview, go to the projects list page and open the advanced search. Click on Full name and type "      test         " with a whole bunch of spaces before and after and see that now you get results. Open the advanced search again and …
> Trim blank spaces from advanced search inputs

- moped-editor/src/utils/dataGridHelpers.js
- moped-editor/src/views/dashboard/UserSavedViewsTable.js
- moped-editor/src/views/projects/projectView/ProjectFiles.js
- moped-editor/src/views/projects/projectView/ProjectFunding/ProjectFundingTable.js
- moped-editor/src/views/projects/projectView/ProjectMilestones.js
- moped-editor/src/views/projects/projectView/ProjectSummary/SubprojectsTable.js
- moped-editor/src/views/projects/projectView/ProjectTeam/ProjectTeamTable.js
Closes https://github.com/issues/assigned?issue=cityofaustin%7Catd-data-tech%7C22957
I fixed this bug for all our data grid tables, it was also happening in the milestones table.
Netlify
1. Open staging and see what happens when you create a new row (in subprojects, team, or milestone tables) and then ESC, you are left with a weird empty row.
2. Now open the netlify link and test doing the same thing with these tables. Instead, the new row should be deleted when you press ESC.
---
> Fix empty row that is added to table when ESCing out of adding new team member and subproject

- moped-editor/package.json
- moped-editor/src/utils/activityLogFormatters/mopedComponentsActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedContractsActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedFilesActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedFundingActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedMilestonesActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedPhasesActivity.js
- moped-editor/src/utils/activityLogFormatters/mopedProjectActivity.js
- moped-editor/src/utils/activityLogHelpers.js
- moped-editor/src/views/projects/projectView/ProjectActivityLog.js
No issue related. This is to patch up how our current activity log code handles the old Hasura event schema.
Local please so that you can look at a project that uses the old schema
1. Go to https://localhost:3000/moped/projects/232?tab=activity_log and make sure that the activity log loads. This shows that the activity log works with the old event schema.
2. Expand the collapsible section below and see a full page screenshot of a project where I created, edited, and deleted all project record types. This shows that the code is working with the new event schema.
3. I don't want to create a bunch of duplicate work so I am good with y'all trusting the screenshot. You can test if you like.
<details>
<summary>Expand me!</summary>
**Moving a component from …
> Update activity log to handle old and new Hasura event schema when creating fields list

- moped-editor/.env-cmdrc
https://github.com/cityofaustin/atd-data-tech/issues/21910
We were able to do all our testing of the PR based off a deploy preview, and I failed to include this one line prior to merge that would flip staging actually over to the new API. This change for staging will take effect on merger of this PR to `main`, I believe.
We'll see a second PR just like this one for production real soon.
Freebie here, just take a look at the one-line-diff. Does it match the PR review section? 
---
> Switch Staging to ECS API endpoint

- moped-editor/src/auth/user.js
This fixes a third place where the user DB row needs to be set. It also updates how we handle setting user state and local storage after the SSO redirect.
Local if you want?
1. Check this file to see that the other two `initializeUserDbObject` calls work this same way. They return the user data and then we set it in local storage. I just forgot to update this one.
---
> Fix missed update to new way initializeUserDBObject works

- moped-database/migrations/default/1758551918596_adjust-projects-per-district-view/down.sql
- moped-database/migrations/default/1758551918596_adjust-projects-per-district-view/up.sql
- moped-database/views/council_district_project_distribution_analytics.sql
This PR hopes to close https://github.com/cityofaustin/atd-data-tech/issues/24669. 
* Replicate some live data into your local database and then apply the migration in this feature branch.
* Connect to your database and open the view `council_district_project_distribution_analytics`.
* I hand-calculated project 22's results in QGIS, and I got 27.10% for one and 72.90%. Are these figures close to what you see in the table? 
* They don't have to match exactly -- i have made no attempt to align the resolution of the buffers or how it handles end-caps. Close enough works here.
* If you want, please feel free to spot check other projects.
* Take a look at the code. Do you see:
* An inner join in the first CTE to remove soft-deleted projects?
* The view dissolves the buffers created from the …
> Update council_district_project_distribution_analytics view's buffer distance, dissolve behavior, and deleted-project support
